### ISSUE TITLE
Looking for contributors! (bot)

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#102]
As we continue to evolve, we are looking for more contributors for Modmail! If anyone would want to volunteer to help out, tell us in Discord.

Necessary skills:
- Competent in Python 3.7
- Competent in discord.py 1.x

Optional skills:
- Competent in MongoDB (backend database for config and logs)

**Comment by kyb3r** [comment]
@iamluca take a look in the [project](https://github.com/kyb3r/modmail/projects/3) and see what you can do in the todo section.

**Comment by WebKide** [comment]
Can help

**Comment by fourjr** [comment]
Going to close because I don't like open issues (but we are always looking for contributors).
