### ISSUE TITLE
The install guide isn't helping me at all.

### ISSUE THREAD

**Issue by jayden8923** [kyb3r/modmail#105]
This part of the guide doesn't make any sense. While making the app none of these fields show up nor when it is created. Please help.

> Input your bot token into the TOKEN field.
Input your API token into the MODMAIL_API_TOKEN field.
Put the ID of your Server into the GUILD_ID field.
Put your own ID in the OWNERS field.
Click the deploy app button and wait for it to finish.
I

**Comment by kyb3r** [comment]
You should see this page when you click the deploy to Heroku button 
![image](https://user-images.githubusercontent.com/29310830/50731988-f6007c80-11c4-11e9-90b3-3fcc71f8da52.png)

**Comment by jayden8923** [comment]
I didn't see it. I will try it again tomorrow.
