### ISSUE TITLE
The ability to add a reason as to why someone is blocked

### ISSUE THREAD

**Issue by alazymeme** [kyb3r/modmail#106]
This could be especially useful for larger servers, for people asking why x was muted. Could potentially look a little like this (in the bot info room)
![image](https://user-images.githubusercontent.com/12804673/50750950-1eef4300-1293-11e9-92b0-a86fdd989eb1.png)

**Comment by kyb3r** [comment]
Added this in v2.0.8 however you will need to reblock everyone as blocked users are now stored in the database. Doing `blocked` will show you blocked users alongside the reason for being blocked.
