### ISSUE TITLE
Adding reactions as a response to messages

### ISSUE THREAD

**Issue by shushia** [kyb3r/modmail#110]
Scenario: 
User sends a message to the bot to bring awareness to an issue, no response is needed. Staff can add a reaction to the bot's embed in the thread channel, which the bot then adds to the original message in DMs so the user knows their issue was acknowledged before it was closed (more of a politeness thing?).

Scenario 2: 
User sends a message to the bot, staff responds with a solution. User responds with a reaction on the bot's message which is then announced in the thread channel kind of like a "my issue was solved" response, and the thread can then be closed. 

This would reduce a lot of clutter in terms of responses and notifications of things like "thanks!" "no further questions" for a lot of the more tech-savvy discord users; also for those who are shy with messaging.

The bot could add this information to the bottom of messages. "If this resolves your issue/if you don't need further help, please click on the checkmark below!" Also somewhat related, but maybe change the thread closing message to something like "@/User has closed this modmail thread. Feel free to message us again if your issue was not resolved!"

Sorry for using the scenarios, I wasn't sure how else to explain. Hope it makes sense!

**Comment by fourjr** [comment]
1. We react to every message saying if it was sent or not. Conflicts?
2. Bot won't work with custom emojis that he doenst have any access to.
3. User might misunderstand or ignore the reaction

closing already gives a notification so what's the point

if you just want a "we got it" just close it

**Comment by fourjr** [comment]
and btw, scenarios are great thx
