### ISSUE TITLE
Blocked users still able to message bot

### ISSUE THREAD

**Issue by alazymeme** [kyb3r/modmail#113]
![image](https://user-images.githubusercontent.com/12804673/50877708-d5cbfa00-141e-11e9-9b76-8799fb2973aa.png)

**Comment by kyb3r** [comment]
Wow I'm gonna look into this rn

**Comment by kyb3r** [comment]
Fixed this in `v2.0.10`. Seems like I forgot to change something when migrating blocked users to the db.
