### ISSUE TITLE
Support multiple bot presence activities

### ISSUE THREAD

**Issue by KeremUygann** [kyb3r/modmail#116]
İ think add bot a this property.
We can change bot status watching and listening. 
<h2> Example </h2> 

*Watching* DM me for help!
*Listening* DM me for help!

<h2>Example Command</h2>

!status-watching "Status"
!status-listening "Status"

**Comment by alazymeme** [comment]
What good would this serve? What is the reasoning for wanting this? Remember this is a modmail bot, not a general moderation bot

**Comment by WebKide** [comment]
That's a good idea, I had considered this, particularly to have a couple of default status that could rotate periodically, to add a bit more dynamism to the server

**listening to** you in DM
**watching** over you
**playing** with the Mods

or any kind of ways that it could be presented

**Comment by kyb3r** [comment]
Thinking of the format: `status [playing/watching/streaming/listening] [message]`

**Comment by KeremUygann** [comment]
> That's a good idea, I had considered this, particularly to have a couple of default status that could rotate periodically, to add a bit more dynamism to the server
> 
> **listening to** you in DM
> **watching** over you
> **playing** with the Mods
> 
> or any kind of ways that it could be presented

Yes, like this.

**Comment by iamluca** [comment]
Support this
