### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CleverSource** [kyb3r/modmail#118]
Anonymous replies based on a user's role in a Discord & automatically responding without using ?reply command would be awesome! And automatic anonymous replies. The reasons for this are mainly so I can protect my moderators identity and in my opinion a user has no reason to know who they are talking to because they could show bias towards one moderator. I would also like it to instead of saying Moderator there role name, so an example would be:

User messages modmail bot saying: "Hey there"
Moderator replies and the modmail bot uses the embed and does like "Support Team: How may I help you?" 

This modmail bot in my opinion is amazing due to the fact I can easily integrate it with anything since it uses your own website for logs, but I would prefer access to self-hosting the logging system myself as well but this is a great addition because it allows for Heroku hosting much easier compared to the other known modmail bot's. Keep up the great work and I hope to see some or all of these features in the near future. 👍

**Comment by kyb3r** [comment]
An issue for anonymous replies already exists, it's in the todo list #107. 

- you can set your own mention with the `mention` command.
- By default, modmail is hosted in one guild? Hosting in separate guilds is optional.
- You can change the playing status with the `status` command.

You can technically host your own [backend](https://github.com/kyb3r/webserver), although there are no instructions for setting it up yet.

**Comment by CleverSource** [comment]
What I mean is a custom message the bot says for if a thread is opened. How would you optionally host it in separate guilds?

**Comment by CleverSource** [comment]
Also, assuming the ?config command just updates the config.json, can everything entirely be covered in config.json such as the "disable_autoupdates" already in there but it'd be set to a default of true or false. I would think most people would easily be able to set everything up from the config.json rather than having to keep using the ?config command each time if that makes any sense.

**Comment by kyb3r** [comment]
Yes, unfortunately, we are still working on documenting a lot of stuff, I need help for that. You can host it in a separate guild via adding a config var `MODMAIL_GUILD_ID` as the guild that is the inbox server and `GUILD_ID` for the server that the members are messaging from. 

Also custom messages are in the to do list: #87

**Comment by CleverSource** [comment]
Okay awesome, do you think I can get a list of everything config variable possible for now? I preferrably want to just set everything up in the config.json rather than the ?config command (unless for some odd reason the ?config command and config.json are separate from each other and what you do with the ?config command isn't towards the config.json).

**Comment by kyb3r** [comment]
The config.json / environment variables on Heroku are there for stuff that you wouldn't normally change ever (guild_id, token, owners). However, the config command is used for changing dynamically, and the config variables you set via the command are stored in the DB, for persistence. 

Heres a list of valid keys: prefix, blocked_emoji, mention, log_channel_id, status, main_category_id, sent_emoji, disable_autoupdates

**Comment by iamluca** [comment]
This should be included in the config of the docker instance. I think that not including it makes the bot not be able to use 100%.
