### ISSUE TITLE
Temp block

### ISSUE THREAD

**Issue by WebKide** [kyb3r/modmail#120]
Didn't find it, so here it is:

Maybe work the block command to block user for 24 hrs by default, but have params so that it can be set to any given time, or permanent

`m.block [hh]`
`m.block 12` blocks the user for 12 hours
`m.block` blocks user for 24 hours
`m.block permanent` blocks the user until a mod unblocks with `m.unblock` command

**Comment by kyb3r** [comment]
Maybe block permanently by default instead.

**Comment by iamluca** [comment]
I support temporarily blocking a user if they are spamming or not.
