### ISSUE TITLE
Make log keys more readable 

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#122]
At the moment it is hard to differentiate logs when u want to access specific logs by a specific a specific reason.
![](https://i.imgur.com/XqgMW4r.png)

My proposal is that you rename the logs ID to 
[Ticket Authors name][Closed ticket by Moderators name] [Title descriptions: Ticket authors first message to the DM. 

well of course some first msgs to the bot can be long so maybe add a character limit to the title name

**Comment by kyb3r** [comment]
Yea I'm thinking of adding a MM:HH prepended to this?

**Comment by maidos** [comment]
not sure if the timestamp is actually needed because ppl just need the context of the mod ticket log title to make it easier to find the right one

**Comment by maidos** [comment]
i dont know coding so i just photoshopped one

![k8an5nc](https://user-images.githubusercontent.com/4606415/51076032-b093f180-1693-11e9-9504-99c009422403.png)

**Comment by kyb3r** [comment]
Btw the logs command only displays logs for a specific user, so "Ticket By" is redundant. I'll try and add the closer in there as well though.

**Comment by maidos** [comment]
For bot-logs channel this type would be ideal imo when it comes to "Ticket by"

![k8an5nc](https://user-images.githubusercontent.com/4606415/51076156-3c5a4d80-1695-11e9-8b58-dbe693a66a59.png)

In this new picture i inclluded userID for archiving purposes because if a user leave or when discord bug out you can no longer see the actual username instead see the userID so we can use that userid to search through bot-logs channel to easier pinpoint the actual ticket.

But for the personal logs, i do agree ticket by is redunant. We could keep the phrase Closed by (Moderator): Ticket description (logID)

**Comment by fourjr** [comment]
@kyb3r is this live?

**Comment by kyb3r** [comment]
Its not final

**Comment by kyb3r** [comment]
Live in v2.2.1 
![image](https://user-images.githubusercontent.com/29310830/51083078-dee30100-1767-11e9-9852-264c92602ec1.png)

**Comment by kyb3r** [comment]
@maidos does this look good?

**Comment by maidos** [comment]
yes it looks great andd alot organized. thanks
