### ISSUE TITLE
Use discord for login, github oauth optional 

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#126]
Citing security concerns... 

Use discord oauth for dashboard login 
Github oauth is also necessary for auto update features or `update` command but optional

## Checklist
- [ ] Backend callbacks (discord oauth) 
- [ ] Frontend UI 
- [ ] Backend new endpoints (add token)
- [ ] Backend error handling (no token found)

**Comment by kyb3r** [comment]
I think we should do fork syncing client side via a personal access token. And remove GitHub OAuth completely.

**Comment by fourjr** [comment]
This is going to be obsolete as we deprecate modmail.tk
