### ISSUE TITLE
Personal Mongo URI Hosting

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#127]
Instead of using centralised DB, some users might opt for their own personal uri.

Allow support for it.

## Discussion Questions
Are we even going to interface with Modmail API anymore? Is everything going to be handled in the bot?

**Comment by kyb3r** [comment]
If a connection URI is supplied, then there's no need for the bot to interact with the API. The API would now only be a service for convenience instead.

**Comment by kyb3r** [comment]
We could also ask for a personal GitHub access token instead, to handle fork syncing client side.

**Comment by kyb3r** [comment]
We could implement this without breaking existing code by making a separate `ModmailApiClient` class that does everything client side.
