### ISSUE TITLE
Automated replies

### ISSUE THREAD

**Issue by SharpBit** [kyb3r/modmail#130]
Reply with a snippet if a user sends a certain phrase

For example when they just say "help" reply with snippet "hi" (ex for bandits modmail)

**Comment by kyb3r** [comment]
`!autoreply add "phrase" [response]...

**Comment by kyb3r** [comment]
Would this change the `thread_creation_response` message or what?

**Comment by SharpBit** [comment]
Is that the embed when they first message the bot? You could make it ping @here on the next one that they send but that's up to you

**Comment by fourjr** [comment]
Message is sent to user:
![image](https://user-images.githubusercontent.com/28086837/51186063-b26be800-1913-11e9-9365-31cf9655a77d.png)

**Comment by SharpBit** [comment]
Oh idk

**Comment by SharpBit** [comment]
Yes, change `thread_creation_response` to the `response` of `!autoreply add "phrase" [response]...`

**Comment by SharpBit** [comment]
@kyb3r

**Comment by Taaku18** [comment]
dupe #649 (continue discussion there)

**Comment by Taaku18** [comment]
Whoops my bad, misread the question, ignore the past 5 events

**Comment by officialpiyush** [comment]
1 year uwu
