### ISSUE TITLE
Mark Releases

### ISSUE THREAD

**Issue by Taaku18** [kyb3r/modmail#136]
Modmail is an ever-growing project, we should start to follow more conventions of larger projects.

When there's a new version of Modmail available (major, minor, patch, pre-release, dev, alpha, beta, etc), we should mark [releases](https://github.com/kyb3r/modmail/releases) in GitHub.

https://blog.github.com/2013-07-02-release-your-software/

An excellent example: [ReactiveUI](https://github.com/reactiveui/ReactiveUI/releases).

**Comment by kyb3r** [comment]
True, I've been meaning to use GitHub releases, but have been lazy.

**Comment by Taaku18** [comment]
There. All historic releases are tagged and marked as release.
