### ISSUE TITLE
Request for a “remind” command

### ISSUE THREAD

**Issue by Taaku18** [kyb3r/modmail#137]
## Abstract

Reminders can be used to remind a user, role or everyone a message at the 
specified time.

## Usage

To add a reminder:

    ?remind <@user—defaults sender> [time] [message]

View scheduled remainders (either one, open for debate):

    ?remind <@user—defaults sender>
    ?remind show <@user—defaults sender>

Cancel a remainders:

    ?remind cancel|remove|delete [reminder-index]

Clear all reminders:

    ?remind clear [@user or “all”—defaults sender]

## Storage

Reminders will be stored in config vars, loaded upon bot load, and saved upon 
the creation of the reminder.

Roughly:

    ‘reminders’ : [
        {‘user id or “everyone”’:
            [‘channel id’, ‘time’, ‘message’]
        }, 
        ...
    ]

Or even better, a database relation.

## Permission

No additional permission required.

## Use Cases 

👆 No need. To your discretion.

- - -

If you like this command to be implemented, drop a 👍 or 🎉 and reply with why you might think if this is a good idea. If not, 👎, and reply with why not.

Your opinion is very important during this phase, and if you’re able to aid the implementation of this command after the planning stage (if this passes), please mention this as well; we’re always looking for more contributors.

 Thanks for your time!

**Comment by kyb3r** [comment]
I assume this will be implemented similarly to how scheduled closing works.

**Comment by fourjr** [comment]
imo, this doenst seem like "a modmail feature". Sure, it's a useful feature, but does it help in modmail?

I don't see any justification here about how this is related to modmail.

**Comment by kyb3r** [comment]
You could make a plugin that implements this tho?

**Comment by Slippy1010** [comment]
Request for an anonymous version of ^reply, that has no embed of your username and tag.
