### ISSUE TITLE
You should be able to change the bot profile picture, and the name!

### ISSUE THREAD

**Issue by Scythic21** [kyb3r/modmail#138]
Since the bot is selfhosted, you should be able to change the profile picture and name with a command.

**Comment by fourjr** [comment]
For now, you can do it via [the discord developers website](https://discordapp.com/developers)

**Comment by HeresHavi** [comment]
Having commands available to change this without going to the Discord Developers Website is nice but I think the way you do these two things is good enough. If you wanna change the name and profile picture, do that through the DD site.

**Comment by fourjr** [comment]
Out of scope of what Modmail should do.
