### ISSUE TITLE
Ability for bot to function even when api is down.

### ISSUE THREAD

**Issue by kyb3r** [kyb3r/modmail#140]
Currently, the bot breaks when the API is down, I propose that we make changes to the code so that the core functionality of Modmail continues to operate even if the API is down.

**Comment by fourjr** [comment]
We could use a cache system for this and ping the api so it'll send requests when it's back up.

**Comment by Taaku18** [comment]
I'll start working on this issue right away. Changes will be made in the newly created [dev branch](/kyb3r/modmail/tree/dev). 

Make the bot more self-reliant, the core functions should run without using any external services. When the API returns, the bot can communicate all the unsent data with the API.
