### ISSUE TITLE
Suggestion: ability to have group conversation. 

### ISSUE THREAD

**Issue by Sasiko** [kyb3r/modmail#143]
Why group conversation between moderators and multiple server members in one server ticket? 
Depending on the server we can invite several server members into one single ticket to either mediate conflicts caused in public and have moderators being the mediator between two parties. 
This can also be utilized to solve scamming issue so we can both side of story. 

So for regular server members they are able to communicate with each via mod mail as the tool.

Group dm conversation already exist in discord but that requires you to add the person as friendlist which drags time further. And you would want to leave the group conversation when issue is resolved because you dont want to talk with them directly anymore.
Also mod mail has ability to save logs so we can access in future should it be necessary

## Below edits are done by the dev team
Tracking features:
- [x] #3054 
- [x] #3065 
- [x] #3066
- [x] #3053
- [x] #3052
- [x] #3082

**Comment by kyb3r** [comment]
Would this exist as a command to add more people to an existing thread?

e.g. `adduser [user]`

Thoughts on implementation?

**Comment by maidos** [comment]
yeah basically a moderator command to invite multiple users to an existing ticket. our mod mail will dm the user with a msg from moderator so we can explain whats happening. server members can just dm regurlarly to receive msg from moderators and other server members. also ability to remove them off from the ticket if both parties ends up going at each other.

**Comment by wolfier74** [comment]
Good idea to add more users to 1 thread

**Comment by ririko5834** [comment]
Yes, this would be useful

**Comment by chasejkal2004** [comment]
Would like to boost this

**Comment by ChrisvanChip** [comment]
I'm really looking forward to see this feature, it's a huge addition & increases the use cases significantly.

**Comment by chasejkal2004** [comment]
It is coming paid fourjr to make it @ChrisvanChip

**Comment by fourjr** [comment]
# v3.10.0-dev4 Changelog

- New config options (image)
- #3054 
- #3065 
- #3066
- Silent adduser/removeuser

![image](https://user-images.githubusercontent.com/28086837/128515717-9116dece-a5e5-4fd3-9b03-5156c826a16c.png)

**Comment by ChrisvanChip** [comment]
There's one thing left prior it being ideal for investigations, restricting users to speak (especially the ticket author).

Since you can't remove the original ticket author (for obvious reasons), it would be nice to disable "receiving" and "replying" separately or both at once. 

The commands could be (name is just an example):
`?disableuser <ID> <receiving/replying/both>`
`?enableuser <ID> <receiving/replying/both>`

_Oh and please make the cooldown configurable by config options, I had to edit it in the source code now._

Beside these two suggestions, amazing work @fourjr! 🎉

**Comment by fourjr** [comment]
The cooldown is done due to ratelimits. Please create a new github issue for the feature request. Thanks for the feedback!
