### ISSUE TITLE
auto config option for note commands

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#147]
This is so we dont need to execute note command everytime moderators want to have internal discussion taken place in tickets. Sometimes tickets that are raised by recpients can contain topics that would involve stafff to discuss wether the recipients points are valid are not. 

Its pretty common for moderators to have internal discussion in mod tickets rather than a staff channel to keep it relevent. 

Enable auto note would mean we dont need to use note command everytime.

**Comment by kyb3r** [comment]
How about a config var such as `enable_internal_message_logging`, which lets the bot log internal messages (non-thread messages) as well. This way, the log viewer would then display internal messages with a separate tag.

**Comment by maidos** [comment]
ya that can work

**Comment by kyb3r** [comment]
Yes @fourjr that's what I was thinking as well, but I don't have the expertise to implement the toggle sadly.
