### ISSUE TITLE
more config options

### ISSUE THREAD

**Issue by pozzzzy** [kyb3r/modmail#148]
There is a very high lack of customization for the bot (discluding editing source) and was wondering if certain features could become configurable, such as embed colors, messages the users receive, messages the moderators receive, etc.

**Comment by kyb3r** [comment]
Currently, things you can configure that pertain to customization are:

- `thread_creation_response` 
- `sent_emoji`
- `blocked_emoji`

They can be changed using the `config` command.

Adding the ability for extra configuration is trivial, it's just a matter of a few code changes. Usually, these requests are a low priority and depends on demand. However, feel free to create a pull request that introduces config variables that change what you want to change.

**Comment by kyb3r** [comment]
I added some customization options in the latest update. 

![image](https://user-images.githubusercontent.com/29310830/51582294-84903000-1f1f-11e9-8f76-49aa1459da50.png)
