### ISSUE TITLE
Event, on_join greets member by dm

### ISSUE THREAD

**Issue by WebKide** [kyb3r/modmail#152]
Say that a web designers guild wants all new members to be greeted by their instance of Modmail upon joining, that way people receive vital info about the guild and get their Modmail ticket started

This is particularly good for businesses and similar enterprises, maybe also youtubers would implement it as well

**Comment by fourjr** [comment]
Use another bot for this. Or wait for plugins ;)

**Comment by WebKide** [comment]
But this is super useful! So many servers will make use of this feature

**Comment by fourjr** [comment]
Why don't we add mod commands as well? So many servers will make use of this feature.

It simply isn't in the scope of mod mail bot. You can add it via plugins in the future though 🔮

**Comment by WebKide** [comment]
I'm working on a mod bot, the idea of a modmail bot that messages new members upon joining server makes more sense than a modbot that sends a message but doesn't have capability to interact via dm

**Comment by WebKide** [comment]
Case study 3:
Youtuber server wants members to send a dm with main rules, a simple greeting custom message thanking member for joining, and a reminder that they can dm modmail with suggestions or questions, which they can do right there and then, or at a later time by going to their dms

**Comment by WebKide** [comment]
Another useful even would be `on_guild_join` to dm guild owner and explain how it works, maybe a simple embed with the most asked questions
