### ISSUE TITLE
suggestion: auto close ticket after specific time

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#161]
Most companys support ticket system including discord close the ticket automatically if the user doesnt respond **after** moderator sent a reply within  a specific timeframe normally within 48 hours. 

And allow us to edit a custom message for bot to  send to the recipient explaining why the ticket got closed.
Perhaps allow modmail to just that aswell?

**Comment by kyb3r** [comment]
How about a config var `auto_close_thread` with the value set to the amount of seconds to close after

**Comment by fourjr** [comment]
Use `config` command? and support RDanny time?

**Comment by HeresHavi** [comment]
Exactly.

`auto_closed_thread` would be nice. Also what Maidos mentioned, make sure it resets when a moderator replies to the thread.

**Comment by Sandaru24** [comment]
yes I like the idea 👍

**Comment by maidos** [comment]
i would like to expand this feature where the bot can send a customized message like

"this thread has been closed automatically due to no response from you after  X days"

**Comment by kenng69** [comment]
Only do that when the thread is not answered for a specific amount of time.

**Comment by StephenDaDev** [comment]
@maidos That could be the close message.

**Comment by daegontaven** [comment]
I've implemented this in a rudimentary fashion. Will P.R soon. Commenting so extra energy isn't wasted on this.

**Comment by kyb3r** [comment]
Thanks @daegontaven
