### ISSUE TITLE
Inconsistency with commands structure

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#165]
So the intention with who can use the mod mail commands to interact with the bot are supposed to be for those who only have manage delete however theres inconsistency with that.

My trial moderators dont have manage message permission to prevent rouge actions but for some reason they do have the ability to use
?reply
?close
?snippets add

I would like to suggest a more clear defined permissions on who can use the command based on Usergroup Roles rather than who has access manage message permission.

**Comment by kyb3r** [comment]
Looks like the `snippets add` problem is a bug where anyone has access to use subcommands.
