### ISSUE TITLE
Bot Status

### ISSUE THREAD

**Issue by fl0wart** [kyb3r/modmail#167]
I suggest the addition of the ability to add bot status (do not disturb, away, online, invisible).

**Comment by Taaku18** [comment]
How would this work exactly? Is the status set explicitly through a command like `?status idle` and such? And does the bot reject messages if it’s set to do not disturb or invisible?

**Comment by fl0wart** [comment]
Like ?status dnd (do not disturb) and it set to it,but still show play status
