### ISSUE TITLE
Close thread anonymously

### ISSUE THREAD

**Issue by Forcellrus** [kyb3r/modmail#169]
Right now, anonymous responses (which I mainly use) don't make too much sense because responder's identity is revealed as soon as they close the thread, so why not have something like !anonclose?

**Comment by kyb3r** [comment]
The close command accepts an optional argument, which is the close message, so you can do something like `close The issue has been resolved`, you can create your own `anonclose` command through the use of aliases. 

- `alias add anonclose close <your custom message>`

**Comment by Forcellrus** [comment]
I guess it works that way as well.
