### ISSUE TITLE
Mod_color variable is broken

### ISSUE THREAD

**Issue by Forcellrus** [kyb3r/modmail#170]
It doesn't work at all, recipient_color on the other hand works as intended. Furthermore, in "[p]config set" list, "mod_color" and "anon_username" appear as one variable, called "mod_coloranon_username", which makes me suspect that "anon_username" variable doesn't work either.

**Comment by kyb3r** [comment]
Yep, this seems to be a typo on our end, It is fixed in v2.13.3
