### ISSUE TITLE
Adding snippet variables

### ISSUE THREAD

**Issue by Forcellrus** [kyb3r/modmail#171]
Right now, we are stuck with plain markdown text to be set as snippet text. How about we get some variables we can put in text, such as `<user>`, `<mention>`, `<date>`, `<time>` etc.
An example:
"Hello, `<mention>`. Thank you for contacting us..."

**Comment by kyb3r** [comment]
Good idea

**Comment by fourjr** [comment]
This could be implemented similar to welcomer

**Comment by kyb3r** [comment]
What snippet variables would you like?

**Comment by kyb3r** [comment]
Currently, I'm going to put in `{recipient}` in which you can access different attributes like: `{recipient.name} {recipient.mention} {recipient.id} {recipient.avatar_url}` etc.

**Comment by fourjr** [comment]
Already implemented
