### ISSUE TITLE
Add a "raw" log of a thread

### ISSUE THREAD

**Issue by aequasi** [kyb3r/modmail#174]
Hi there! Could you please add a "raw" log for threads (something like https://logs.modmail.tk/02032d65a6f3/raw)

**Comment by Taaku18** [comment]
The "raw" feature for logs does exist. There is a bug preventing it from rendering in logs.modmail.tk, but it should work for self-hosted logviewers. For example, the raw version of the logs you linked can be viewed here: https://modmail-logs.herokuapp.com/logs/raw/02032d65a6f3.

**Comment by Taaku18** [comment]
Since Modmail API is going to be removed soon, I tagged this with `wontfix`. But if anyone wants to fix this issue, by all means, remove the tag.
