### ISSUE TITLE
Image Wont Show

### ISSUE THREAD

**Issue by lemonvamps** [kyb3r/modmail#177]
whenever i embed an image and try to send it with reply, it doesnt show. how can i fix that? (it has all permissions it should have+admin permissions enabled)
<img width="717" alt="screen shot 2019-02-12 at 5 28 18 pm" src="https://user-images.githubusercontent.com/43923548/52672387-b9265480-2eeb-11e9-9824-06a0d9222d34.png">

**Comment by kyb3r** [comment]
This seems to be a bug with discord for not showing the image in the embed.
