### ISSUE TITLE
How does the README buttons work?

### ISSUE THREAD

**Issue by TheBitLlama** [kyb3r/modmail#184]
How did you made those cool buttons? I really like 'em!

**Comment by fourjr** [comment]
What buttons are you referring to?

**Comment by TheBitLlama** [comment]
The buttons, that are under the MODMAIL logo

**Comment by fourjr** [comment]
Check out [shields.io](https://shields.io/)

Everything we do on this repository is open-sourced as well. You can check the source directly.

**Comment by TheBitLlama** [comment]
Thanks! And that header? How did you made, that it's right in the center?

**Comment by fourjr** [comment]
Check the source code yourself

**Comment by TheBitLlama** [comment]
Alright, I got answer to almost anything, with a single CTRL+SHIFT+I, but I can't figure out from the HTML, that how did you make those hyperlink images(buttons). I got an image, that's ok, but I can't add a link, and I can't figure it out from the source code.

**Comment by fourjr** [comment]
https://github.com/kyb3r/modmail/blob/master/README.md Press `raw` at the top right

**Comment by fourjr** [comment]
This isn't a html/markdown support place so please stop using this issue thread as one.
