### ISSUE TITLE
Owner command to restart the bot

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#190]
Would be nice for owners only to restart the bot via command executed from discord server so we dont have to do it manually in heroku website.

**Comment by fourjr** [comment]
Why would you need to restart the bot?

**Comment by maidos** [comment]
latency issues, partial bot crash or issues cause by outside influence, eval commands, diagnostic purposes especially when you communicate with mod mail support and they advice you to restart the bot.

**Comment by fourjr** [comment]
Restarting bot isn't possible in the bot itself. You'd have to go to the heroku dashboard.

**Comment by maidos** [comment]
wouldnt  `?eval await bot.logout() `force the bot to eventually restart by herokuÅ?

**Comment by fourjr** [comment]
It's not guaranteed. The bot *might* log out and never restart

**Comment by maidos** [comment]
wouldnt it be possible to use heroku webhooks to use cli commands and then use heroku ps and execute the command heroku ps:restart

**Comment by fourjr** [comment]
that'll require a heroku token, more trouble than necessary

**Comment by Taaku18** [comment]
Using `?eval await bot.logout()` is pretty much reliable, but the time the bot is down grows exponentially reaching a maximum of 320 mins, however the growth resets everyday. 

https://devcenter.heroku.com/articles/dynos#dyno-crash-restart-policy

**Comment by fourjr** [comment]
I would not want a command that isn't 100% working.

**Comment by officialpiyush** [comment]
Yo, until i add the reboot command to the bot, I've made a reboot plugin, which can be installed by `plugins add officialpiyush/modmail-plugins/reboot` . It just takes < 3 seconds to reboot
