### ISSUE TITLE
Add SLA times.

### ISSUE THREAD

**Issue by Adicogames** [kyb3r/modmail#192]
It would be very helpful to have SLA times for the bot to track on each mod mail, for example:

- 1 hour to reply to a new message.
- 2 hours after each reply to check on it.

So, if a new message comes in the admins/mods have 1 hour to reply, otherwise the bot will ping a role, for example mods. And if 2 hours have past since the last message it will ping the last mod to reply to the message.

And the times could be variable to allow for different SLA, as well as the role to be ping and so on.

**Comment by fourjr** [comment]
What does SLA stand for?

**Comment by Adicogames** [comment]
> What does SLA stand for?

Service-Level Agreement. it encompases a lot of things, one of them is "response time" meaning how much time there should be between entry of something (like an ticket) and the response from a service desk employee.

In this context it would be the time between the entry of a modmail message and the response from the admins/mods.

**Comment by StephenDaDev** [comment]
Maybe could add multiple additional pings to it could also work as an "escalation" system if at first the Helpers/Mods don't take it, it gets escalated to the Admins, and then the Owner.

**Comment by StephenDaDev** [comment]
**Additional Request from Users:** Send a message when the additional ping happens for example after 1 hour ping a role and then send a message like ``Sorry for the inconvenience. All of our support members are unavailable at the moment, please wait and you will be helped shortly.``
