### ISSUE TITLE
OAuth Login for Logs

### ISSUE THREAD

**Issue by daegontaven** [kyb3r/modmail#199]
## Problem
We keep our logs channel's message history private to ensure that newer modertors don't have access to the older logs. However, older moderators gone rogue unbenownst to us may diligently take down the links to the logs and share secret material with newer moderators.

## Solution
Make it so that older logs require discord OAuth from approved roles/owners to view internal messages.

### Developer Notes:
I'm a python developer, so I'll add the ability myself if and when I can. In the meanwhile if any one wants to adop this issue, feel free to do so! I assume this change needs a memcache like redis. However, it may be a hinderance since AFAIK redis is huge and the memory limit for a dyno on heroku is 512M. We might be able to get away with simply storing the cache simply into a variable. Questions welcome ^_^ !

**Comment by fourjr** [comment]
This will be interesting to implement. Would require a new key in MongoDB of allowed users.

**Comment by officialpiyush** [comment]
Agreed

**Comment by kyb3r** [comment]
Added this in 2.20.0

**Comment by kyb3r** [comment]
I used an in-memory session interface for persistence, unfortunately, this would make you have to log in every time on Heroku since the app would sleep. This wouldn't be a problem if you hosted it on a VPS though.
