### ISSUE TITLE
Black text on gray background in logs on Edge 

### ISSUE THREAD

**Issue by sylveon** [kyb3r/modmail#204]
![image](https://user-images.githubusercontent.com/6440374/54885178-e43b8680-4e4f-11e9-9496-6a3c18535784.png)

This occurs because the logs use a Chrome extension not supported by Edge, 8 digit hex colors:
![image](https://user-images.githubusercontent.com/6440374/54885192-0208eb80-4e50-11e9-92db-e576b6c73bc9.png)

This style should be changed to `rgba(255, 255, 255, 0.6)` to work on all browsers

**Comment by kyb3r** [comment]
Can u make a pull request [here](https://github.com/kyb3r/logviewer)

**Comment by sylveon** [comment]
Opened one.
