### ISSUE TITLE
Idea: Config item for Text to show when the thread starts.

### ISSUE THREAD

**Issue by TobiTenno** [kyb3r/modmail#206]
The bot already shows the general information for the user, which is fantastic.

Another bit that would likewise be great is a configurable message for things like reminding mods of commands and the server's policies in dealing with users.

**Comment by kyb3r** [comment]
This seems like a niche feature, however, it can be achieved by editing the `mention` config var to include some extra text.

**Comment by TobiTenno** [comment]
But that won't show in an embed, uniform like the rest.
