### ISSUE TITLE
Allow editing of thread close response as well

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#208]
In the new update we can now customise the embeds of thread creation and thread close, but there is no ability to edit the "closed this modmail thread" response. Would be nice if we can edit that as well. Maybe two config vars need to be there, one for a staff member closing the thread and one for the user closing the thread with the emoji as the responses are different for both.

**Comment by kyb3r** [comment]
Ok, so `thread_close_response' and `thread_self_close_response`

They will be provided by two variables that you can incorporate into them:

- `closer` - the user object that closed the thread.
- `logkey` - the key for the thread logs e.g. (`5219ccc82ad4`)
- `loglink` - the full link to the thread logs e.g. (`https://logwebsite.com/logs/5219ccc82ad4`)

Example usage would be: ``?config set thread_close_message {closer.mention} closed the thread, here is the link to your logs: [`{logkey}`]({loglink})``

**Comment by kyb3r** [comment]
Added this in da306f9b8e2fda5e2d1373e731c270980beb620b
