### ISSUE TITLE
Ability to delete certain logs via the bot itself

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#210]
Suppose you don’t want to keep unnecessary past threads in the database such as test threads and it increases that person’s past thread count. Currently if we want to delete a log from the database we have to log into MongoDB atlas, go to Collections, find it in a long list of logs and delete it. So it would be great if there is a command such as `logdelete` where you input the log URL or the log ID and it deletes it from the database. Also have different ways to use the command, such as deleting an individual item, deleting all logs for a selected user via mention or User ID and a delete everything option.

**Comment by kyb3r** [comment]
If/while this gets implemented, in the meantime, you can use the eval command to do this:

Delete all logs for a single user:
```py
result = await bot.db.logs.delete_many({'recipient.id': "325012556940836864"})
print(result.deleted_count)
```

Delete a single log entry:
```py
result = await bot.db.logs.delete_many({'key': "2edf087b654e"})
print(result.deleted_count)
```

**Comment by StephenDaDev** [comment]
@Taaku18 This has been added in [v3.3.0](https://github.com/kyb3r/modmail/blob/master/CHANGELOG.md#v330)
> - Ability to delete log entries. (Thanks to papiersnipper PR#402)

Close Requested - Thanks *I'm very sorry but I can't close these on my own otherwise I would have already*
