### ISSUE TITLE
Inactive close 

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#213]
Config option to automatically close with a custom close message after X minutes of inactivity.

**Comment by DAVIREPYT** [comment]
the webpage to generate the MODMAIL_API_TOKEN not work me!

**Comment by Taaku18** [comment]
> the webpage to generate the MODMAIL_API_TOKEN not work me!

The modmail.tk API is no longer supported. Follow the guide in the Wiki section to set up Modmail.

**Comment by maidos** [comment]
Can you explain more about the criteria for inactivty? does the inactivity start/reset after the recipient last response?

**Comment by kyb3r** [comment]
Yes

**Comment by maidos** [comment]
is it possible for the thread to auto close if someone left the server?

**Comment by kyb3r** [comment]
Sure, but we haven't started working on this yet.
