### ISSUE TITLE
Leave Command

### ISSUE THREAD

**Issue by ShubhamShourya** [kyb3r/modmail#218]
My bot is in some of the server and i would like to get a command so that when I'll type ?leave ServerId, the bot will leave the server with that id, and this command should only be used by bot owner.
Hope this would be added.

**Comment by fourjr** [comment]
Out of scope of what Modmail should do. Why don't you just *kick* your bot out of the server? Every server you add Modmail to, you should have some sort of moderation permissions.

Anyway, here is an eval command if you wish to do this:
```python
eval guild_name = 'server name'
guild = discord.utils.get(bot.guilds, name=guild_name)
if guild:
    await guild.leave()
print('Left', guild)
```
