### ISSUE TITLE
What permissions are needed to use [prefix]close

### ISSUE THREAD

**Issue by Zacatero** [kyb3r/modmail#22]
My moderators are able to do [prefix]reply all day long, but only those with the ADMINISTRATOR permission can do [prefix]close. Is Administrator required for that?

**Comment by Zacatero** [comment]
Its been about 20 days since i opened this with no reply. Just bumping it to keep active

**Comment by Zacatero** [comment]
Bumpity Bump

**Comment by Garcia1008** [comment]
Yes

**Comment by Zacatero** [comment]
@Garcia1008 If i self-host the bot is that something i can change?

**Comment by Zacatero** [comment]
Never mind. I just edited the code and changed the required permission.
