### ISSUE TITLE
[Suggestion] Search closed-by using ID

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#222]
Currently you are only able to see who closed the ticket by using tagged username
!logs closed-by @username 
Theres some downside by having only that.
1. Tagging them can be annoying.
2. Tagging them in a test channel where they dont have access to, yield mixed result where as theres no result from the user. 
3. Using !logs search 500 USERID does not yield effective result as result only show 1/10 of the actual tickets that the user closed.

https://i.imgur.com/r75t6hL.png
https://i.imgur.com/Ek6JcUR.png

Suggestion: The actual idea is let us search by ID instead so 
!logs closed-by USERID

**Comment by Taaku18** [comment]
Searching logs close-by by ID was always possible, https://i.imgur.com/02C7AfF.png.
