### ISSUE TITLE
No Images/logs on VPS

### ISSUE THREAD

**Issue by GoogleIt1** [kyb3r/modmail#223]
I'm assuming its probably a port issue on my end but neither the Logs link or the Attachment Links are responding 
![image](https://user-images.githubusercontent.com/34065903/57202049-d4df4b00-6f6e-11e9-9c60-baffcc42b89a.png)
![image](https://user-images.githubusercontent.com/34065903/57202059-ec1e3880-6f6e-11e9-95d4-de477cd9bb83.png)
![image](https://user-images.githubusercontent.com/34065903/57202077-1243d880-6f6f-11e9-84fc-9bc816f29531.png)
![image](https://user-images.githubusercontent.com/34065903/57202087-27206c00-6f6f-11e9-86df-a04bba7834cd.png)

**Comment by GoogleIt1** [comment]
Wrong Github sorry :\

**Comment by mohaisrealrblx** [comment]
> Wrong Github sorry :\

Hey! i'm having the same bug. Can you tell me how did you fix it, please?
