### ISSUE TITLE
Clickable emoji or command to start a new thread

### ISSUE THREAD

**Issue by matrix2113** [kyb3r/modmail#224]
Emoji / Command to start a Modmail DM thread. (Available as a plugin now)

**Comment by officialpiyush** [comment]
Seems like i have to fix it and PR soon

**Comment by immortality223yt** [comment]
Isnt this for the `embed` plugin already?

**Comment by immortality223yt** [comment]
https://discordapp.com/channels/515071617815019520/543040188541042699/585491519046287365
http://prntscr.com/nyjoc9

I guess kyb3r wants it in the core cogs?

**Comment by StephenDaDev** [comment]
Status = Iffy - Plugin was made but never committed to core.

**Comment by officialpiyush** [comment]
;p. The plugins just send a non-customizable "Hello how can we help you" message to the user. I guess I shall update the plugin to open a thread on reaction.

**Comment by DAzVise** [comment]
this should be a core feature not a plugin

**Comment by officialpiyush** [comment]
idc

**Comment by Akhil2149** [comment]
I guess this should be a core feature.

**Comment by officialpiyush** [comment]
Yo, it's done. So the bot creates a new thread whenever a user reacts :)

https://github.com/officialpiyush/modmail-plugins/commit/86b1a08de9b62154d9616831a8bd9e0647ebcbd3
