### ISSUE TITLE
DM Does not arrive

### ISSUE THREAD

**Issue by Reverion** [kyb3r/modmail#23]
I have set the thing up, its hosted and all. There is an extra catagory named "modmail" and when I dm the bot I also get the reaction.
My DM however does not add another channel/thread, so me as moderator couldnt see anything. Anyone know why?

**Comment by gamingbro** [comment]
Have you tried doing [prefix]setup yet?

**Comment by Zacatero** [comment]
You have to make sure that the bot can create channels. Make sure the bot has that role permission
