### ISSUE TITLE
Support teams natively

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#230]
Waiting on https://github.com/discordapp/discord-api-docs/issues/787

**Comment by Agent-Fennec** [comment]
Possibly Support levels to move to support tickets to a different category for someone more qualified to work on.

**Comment by StephenDaDev** [comment]
This can be done by using different categories for example if you have Tier 1 Support and Tier 2 Support you can use ``?move Tier 2`` or make an alias and permissions restrict tier 2 from tier 1 @Agent-Fennec

**Comment by Taaku18** [comment]
Update: waiting on discord.py v1.3.0 release.

**Comment by StephenDaDev** [comment]
Ok!
