### ISSUE TITLE
Global Subscribe Command

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#246]
Run the ``Global Subscribe Command`` and have it ping you for every new message in every thread. 

#### Suggestion by Discord User kederan#7328

**Comment by kyb3r** [comment]
It could be implemented in the form: `?sub all`

**Comment by StephenDaDev** [comment]
Could this potentially cause an issue if they were trying to subscribe a user ``all`` or if they have a role ``all`` and are trying to subscribe it to a thread?

**Comment by kyb3r** [comment]
yes, you would have to use the name#discrim or ID in that case

**Comment by StephenDaDev** [comment]
Also, would probably be useful to do with the notify command

**Comment by StephenDaDev** [comment]
You are stale.
