### ISSUE TITLE
modmail bot not creating new channels

### ISSUE THREAD

**Issue by gamingbro** [kyb3r/modmail#25]
I setup a modmail bot and had the mod mail category and modmail channels all setup and the bot was working. But I figured out that the bot's name wasn't right so I decided to create a new (second) modmail bot with the right name, but when I set it up in the server, it said that this server was already setup, so, I kicked the other old/wrong bot and deleted the channels and categories, and tried again with yet another (third) bot. I set it up in the server, and it created the modmail category and the bot-info channel, but when I DM'd it to test it out, it doesn't respond back with the "thanks for the message!" response. And it also doesn't create any new channel threads. So I was wondering if anyone knows how to fix this. Thanks!

**Comment by clashwithA** [comment]
I had the same issue

**Comment by fourjr** [comment]
chheck permissions

**Comment by Venatus777** [comment]
@fourjr I have the exact same issue, accept I gave the role the bot created admin permissions, and made the role the highest role. And it is still not creating the channel. Yet it reacts to my message, what could be the issue?

**Comment by Venatus777** [comment]
it reacts with the white check mark emoji

**Comment by fourjr** [comment]
can you show me the heroku [logs](https://cdn.discordapp.com/attachments/345787780653252610/361386424710201344/Screen_Shot_2017-09-24_at_3.40.22_pm.png)

**Comment by fourjr** [comment]
don't need to ping... 2 possibilities:
- You didn't put `GUILD_ID` in your config variables
- The guild ID is wrong

**Comment by Venatus777** [comment]
I have developer mode on, I right clicked the server tab in top left and clicked copy id
put the ID it gave me into the ID section, Dont see what I did wrong but I'm sure its something :(

**Comment by fourjr** [comment]
What server tab...? can you give a screenshot?

**Comment by Venatus777** [comment]
<img width="289" alt="_bot-info_-_discord" src="https://user-images.githubusercontent.com/36063147/43265897-a8fda250-90af-11e8-8541-dd54b07e1ec8.png">

**Comment by Venatus777** [comment]
that, the dropdown bar where it says the server name

**Comment by kyb3r** [comment]
fixed
