### ISSUE TITLE
Automatic Changing Activity

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#251]
Be able to set an activity that changes every few seconds.
Also apparently known as a "rotating status"

#### Suggestion by Discord User Fighter for Justice#0825

**Comment by fourjr** [comment]
This should be more of a plugin.

However, below should be noted when developing such a feature:
- Minimum time should be once an hour. 
- Max should be about 20 hours, dyno restart?

**Comment by StephenDaDev** [comment]
For plugin suggestions, it is recommended to suggest in our plugins server in the #suggestions channel.
Join [here discord.gg/4JE4XSW](https://discord.gg/4JE4XSW)
