### ISSUE TITLE
Ability to wipe messages from Database

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#252]
An ability to delete messages sent by the recipient, for example when someone sends their external IP address or Home Address and it needs to be deleted

**Comment by Taaku18** [comment]
Right now, `?delete` is accessible by an average supporter, to delete a mod message from the DM channel of the recipient (messages in the database remains undeleted). There is currently no way of deleting a message permanently from the logs without editing the database directly. I suggest implementing this as another command, for example, `?wipe <msg-id>`, with permission level set to moderator, which can delete any message from both the channels and the database.

**Comment by kyb3r** [comment]
database related commands might be under `db` so maybe `?db wipe <msg-id>`

**Comment by StephenDaDev** [comment]
Maybe have it log in the logs "This message was wiped by [user]" also maybe be able to add a reason for example "?db wipe 570814268296134657 House Address" and it would show up as ``This message was wiped by [user] for House Address"

**Comment by matrix2113** [comment]
[here](http://prntscr.com/ob6m68)

Taki had an eval command that did the trick.

**Comment by StephenDaDev** [comment]
This is a different issue, this is regarding one message instead of a thread. This does go with the ``db`` command though

**Comment by officialpiyush** [comment]
Is'Nt ThIs ImPlEmEnTeD

**Comment by StephenDaDev** [comment]
No. As the suggestion says ``delete messages`` and is to delete single messages, instead of a whole thread.

**Comment by officialpiyush** [comment]
Ah yes, had misread it. lol

**Comment by StephenDaDev** [comment]
This issue is approved and holds significant value.
