### ISSUE TITLE
Deleted Message Indicator in Logs

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#253]
Once a log is closed if a message was deleted (not wiped) it would have a symbol to indicate it was deleted, maybe if hovered over, it would show who deleted it.

**Comment by StephenDaDev** [comment]
What I'm thinking ![alt text](https://i.imgur.com/a7iO3qV.png "Concept Image")

**Comment by officialpiyush** [comment]
UwU

**Comment by kyb3r** [comment]
I was thinking something like this instead: 

<img src='https://user-images.githubusercontent.com/29310830/58404765-3d6ea300-80a9-11e9-83da-dfa0c78d2d52.png' width=600>

**Comment by StephenDaDev** [comment]
Thats better

**Comment by Forcellrus** [comment]
> I was thinking something like this instead:
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/29310830/58404765-3d6ea300-80a9-11e9-83da-dfa0c78d2d52.png">

Maybe color the "(deleted)" text red, so more distinguishable from "(edited)"?

**Comment by StephenDaDev** [comment]
Hi There! Thanks for reaching out to suggest something for Modmail, we love hearing your suggestions as it helps us shape the bot to what our users want it to be. However this is a logviewer related suggestion, therefore it belongs on the repo [kyb3r/logviewer](https://www.github.com/kyb3r/logviewer).
