### ISSUE TITLE
[request] Allow snippets to be configured to send anonymously

### ISSUE THREAD

**Issue by orangespire** [kyb3r/modmail#254]
Currently when snippets are used they are not anonymous.  It would be nice to have an option to configure snippets to send anonymously.

**Comment by StephenDaDev** [comment]
Until (if) this is added you can do this by using aliases
``?alias add anonreply [snippetname] [snippetcontnet]``

**Comment by fourjr** [comment]
This is not worth the extra work as it is easily done using aliases.
