### ISSUE TITLE
Pin messages for recipient

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#256]
Have a command that will pin the message for the other user, So if someone uses a command such as ``?pin [message id]`` it will pin the message in the DM, Original Request, said for the recipient to be able to pin for support, but would most likely not work as you can't use commands as the recipient. 

#### Suggestion by Discord User 3dlic#0613

Also, should probably remove all pinned messages in the DM once the thread is closed

**Comment by kyb3r** [comment]
I kinda feel like this is unnecessary, can you tell me how this might be useful?

**Comment by StephenDaDev** [comment]
Honestly, I think it would be too, I am just creating it because someone suggested it to me and thought maybe some people could benefit from it

**Comment by StephenDaDev** [comment]
No Purpose
