### ISSUE TITLE
Suggestions - Server Info and Globalbans

### ISSUE THREAD

**Issue by Emivg** [kyb3r/modmail#259]
Hello, first of all thank you for keep this amazing bot up-dated, I have 2 suggestions for it:

1- I have my bot in several servers, when someones creates a new ticket it could be usefoul if the bot shows in the start message the servers the user share with the bot

2- Add (in the moderation plugin) the Globalban command, so the bot will ban the user from every server the bot is in

Regards!

**Comment by kyb3r** [comment]
1. I can do this.

2. The moderation plugin is developed by a third party (@officialpiyush), you might want to create an issue on his plugin repository 👍

**Comment by officialpiyush** [comment]
Hello!

**Comment by officialpiyush** [comment]
https://github.com/kyb3r/modmail/commit/8fa7b39e7d9cd84ff35259df03098e1428f39730 UwU 1st one is getting implemented soon™
