### ISSUE TITLE
Status dissapears after few hours

### ISSUE THREAD

**Issue by Reverion** [kyb3r/modmail#26]
Anytime i do [p]customstatus [status] it sets it for a few hours, but after like 5/6 hours it resets and you have to do it again.
Is this a common issue?

**Comment by fourjr** [comment]
This happens if you are using heroku. Might make a way for it to stay in the future

**Comment by fourjr** [comment]
EDIT: You can set a `STATUS` environment variable for this

**Comment by Reverion** [comment]
I tried the STATUS variable, but it doesnt show anything in discord, [Maybe Im just dumb, but here is the screenshot](https://imgur.com/a/JZdN6)

**Comment by fourjr** [comment]
Have you updated to the latest version? If so, drop me a DM on discord. `4JR#4895`
