### ISSUE TITLE
Add something like "business hours"

### ISSUE THREAD

**Issue by EGGamer** [kyb3r/modmail#261]
Let me explain the title a bit. In my community, most of the admins and moderators, aren't active at night, but we have users that are online, and could use the bot at night, but they wouldn't be responded until the morning when someone of the staff wakes up. So it would be great to automate the bot to do something like: At X hour you set your status to "Idle" and set the activity to: watching "your messages tomorrow.", and maybe if someone opens a thread the embed that appears could say something like "A response may take time to arrive". And at Y hour it sets everything to what it was before.

**Comment by MiTonder** [comment]
That could be pretty nice

**Comment by kyb3r** [comment]
This is also a niche request, which could be implemented in a plugin.

**Comment by officialpiyush** [comment]
uwu

**Comment by StephenDaDev** [comment]
Could easily copy and paste a command. Also could add a Bussiness hours thing to your ``thread_creation_response`` 
If you need help with any of this DM Modmail in our support server

**Comment by officialpiyush** [comment]
How actually you want to set your time

**Comment by EGGamer** [comment]
@officialpiyush The same way as the scheduled thread closing. Or maybe set an exact time like At 9pm CEST.

**Comment by StephenDaDev** [comment]
If you are scheduling it in the same way as a scheduled close it needs to be rescheduled every night, making it still manual. A set time would probably make more sense for the guilds that want to use this.

**Comment by Taaku18** [comment]
`?disable` and `?enable` (see changelog) have been implemented in the latest update (3.3.0), you can use that to toggle DM for Modmail. As for "business hours", you can disable every night then reenable in the mornings. Automation will likely not be implemented.
