### ISSUE TITLE
How to configure GITHUB_ACCESS_TOKEN and issue in update

### ISSUE THREAD

**Issue by Weirdo914** [kyb3r/modmail#263]
How to add my github access token to the bot

**Comment by Weirdo914** [comment]
What scopes do i have to add in my token

**Comment by papiersnipper** [comment]
Go to the settings tab of your bot's dashboard in Heroku. Add the token like so
![afbeelding](https://user-images.githubusercontent.com/42642013/58500696-f3f28680-8182-11e9-8136-79c562744bd2.png)

You only need to add the repo permissions to your token.

**Comment by Weirdo914** [comment]
All repo permissions?
![github](https://user-images.githubusercontent.com/44896455/58501368-e0a2e380-81a1-11e9-9cfa-5b5b55582a54.png)

**Comment by papiersnipper** [comment]
Yes, only the repo access

**Comment by Weirdo914** [comment]
Ok thanks

**Comment by Weirdo914** [comment]
After that 
![Uploading Screenshot_18.png…]()
i type update but nothing happens it shows bot is typing and then nothing happens

**Comment by kyb3r** [comment]
follow this gist https://gist.github.com/kyb3r/de3003dedd3260ffd062375140d7563d
