### ISSUE TITLE
[Suggestion] Add the ability to Edit snippets and alias

### ISSUE THREAD

**Issue by MiTonder** [kyb3r/modmail#264]
I just have the fresling that it would be great, especially for snippets. I just made a snippet in the support server about dyno hours, and instead of just having a command called `?snippets edit` i need to remove it and add it back again, and the same With alias

**Comment by StephenDaDev** [comment]
Good feature. I feel this would be very helpful at the beginning of your modmail deployment. (or for people like myself who can't type)

**Comment by StephenDaDev** [comment]
👏
