### ISSUE TITLE
[Suggestion] Archive

### ISSUE THREAD

**Issue by SodaxoPastel** [kyb3r/modmail#265]
Do ?archive, and it moves the thread to a certain category and closes the thread, but the thread can still be seen by mods for training purposes or whatever.

**Comment by kyb3r** [comment]
Actually a good idea

**Comment by Doc94** [comment]
i think this can be added to https://github.com/kyb3r/logviewer
like root page (actually show running text) show archived or past items.

**Comment by kyb3r** [comment]
Like an interface to browse logs on the site?

**Comment by Doc94** [comment]
> Like an interface to browse logs on the site?

Yes, i think this sound better than Archive, and the feature can be "top/fav" ticket in website.

**Comment by StephenDaDev** [comment]
I have gotten countless requests to have a way to select logs on the site, and it could be quite useful. Could be able to pin threads, or search like you can with the ``?logs`` command
