### ISSUE TITLE
Starboard command!

### ISSUE THREAD

**Issue by allipsee** [kyb3r/modmail#267]
I think you should make starboard in modmail like R.Danny's

**Comment by MiTonder** [comment]
Piyush already made a plugin, idk if it works but here it is https://github.com/officialpiyush/modmail-plugins/tree/master/starboard

**Comment by allipsee** [comment]
I dont think it works

**Comment by MiTonder** [comment]
I Will ask Piyush

**Comment by officialpiyush** [comment]
The plugins in the registry are the only which work rn, I'll fix starboard today, it got logical errors

**Comment by officialpiyush** [comment]
O didn't read the whole thing, ig you can make it too
