### ISSUE TITLE
Unexpected "This time is in the past."

### ISSUE THREAD

**Issue by robinmahieu** [kyb3r/modmail#269]
When trying to close a thread in x amount of hours, this error pops up **sometimes**.

![Image](https://i.imgur.com/JL2gMLL.png)

**Comment by StephenDaDev** [comment]
I have tested with one thread, I was able to get it to work when using no space and ``h`` instead of ``hour`` all others gave this error.

```?close in 1 hours This thread has been closed due to inactivity, please contact us again if you have any issues/queries.``` **Error Presented**

```?close 1hour This thread has been closed due to inactivity, please contact us again if you have any issues/queries.``` **Error Presented**

```?close 1h This thread has been closed due to inactivity, please contact us again if you have any issues/queries.``` **Worked as expected**

*I am still testing various things to see what causes this error and what does not*

**Comment by StephenDaDev** [comment]
Adding to my previous testing, the "day" timeframe seems to work fine.

```?close 1 day`` **Worked as expected**
```?close 1 days`` **Worked as expected**
```?close 1d`` **Worked as expected**

and With minutes:

```?close 1 minute`` **Worked as expected**
```?close 1 minutes`` **Worked as expected**
```?close 1m`` **Worked as expected**

It appears it is currently only the "hour" that is messed up.

**Comment by kyb3r** [comment]
It might be due to the message afterwards that's causing the error

**Comment by StephenDaDev** [comment]
Any updates on this?

**Comment by Weirdllamas** [comment]
I ran a few tests, the issue appears to be with self.dt. (Line 105 of time.py is a good jumping off point)

The times looked like this for ?close 1h (correct):
now: 2019-08-23 18:43:52.624895 
self.dt: 2019-08-23 19:43:52.624895

While for ?close in 1 hours (incorrect):
now: 2019-08-23 18:43:28.221410
self.dt: 2019-08-23 18:43:28

**Comment by Weirdllamas** [comment]
Ran some more tests, i think the ShortTime.compile regex is causing the issue

**Comment by Weirdllamas** [comment]
But yeah, it appears to be the message afterwards

**Comment by officialpiyush** [comment]
Option 3: Shift to dateparser ;p
