### ISSUE TITLE
Edit and Delete message only for sender of the message

### ISSUE THREAD

**Issue by AhmedXL** [kyb3r/modmail#272]
?edit messageID
?delete MessageID
**only works on messages that the one who triggered the command is the author**
even with ?anonreply
**only apply to edit or delete if the one who did send it is the same as the one who triggered the command**

**Comment by StephenDaDev** [comment]
This would most likely be hard to implement, due to the fact if you delete a message using the Discord message delete system, it will delete the message. Also, what if you need to remove a message and the person is offline?

**Comment by AhmedXL** [comment]
> This would most likely be hard to implement, due to the fact if you delete a message using the Discord message delete system, it will delete the message. Also, what if you need to remove a message and the person is offline?

current position that bot removes or edit any message whoever sent it by using the command
all i am asking is locking these commands to only works with the one who did send them
if the one who did send the message and you want to delete it, just make the mod say what he gonna say in another message... i feel like that will make sense, that it.

**Comment by kyb3r** [comment]
@StephenDaDev not hard at all to implement actually, it just needs an additional line of code.

**Comment by kyb3r** [comment]
haha jk
