### ISSUE TITLE
Suggestion: Command that will allow to close 2 or more threads at once

### ISSUE THREAD

**Issue by allipsee** [kyb3r/modmail#275]
Make a multi thread command so you can close for example 2 threads or more using 1 command.

**Comment by StephenDaDev** [comment]
Use cases? I feel like the rarity for wanting to do this would make copy and pasting ``?close`` "easier" than having a whole command developed for it

**Comment by StephenDaDev** [comment]
[![](https://api.gh-polls.com/poll/01DDNZPFS7BXKHSHKWCDCREDVA/Yes%2C%20Add%20it%20in!)](https://api.gh-polls.com/poll/01DDNZPFS7BXKHSHKWCDCREDVA/Yes%2C%20Add%20it%20in!/vote)
[![](https://api.gh-polls.com/poll/01DDNZPFS7BXKHSHKWCDCREDVA/Nah%2C%20This%20ain't%20nessicary)](https://api.gh-polls.com/poll/01DDNZPFS7BXKHSHKWCDCREDVA/Nah%2C%20This%20ain't%20nessicary/vote)

**Comment by StephenDaDev** [comment]
@Taaku18 Majority Rules I guess.

**Comment by Taaku18** [comment]
Polls are a mean of determining demands, although majority voted “no”, there’re still 26% of people who wants this feature. 

However, how does this actually work? 

Ability to close all threads? (`?close all`)
Ability to close multiple specified threads? (Too trivial)
