### ISSUE TITLE
Suggestion: Ability to change the icon/avatar in the footer on each type of thread.

### ISSUE THREAD

**Issue by nahgola** [kyb3r/modmail#2750]
![](https://i.gyazo.com/6bd23ce0276a3badd7efb22f13a5f4ce.png)

**Comment by Taaku18** [comment]
Do you mind expanding on what you meant by "each type of thread"? Do you just want to have the footer icon customizable via a config var?

**Comment by nahgola** [comment]
> Do you mind expanding on what you meant by "each type of thread"? Do you just want to have the footer icon customizable via a config var?

Well with anon replies for example, there's no icon for the footer. And the default footer icon for other thread footers is the server icon. So either a way to set a custom icon for all footers, for each individual thread footer, or the ability to do either.
