### ISSUE TITLE
Specify roles not allowed to contact Modmail

### ISSUE THREAD

**Issue by Jees1** [kyb3r/modmail#2753]
**Is your feature request related to a problem? Please describe.**
I don’t like how unverified people contact modmail to lie about a ingame thing, we use a bot to verify users in with roblox. Sometimes, they contact our modmail to get a rank that they bought. They can say a username of anykind and it may not be theirs. We then can’t ban them ingame since we don’t have proof of them owning that account, ee can only ban them in Discord.

**Describe the solution you'd like**
I would like a feature to block users with a certain role to contact modmail.

**Describe alternatives you've considered**
I can’t think of anything.

**Who will this benefit**
This feature would benefit people with a verification bot that is connected to games.

**Additional context**
You could make it a config the message that gets sent to the user with the specific role.

**Comment by Taaku18** [comment]
We currently only have `?block` which can block a user for certain or indefinite time. Adding role support can be part of a future update. Thanks for suggesting.

**Comment by Jees1** [comment]
@Taaku18 Adding to that, there should be a possibility to make members not in the server for some time contact modmail. For example: Someone joins and I’ve set the minimum time to 1 hour, they dm modmail and they can’t cuz they’ve been there only for like 24 mins (this might not make any sense)

**Comment by StephenDaDev** [comment]
Thats already a thing a @Jees1! Check out ``?config help guild_age``

**Comment by Taaku18** [comment]
@Jees1 Im understanding your question as that you set guild_age to 1 hour, but you want to allow certain users who joined the server less than 1 hour to be able to contact Modmail. In that case, we have the option to “whitelist” the user:

    ?blocked whitelist @user

Don’t forget to unwhitelist (the same command) later.

**Comment by fourjr** [comment]
Added to v3.6.2-dev3 which is still in development. Will be ready for public release soon.
