### ISSUE TITLE
Support queue

### ISSUE THREAD

**Issue by AlertShamrock** [kyb3r/modmail#2754]
We need a queue to prevent more than personal to take a thread. A command to abilities to request for help, but when you request for help you need to put a role, or rank (Like departments, or supporters, moderators), for ranks like supporters, moderators, administrators, and owners, will have the power to help too. Help requests will show in the queue. 

**Still confused?**

What will happen if a new thread is made?
No one can see the channel until they claim it, or get access by help request. (Apart from people with access to the channel. Like administrators)

What will you see in the queue?
New threads say "New thread. Reason: (First message they sent)"
Claim threads say "@claimer claimed this thread!"
Help request say "@user request help minimum role: (Supporters, Moderators, Administrators or Owners). Reason:  <@user reason here>"

How to do you claim a new thread?
By a reaction, (custom reaction by configuration commands but the default is a checkmark).

What happens when you request help?
It creates an embed like a new threat embed. But saying "@user request help minimum role: (Supporters, Moderators, Administrators or Owners) Reason: <@user reason here>" 

When someone claims the thread? 
The reaction will be removed, they gain access to the channel, and send a message that @user claim their thread/ticket!!

Why is this important?
To stop threads fights, between support personals, and make everything more organized!! 
Free feel to add more with this feature! 

Sorry, if I am confusing. I am horrible at explaining!!

**Comment by StephenDaDev** [comment]
In this thread does personal = personnel? It also seems very similar to #407 (Support Assignment) as they both reference a supporter claiming a thread.

**Comment by Taaku18** [comment]
This feature request completely changes the workflow of Modmail, it will not be worked on unless with extensive requests from users.

**Comment by StephenDaDev** [comment]
[![](https://api.gh-polls.com/poll/01DZ85YP7Y2NAXT088RH43KNPQ/Yes%20add!)](https://api.gh-polls.com/poll/01DZ85YP7Y2NAXT088RH43KNPQ/Yes%20add!/vote)
[![](https://api.gh-polls.com/poll/01DZ85YP7Y2NAXT088RH43KNPQ/No!%20Don't%20change)](https://api.gh-polls.com/poll/01DZ85YP7Y2NAXT088RH43KNPQ/No!%20Don't%20change/vote)

**Comment by wc3717** [comment]
I like this idea.

**Comment by Anonymyous678** [comment]
Yes its seem to be good idea. Please add it.

**Comment by northeastprince** [comment]
Agreed would love this feature.

**Comment by dirtyformal** [comment]
Would also love this feature.

**Comment by JOX3944** [comment]
Please add this!

**Comment by wolfier74** [comment]
Yes please add this

**Comment by fourjr** [comment]
Hey, this can be now done with a plugin and will be categorised as out of scope.
