### ISSUE TITLE
Prevent guild perms from overriding bot perms

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#2755]
**Is your feature request related to a problem? Please describe.**
Yes, I help with and know 2-3 other servers who operate their modmails with a "License" system due to past abuse of the system. Due to this we (being the servers who do this) don't want people with a certain guild perm being able to respond to a thread as they don't have a license. But since they have a Management Position their guild perms override what we have manually set with the ``?permissions add`` command.

**Describe the solution you'd like**
An ability to stop Guild role perms from overriding ?perms perms (dang that's a lot of "perms")

**Who will this benefit**
Servers who have a dedicated support team and support team TL or certification system who only want those allowed to respond to be able to respond.

**Additional context**
.

**Comment by Taaku18** [comment]
Only Admin perm overrides bot perms, is this an issue?

**Comment by StephenDaDev** [comment]
I'm requesting an ability to override the override on admin perms overriding bot perms :)

**Comment by StephenDaDev** [comment]
This is a higher risk due to a MASSIVE security flaw (@Taaku18 check your Discord DMs) I can not share the issue here for safety reasons.
