### ISSUE TITLE
Automatically close thread when recipient leaves the server

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#2757]
**Is your feature request related to a problem? Please describe.**
When a user leaves a server with an open thread, the thread gets a message, but the thread stays open, if you have many threads open it could be a little while before you get to close it, and it has no use since the user is gone.

**Describe the solution you'd like**
A config option to automatically close a thread when the recipient has left the server.

**Who will this benefit**
People who have lots of threads and don't wish to keep useless threads open.

**Comment by officialpiyush** [comment]
~~why dont we plluuggiinniiiffyyyy it~~

**Comment by StephenDaDev** [comment]
Approved suggestion

**Comment by fourjr** [comment]
Added to v3.6.3-dev1 which is still in development. Will be ready for public release soon.
