### ISSUE TITLE
The ability to add permissions on per thread basis

### ISSUE THREAD

**Issue by YyAoMmIi** [kyb3r/modmail#2759]
**Is your feature request related to a problem? Please describe.**
Permission granted is applied to everything on bot. 
I have 2 level of staff. Main staff and nsfw staff. Main staff have permission level 3. 
I do not want nsfw staff to access modmail until regular staff give them permission to do so. 
But giving permission is giving a permanent on bot global level. 

**Describe the solution you'd like**
I would like to give permission on a per thread level. 
So when I use alias [to the short cut [task]], it will give permission on a thread level. 

**Describe alternatives you've considered**
To just allow the NSFW staff to see all issues. 

**Who will this benefit**
Does this feature apply to a great portion of users?
This will allow people to have multiple level of staff, and not allow everyone to see modmail at first. 

**Additional context**
My request in discord:
https://discordapp.com/channels/515071617815019520/529240018934431744/664329142212493323

**Comment by StephenDaDev** [comment]
Hey there! This can be done by just moving the thread using the move command, **sorta** it will restrict NSFW staff from the main issues, they then can't use the commands in that channel, but they would still be able to use some commands, *so* you could give all regular staff moderator then override commands to moderator. If you need help with this I'd be happy to help. This would accomplish most of your goal just wouldn't be as easy

**Comment by YyAoMmIi** [comment]
Problem was I didn't want the nsfw to view the other threads open.

I wanted them to view it after it as moves.

**Comment by StephenDaDev** [comment]
You simply don't give them access to the main thread category. Problem solved.

**Comment by YyAoMmIi** [comment]
That was my initial plan.
With task set to move the thread.

Modmail
NSFW issue

NSFW staff could not see modmail, and only saw nsfw issue.

However, even when thread moved from modmail to nsfw issues, where nsfw
staff could now see, they could not use any modmail commands.
Actually, by giving more access to modmail they ended seeing all threads,
modmail even the modmail Catagory that they could not initially see

**Comment by StephenDaDev** [comment]
Did you give them permissions with ``?permissions add level SUPPORTER [role]``

**Comment by YyAoMmIi** [comment]
Yup, which led to them seeing all modmail threads

**Comment by StephenDaDev** [comment]
No. someone along the line changed role and or category permissions. Thats not how the bot works. Are you in our Support Server?

**Comment by YyAoMmIi** [comment]
Yup

This is when I asked about that function

https://discordapp.com/channels/515071617815019520/529240018934431744/664329142212493323
