### ISSUE TITLE
Open thread with self command (for users not staff)

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#2762]
**Is your feature request related to a problem? Please describe.**
Me no, but others would like this option

**Describe the command you'd like**
A command than when run create a thread with the user running the command, but it works for anyone, not just staff like the contact command.

**Who will this benefit**
People who have a majority of users who are used to how ticket bots work, instead of modmail and are easily confused.

**Additional context**
Nope!

**Comment by officialpiyush** [comment]
~~use react-to-contact plugin~~ :p

**Comment by StephenDaDev** [comment]
That's not a command.

**Comment by StephenDaDev** [comment]
Would also be useful to have its be configurable (with aliases) to open in a certain category

**Comment by fourjr** [comment]
Hey, this feature will **not** be implemented due to the following issues:
- After adding this feature, there will be calls to have a config to disable this command... which is a lot more work than its worth
- There will already be a react to contact in development version 3.6.3-dev1

**Comment by StephenDaDev** [comment]
``?perms override [command] 5`` allows the command to be disabled without config var.

**Comment by fourjr** [comment]
Added to v3.6.2-dev3 which is still in development. Will be ready for public release soon.
