### ISSUE TITLE
Config Var to stop reactions from being forwarded

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#2763]
**Is your feature request related to a problem? Please describe.**
Yes, in a larger server I'm in people like to spam react reactions and then remove them all over and over when they find out we can use them when you have 3-4 threads all being replied to by their respective teams (Partnership, Moderation, Events, etc etc.) this slowly starts to lag the replies being sent by the bot, one person doing it is annoying to the supporter but no that bad but when multiple users are doing it tends to become a slight problem (you can still live with it, just kinda annoying)

**Describe the solution you'd like**
``transfer_reactions`` true/false config var, if set to FALSE then do not transfer emoji's between recipient to support or support to the recipient.

**Who will this benefit**
People who don't care about reactions being forwarded, people with childish users who like to do what they do to us, or server where using NSFW reactions is a thing that people do.

**Comment by fourjr** [comment]
Added to v3.6.3-dev1 which is still in development. Will be ready for public release soon.

**Comment by fourjr** [comment]
https://github.com/kyb3r/modmail/commit/306a158bc69e55008354238671149eb45e5e466b
