### ISSUE TITLE
[ISSUE] Youtube tutorial 

### ISSUE THREAD

**Issue by RealZnowman** [kyb3r/modmail#2765]
The youtube tutorial in the Wiki is deleted and I cant check to see if I have done all the steps correctly

If you can please show me a video of the tutorial, Thank you! 

**Proof**
<img width="1353" alt="Screen Shot 2020-02-14 at 5 12 28 PM" src="https://user-images.githubusercontent.com/50973050/74575635-5ed03180-4f4d-11ea-8e9e-b71e6f7cbdaf.png">

**Comment by RealCyGuy** [comment]
I don't know why it doesn't work, but if you need help you can join the support Discord server! :)

**Comment by codeinteger6** [comment]
The YouTube channel has been deleted

**Comment by StephenDaDev** [comment]
Not a bug, Youtube took it down because it was "Copyrighted". Please use the tutorial on the wiki while we decide if we would like to create a new version of this video. (I have a way to stop it from getting taken down again)
