### ISSUE TITLE
[BUG] I've done everything correct but bot goes online and than offline 

### ISSUE THREAD

**Issue by catsarecoo** [kyb3r/modmail#2769]
Yes, I've been done everything correct but bot goes online for 1 sec than goes offline. Host method is heroku
And idk how to fix it
i don't have any proof but i will get one

**Comment by StephenDaDev** [comment]
Hey there! Thanks for reaching out! This appears to be an issue with the bot itself, please join our support server as this is the best method to contact the support team.

**Comment by catsarecoo** [comment]
but where do i find invite for support server @StephenDaDev
