### ISSUE TITLE
[Request] Add help Page in paginator

### ISSUE THREAD

**Issue by mischievousdev** [kyb3r/modmail#2770]
Add help page in paginator, which shows the usage of the emojis, and how to use commands like that, which is very usefull for us. Im already posted this request in server also.

**Comment by StephenDaDev** [comment]
So I understand ``which shows the usage of the emojis`` as you explained this to me, but what do you mean by ``how to use commands like that`` command usage is included when doing ``[p]help command``

**Comment by mischievousdev** [comment]
Like <argument> - This means required like that, seperate page for emoji help and command arg help

**Comment by StephenDaDev** [comment]
Oh so put it in ``<>`` for required and ``[ ]`` for optional, and then have a way to define this to the user

**Comment by mischievousdev** [comment]
ya
