### ISSUE TITLE
Keyword alerts

### ISSUE THREAD

**Issue by khionu** [kyb3r/modmail#2772]
**Is your feature request related to a problem? Please describe.**
We'd like to be able to distinguish between urgent mail and less-urgent mail.

**Describe the solution you'd like**
Keyword checking in the first message sent. So, if someone says "[Hammer]", our Hammer role will get pinged by the bot.

**Describe alternatives you've considered**
A short set of questions that must be answered after the initial complaint.

**Who will this benefit**
Moderators who wants conditional notifications based on their member's needs.

**Comment by Taaku18** [comment]
Ref #649

**Comment by khionu** [comment]
That's a different functionality entirely, even if it's also keyword-driven.

**Comment by StephenDaDev** [comment]
Yes and no, It still routes threads differently and can be used for urgency.

**Comment by khionu** [comment]
This issue is still relevant. While #649 would have (closed for being stale) provided a similar solution, it would not have enabled any sort of notification through Discord. You can't have default notifications per category, so #649 would not have aided in faster response times.

**Comment by khionu** [comment]
Can I get this issue reopened, please? This is still relevant.
