### ISSUE TITLE
Confirm thread creation

### ISSUE THREAD

**Issue by khionu** [kyb3r/modmail#2773]
**Is your feature request related to a problem? Please describe.**
We're getting a lot of threads started by people who won't bother to read anything and just send the bot a message like "hi", not realizing we take this very seriously.

**Describe the solution you'd like**
A confirmation before starting the thread, in the form of a message with reactions for confirm/cancel.

**Describe alternatives you've considered**
Command instead of reactions.

Note, I'm already working on adding this feature to the bot, but if this can be approved, I would like some help discussing a minor blocker I found in the bot structure, and then I can PR it.

**Comment by StephenDaDev** [comment]
Hey! Thanks for leaving feedback, without user feedback and suggestions Modmail wouldn't be where it is today. 

While this suggestion is greatly appreciated a better way to implement this would *probably* be in #398 (Accidental Threads) as this only filters certain messages allowing users who know how the system works to just DM and not have to deal with a confirmation every time they'd like to contact the support team via the bot.

**Comment by kantenkugel** [comment]
Just my two cents:

I think that keeping a list of words to ignore, or trying to figure out what should start one vs what shouldn't is probably way too hard or not feasible. Therefore, a Command or reaction seems like the better solution for me.

This would only be needed to start a thread and the bot could just give some information like"There is no active Thread. Do you want to start one?" together with either the command or reaction possibility.

I don't think that this is too high of an entry barrier, considering users usually super rarely wanting to actually create a modmail thread, the bot helping out with creating and you only having to do it once per Thread

**Comment by StephenDaDev** [comment]
That's with your usage, for servers who use modmail MUCH MORE (I have over 300 threads in about a month) this will start to be a pain. This helps some server but causes issues for others

**Comment by khionu** [comment]
In the work I've been doing locally, I added it as a configuration. I have no opinion on it being on or off by default, but I think it would be a nice feature. 

300 threads over a month is significant, sure, but this overhead concern would be felt on a per-thread basis on the user side. That said, it would be easy enough to make it a one-time check. UserId -> DateTime, so if the message gets updated they have to agree again.

Are there other concerns that you have? I'd be happy to address concerns until the idea is in a state where you'd be welcome to have it submitted.

**Comment by StephenDaDev** [comment]
One time could be helpful, when that concept is brought in it becomes more logical

**Comment by khionu** [comment]
Alright! I'll have a PR open in a couple days.

**Comment by khionu** [comment]
I assume you'd rather have the default as "off"?

**Comment by DAzVise** [comment]
> I assume you'd rather have the default as "off"?

Yeah probably

**Comment by khionu** [comment]
I was never able to get around to finishing this feature, but it's still relevant.

**Comment by khionu** [comment]
Can I get this reopened, please? It's still relevant.

**Comment by Markus2809** [comment]
Who you asking?

**Comment by khionu** [comment]
Can someone reopen this and also remove the Stale label?

**Comment by Anonymyous678** [comment]
👍 I agree with this

**Comment by ririko5834** [comment]
I like this feature request. This would be great, please add it.

**Comment by Anonymyous678** [comment]
Why someone who is a good python dev can't code this? 🙏

**Comment by Anonymyous678** [comment]
@khionu When you will make PR?

**Comment by fourjr** [comment]
Added to v3.6.3-dev2 which is still in development. Will be ready for public release soon.
