### ISSUE TITLE
New replies in a thread cancels the [p]close cancel command for the autoclose

### ISSUE THREAD

**Issue by OviiiOne** [kyb3r/modmail#2779]
**Describe the bug**
With the autoclose set up if you do the `[p]close cancel` command the intended behavior is for the ticket not to close. But if someone replies to the ticket the autoclose countdown will start again.

**Bot Info**
Bot version: 3.4.1
Host method (Heroku, self-host, etc): Hosted on a VPS

**To Reproduce**
Anyone can reproduce the bug.
1. Set up the auto close for the tickets, let's say, 12h for example.
2. Open a new support ticket via messaging the bot.
3. Type the `close cancel` command.
4. Reply to the support ticket or send a new message to modmail.
5. The ticket will autoclose in the time set up in the configuration.

**Error Logs**
https://hasteb.in/ucivoxir

**Screenshots**
[Screenshot 1](https://i.imgur.com/9Q7WKXU.png)
[Screenshot 2](https://i.imgur.com/Cbdvt6T.png)

**Additional context**
Disabling auto close and enabling it again does not solve the problem

**Comment by Taaku18** [comment]
Hi thanks for reaching out. For now, this behaviour is by-design. `?close cancel` only meant to cancel auto-close for the auto-close session after the latest reply. If a further reply is made then the auto-close timer will restart. If more people opt for your change, we may add that as a feature in the future.
