### ISSUE TITLE
Multistep aliases 

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#278]
Be able to have an alias do mutiple things in one command. 

For example:
(1 is the first thing to run, 3 is the last thing to run)
1. ``anonreply [survey message]``
2. ``move surveys``
3.  ``close 2h Closed due to inactivity.``

All with running one command

**Comment by kyb3r** [comment]
I may think of implementing this via `&&` signs. For example `?alias add x anonreply hi there && move surveys`

**Comment by fourjr** [comment]
For now, you can use `alias add eval ` to produce a similar result

**Comment by MiTonder** [comment]
How?
