### ISSUE TITLE
Restrict viewing sensitive threads and their logs on a thread-by-thread basis.

### ISSUE THREAD

**Issue by daegontaven** [kyb3r/modmail#2781]
**Problem**
Often times when in a discord server that handles sensitive information, it is difficult to prevent some eyes from seeing such data in a thread. There is no way to gate keep this info from junior moderators except to lock all threads with OAuth login to some roles. This has the unfortunate consequence of making it impossible for junior mods to view non-sensitive material on their own since all threads are locked by default.

**Solution**
We can make a `!lock level ADMINISTRATOR` command that will do the following:
- Disable view channel permission (in the thread) for everyone who is below that level.
- Disallow viewing logs in log viewer for everyone below that level.
- Ping `@here` in the thread about the change.

In the same way we can use `!lock role <target>` to lock to users or roles.  Meanwhile OAuth whitelists can still be used to globally prevent outsiders from viewing the logs (might require re purposing that part of the code).

An `!unlock <key_or_link>` can be used when it is deemed non-sensitive.

**Who will this benefit?**
This mainly affects discord servers that have some sensitive information being sent in DMs. One example is the server that verifies ID cards to validate credentials. It's not good to let junior mods have access to this data.

**Notes**
I want to mention that the specific name of the command doesn't have to be `!lock`. I can think of some use cases where that may be used for other purposes (like making a channel read only). But I think nevertheless this is the best use case. I also wanted to air this here to see if this is actually a good idea. If after some deliberation, I get the go ahead, I wouldn't mind writing the code for this feature myself.

**Comment by StephenDaDev** [comment]
This has been requested countless times, but I can't seem to find the issue for it. May have accidentally been deleted when the spam issues were removed. I think its __needed__.

**Comment by daegontaven** [comment]
@StephenDaDev I couldn't find it either. Anyways, if it is found then I'll close this and reference that issue instead 😅.

**Comment by HowlingHell009** [comment]
I am just going to say, this is already possible via making multiple categories and using the !move command. You can then remove a certain discord role from that channel.

**Comment by daegontaven** [comment]
@HowlingHell009 This is about protection of logs through OAuth, not access to threads from channels.
