### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by RobzHD** [kyb3r/modmail#2782]
I'm not sure what this means. How can it be fixed?

**Comment by daegontaven** [comment]
Please be more specific than that. You can use the `[p]debug` command to check for the full traceback if this was a runtime error. You are supposed to respond to each question [here](https://github.com/kyb3r/modmail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md.) when writing bug reports.

**Comment by RobzHD** [comment]
Where do I use the command?

**Comment by RobzHD** [comment]
It's all been fixed now. It's okay.

**Comment by daegontaven** [comment]
You should drop by our [discord server](https://discord.gg/etJNHCQ) to receive support for any future installation issues.
