### ISSUE TITLE
Suggestion: Marked NSFW modmail threads should be marked as NSFW on the logs

### ISSUE THREAD

**Issue by OviiiOne** [kyb3r/modmail#2792]
**Is your feature request related to a problem? Please describe.**
Not really. I like to review what the support team has answered when I was not active, and sometimes when I open the ticket logs I see things I cannot unsee now.

**Describe the solution you'd like**
If a modmail thread is marked as NSFW while it's open, the log sent to the log channel should indicate there's NSFW on that thread log.

**Who will this benefit**
I guess everyone who has access to the logs can benefit as they will know if there's something not safe in the ticket before opening it.

**Comment by Computer-Man497** [comment]
I can second this

**Comment by StephenDaDev** [comment]
Hi There! Thanks for reaching out to suggest something for Modmail, we love hearing your suggestions as it helps us shape the bot to what our users want it to be. However this is a logviewer related suggestion, therefore it belongs on the repo [kyb3r/logviewer](https://www.github.com/kyb3r/logviewer).

**Comment by OviiiOne** [comment]
My bad, thanks for pointing it out ^^
I'll suggest this again in the logviewer repo.

**Comment by RealCyGuy** [comment]
@StephenDaDev OP asked for the log in log channel to be marked nsfw, not the link. Even for the link, modmail currently does not record nsfw in the log.

**Comment by StephenDaDev** [comment]
True, it is a suggestion for both in that case.
