### ISSUE TITLE
Ability to set mentions via user/role ID

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#2796]
**Is your feature request related to a problem? Please describe.**
When I have to update the mentions using the `[p]mentions` command, I would have to keep mentioning those who want to be mentioned which may annoy them. Creating a temporary channel just to change it may not always be an option if you have people in admin roles, who can see every channel.

**Describe the solution you'd like**
Inputting the user or role ID instead of directly mentioning

**Describe alternatives you've considered**
Can't think of any

**Who will this benefit**
Staff, as they may not enjoy being pinged for no reason

**Comment by Anubhav1603** [comment]
If we just put user name with discriminator and id next to it ,it will do the job i guess
for example - Anubhav#3355(123456789)

**Comment by codeinteger6** [comment]
@Anubhav1603 just putting User ID should be enough.

**Comment by Anubhav1603** [comment]
Ok
