### ISSUE TITLE
[BUG] Memory Leak (Sasiko#1234)

### ISSUE THREAD

**Issue by matrix2113** [kyb3r/modmail#2801]
**Describe the bug**
Memory leak which is caused by the following;      1 possibly the login? but the bot constantly restarts due to guild no found and plugin misc errors too
2 fallback category causes memory leaks if you dont have the bot the permissions to create category

**Bot Info**
Self Hosted (pm2) v3.4.1

**To Reproduce**
Unsure. Seems to be erratic.
Could be also using the role reaction plugin if it caches offline users as well.

**Error Logs**
https://cdn.discordapp.com/attachments/528927720063631360/715547924351680555/message.txt

**Comment by XtoMHA96** [comment]
I add new data to this problem:

When restarted multiple times, the values of "log_channel_id" and "main_category_id" change to "None", so it stops logging. I have set these options manually, but they change back to "None".

**Comment by Sasiko** [comment]
Ever since the modmail had to update discord.py version, my modmail bot stopped causing memory leak. 
my modmail bot is  now using 158MB ram
