### ISSUE TITLE
Disable Eval

### ISSUE THREAD

**Issue by Sasiko** [kyb3r/modmail#2803]
Option to disable eval on .env 

This is important, especially when you dont want to use eval and account getting compromised can lead to injecting malicius files etc

**Comment by Taaku18** [comment]
Will be added in the next version of Modmail.

**Comment by RealCyGuy** [comment]
but the person with access to the account could just re-enable the eval command

**Comment by Taaku18** [comment]
> but the person with access to the account could just re-enable the eval command

The config var can only be changed in the config file/env vars, which requires you to have access to the file system.

**Comment by lorenzo132** [comment]
@Sasiko This has been added by now, add the line `ENABLE_EVAL=no` to your `.env`
