### ISSUE TITLE
How To Create Log View ?

### ISSUE THREAD

**Issue by Dove23** [kyb3r/modmail#2805]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Who will this benefit**
Does this feature apply to a great portion of users?

**Additional context**

**Comment by StephenDaDev** [comment]
Hello! The issues section of GitHub is reserved for suggestions, bugs, and other development-related things. Please ask our support team for help in the future (You can do so [in our support server](discord.gg/etJNHCQ). To answer your question, the process of deploying the logviewer is explained [on our tutorial](https://github.com/kyb3r/modmail/wiki/Installation). Thank you for your support of Modmail!

**Comment by StephenDaDev** [comment]
@Taaku18
