### ISSUE TITLE
Custom Questions at the start of dm chat

### ISSUE THREAD

**Issue by Mystik01** [kyb3r/modmail#2806]
**Is your feature request related to a problem? Please describe.**
Feature is not related to a problem

**Describe the solution you'd like**

When members open a chat, they are greeted with custom questions that we can setup, some questions should be have a specific answers too. 
Q1, what's the subject of your enquiry?
Q2, please provide a description of your enquiry.
Then this information will be displayed as the first messages in the channel where the messages are sent and received by the mod. Some questions should have specific answers eg, if your reporting a discord user the bot should be able to detect if that's a valid user in the server that the user has replied with. 

**Describe alternatives you've considered**

Categories, when members open a chat, they have to select a category that their issue fits into and could use reactions to choose the category. See image below, from Yunite Discord Bot.
![Screenshot_20200608-234500~2](https://user-images.githubusercontent.com/65687597/84087520-38457300-a9e2-11ea-856b-51c8d0ed0d54.png)

**Who will this benefit**
Does this feature apply to a great portion of users?

It will benefit mods or who ever answers the tickets, helps them know what issue that the user has.

**Additional context**

None.

**Comment by martinbndr** [comment]
Yea that would be a nice idea!

**Comment by Anonymyous678** [comment]
👍 This seems to be useful idea. Please make plugin for this.

**Comment by lorenzo132** [comment]
Hey @Anonymyous678 @martinbndr and @Mystik01 ,
This already is possibly without plugin, simply do `?config set thread_creation_response Your custom message here`

**Comment by lorenzo132** [comment]
Just the catagory choosing isn't a feature

**Comment by Anonymyous678** [comment]
Yes but i want reaction menu with number buttons for choosing support department before opening thread.  Or maybe bot should ask some setuped questions before opening thread (something like application bot)

**Comment by lorenzo132** [comment]
@Anonymyous678 You may request this plugin idea in our plugin server^^  https://discord.gg/4JE4XSW
i'm pretty sure someone is willing to put a bit of time in it to make a plugin for this

**Comment by Merp-Me** [comment]
Yes, this addition would be amazing, it would sort out all threads and not mix them up with the regular ones. Instead of a plugin, if it could just be a new feature, it would be a lot better :p

**Comment by Anonymyous678** [comment]
> Yes, this addition would be amazing, it would sort out all threads and not mix them up with the regular ones. Instead of a plugin, if it could just be a new feature, it would be a lot better :p

👍  I agree with this

**Comment by StephenDaDev** [comment]
I would merge #2773 (Confirm Thread Creation) Into this as well, have a "Nevermind I don't wish to create a thread" option by default.

**Comment by ririko5834** [comment]
I like this feature request. This would be great, please add it.

**Comment by Anonymyous678** [comment]
This is so amazing feature request 👍

**Comment by Anonymyous678** [comment]
Why is this still not completed?

**Comment by Ronish1122** [comment]
Would be great to have a feature like this :)

**Comment by Anonymyous678** [comment]
@Ronish1122 Yes, it would be.

**Comment by fourjr** [comment]
I just had a read through this again. From my understanding, the request is to have the bot send an embed and wait for user's reactions, relay reactions to the bot.

Here are the reasons for labelling it as out of scope:
1. A plugin can easily accomplish these steps as the `on_thread_ready` is exposed.
2. Reactions are linked from user -> mod, a mod can easily send out these messages and any reactions would be visible on both ends.
