### ISSUE TITLE
Bot token changed

### ISSUE THREAD

**Issue by Mystik-Rogue** [kyb3r/modmail#2808]
Hi,
I accidentally uploaded my bot-token online but Discord automatically regenerated it which has now stopped my bot working...
Anyway I can change the bot token on heroku?

**Comment by lorenzo132** [comment]
Hey there, you can change this in your `config vars` https://i.imgur.com/L2jNfOt.png

**Comment by Mystik-Rogue** [comment]
> Hey there, you can change this in your `config vars` https://i.imgur.com/L2jNfOt.png

Thanks bro, appreciate it.
