### ISSUE TITLE
Times close with 2h and above, not accurate or wont work.

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#2809]
**Describe the bug**
When you close a thread with a timer of 2 hours, for example `?close 2h` This will not work and fail to close after 2 hours.

**Bot Info**
Bot version (check with `@modmail about`): `3.4.1`
Host method (Heroku, self-host, etc): Hosted using a VPS, ubuntu 19.10

**To Reproduce**
1. Who can reproduce? Those that can close threads.
2. Where can it be reproduced (ex. in thread channels, recipient DM's)?
  This can be reproduced in the thread channel.
3. Done what to cause the error? 
   Create a thread > `?close 2h` > fails to close after 2 hours
4. Any recently made changes to your bot? No changes were made.
5. Errored: Fails to close

**Error Logs**
https://hasteb.in/dipumusu

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
https://cdn.discordapp.com/attachments/676825933587415050/721746965737504878/Knipsel.PNG

**Additional context**
Appeared to happen with multiple modmail instances ( also other people their modmail instances )

**Comment by Taaku18** [comment]
Thanks for reporting, if there’s something extraordinary in the logs can you repaste it please, the log link doesn’t work. And a few questions: Is it only for 2h and is it consistent?

**Comment by RealCyGuy** [comment]
I can't view the logs with https://hasteb.in/dipumusu

**Comment by StephenDaDev** [comment]
I have been unable to replicate this with any bot I have access to, mostly VPS, some Heroku
