### ISSUE TITLE
Doesnt Ping the assigned role every thread crated

### ISSUE THREAD

**Issue by EyeEnyx** [kyb3r/modmail#2810]
![image](https://user-images.githubusercontent.com/61381475/84761933-badebb80-affc-11ea-941f-db3fd2b07490.png)
![image](https://user-images.githubusercontent.com/61381475/84761959-c500ba00-affc-11ea-957e-52231860278a.png)

**Comment by StephenDaDev** [comment]
Can you please give us Bot Details, reproduction steps, and insight on how you are hosting this?

**Comment by EyeEnyx** [comment]
> Can you please give us Bot Details, reproduction steps, and insight on how you are hosting this?

![image](https://user-images.githubusercontent.com/61381475/84842504-e05cdb00-b077-11ea-8708-a7192733167c.png)
i filled the required on this easy deploy mod mail one, sorry im not into coding, i just really follow the steps how to host it and how to setup it thank you

**Comment by RealCyGuy** [comment]
@EyeEnyx, can you post your logs here?

**Comment by EyeEnyx** [comment]
> @EyeEnyx, can you post your logs here?

![image](https://user-images.githubusercontent.com/61381475/84842825-bd7ef680-b078-11ea-9922-b96cb50456cb.png)
this one ?

**Comment by RealCyGuy** [comment]
@EyeEnyx 
![Heroku logs](https://i.imgur.com/TTrhitm.png)

**Comment by EyeEnyx** [comment]
> @EyeEnyx
> ![Heroku logs](https://camo.githubusercontent.com/35cdd4081fb13572c4081cd0993607634d4de027/68747470733a2f2f692e696d6775722e636f6d2f5454726869746d2e706e67)

oh my bad
![image](https://user-images.githubusercontent.com/61381475/84842946-21092400-b079-11ea-99bf-04758f77db40.png)

**Comment by fourjr** [comment]
Hey, if you are still having trouble setting up the bot, please DM modmail on our discord.

https://discord.gg/etJNHCQ
