### ISSUE TITLE
Let modmail assign modmail ticket in specific category

### ISSUE THREAD

**Issue by Sasiko** [kyb3r/modmail#2817]
Setup a config var of how many category you want. 
Make sure the category is properly labeled. 
Example
Category: Role assignment, Suggestions, Report scams

When users DM modmail to start a new modmail thread, when that user type any of those category names, modmail bot will then assign that thread to the appropriate category.

Example if user typed Role assignment, i want this role and modmail bot will be able to recognize that 

if it cant find any of the category name, just have a default uncategorized ticket id

**Comment by Bobinatorxl** [comment]
This is what I have been looking for, this would help so much!

**Comment by Anonymyous678** [comment]
Yes, modmail categories is great idea

**Comment by Anonymyous678** [comment]
Maybe add option to create reaction panels (something like TicketTool panels) with categories

**Comment by frostdevildan** [comment]
> Maybe add option to create reaction panels (something like TicketTool panels) with categories
Why do that, when support teams can just use the "move" function to move threads with a single command?

**Comment by Bobinatorxl** [comment]
Maybe I am not sure how the move function works, do you do for example ?move <category> cause I thought that wasn't how that worked.

**Comment by frostdevildan** [comment]
Yes. it is "?move Category name/ID". If your category consists of more than one word, put the name in " ".

**Comment by fourjr** [comment]
Duplicate of #2806
