### ISSUE TITLE
Can't get past Discord system resetting token

### ISSUE THREAD

**Issue by haydenwalker980** [kyb3r/modmail#2818]
**Bot Info**
Bot version: Latest, 3.4.1
Host method: Heroku

**To Reproduce**
1. Anyone can reproduce this.
2. In modern Discord, the system resets your bot token if it detects it online.
3. All you need is your token in the `.env` file
Heres what this looks like:
![image](https://user-images.githubusercontent.com/37120379/86544331-e0afff80-beda-11ea-8291-9c737893fab7.png)

**Comment by lorenzo132** [comment]
Hey, 
First off regenerate your bot token. This is not how you launch your modmail. 
You can launch your modmail bynusing this template https://dashboard.heroku.com/new?template=https://github.com/kyb3r/modmail

Sincerely lorenzo

**Comment by lorenzo132** [comment]
@haydenwalker980

**Comment by haydenwalker980** [comment]
> Hey,
> First off regenerate your bot token. This is not how you launch your modmail.
> You can launch your modmail bynusing this template https://dashboard.heroku.com/new?template=https://github.com/kyb3r/modmail
> 
> Sincerely lorenzo

Done that, the bot isn't coming online. Any help would be appreciated.

**Comment by haydenwalker980** [comment]
@lorenzo132

**Comment by StephenDaDev** [comment]
@haydenwalker980 Did you ensure you started the worker? [Here is a GIF on how](https://taaku18.github.io/img/turn-on.gif)

**Comment by haydenwalker980** [comment]
Done that, and it's working. I need the default prefix to have it work.

**Comment by haydenwalker980** [comment]
@StephenDaDev

**Comment by StephenDaDev** [comment]
Default prefix is ``?`` or you can simply ping the bot ``@modmail [command]``. @haydenwalker980

**Comment by haydenwalker980** [comment]
Okay. Thank you. I will close this issue now.
