### ISSUE TITLE
Embed Images from Gyazo

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#282]
Make it so the bot will embed images from Gyazo! Like this one https://gyazo.com/290a84af451200ea2408f4fe48371ad2

**Comment by kyb3r** [comment]
I'll just replace the url with `https://i.gyazo.com/290a84af451200ea2408f4fe48371ad2.png`

**Comment by StephenDaDev** [comment]
I heard some people use lightshot, (I despise it but ok) can we do that one aswell?

**Comment by fourjr** [comment]
Imgur as well.

**Comment by StephenDaDev** [comment]
Imgur is already done @fourjr 

Proof: https://imgur.com/AarqiJU

**Comment by officialpiyush** [comment]
Lol

**Comment by StephenDaDev** [comment]
Fucking shit. ITS NOT DONE MR

**Comment by fourjr** [comment]
Added to v3.6.3-dev2 which is still in development. Will be ready for public release soon.
