### ISSUE TITLE
Custom reactions

### ISSUE THREAD

**Issue by boingfromdiscord** [kyb3r/modmail#2826]
**Is your feature request related to a problem? Please describe.**
Not that I know of

**Describe the solution you'd like**
When setting up our instances on heroku maybe there should be an optional field for emojis instead of ✅

**Describe alternatives you've considered**
Not really sure

**Who will this benefit**
I feel like some people would like this

**Additional context**
None

**Comment by fourjr** [comment]
You can use config within the bot for this, look into `?config` and `?config options`, `sent_emoji` might be what you are looking for.
