### ISSUE TITLE
Add avatar icon when thread closed

### ISSUE THREAD

**Issue by Anubhav1603** [kyb3r/modmail#2828]
**Is your feature request related to a problem? Please describe.**
when thread get closed it dont show the details of mod who closed the thread,so its hard to predict mod has replied or modmail closed the thread on its own

**Describe the solution you'd like**
When thread gets closed by mod then bot should add mod avatar and little info thread has been closed by modname then text

**Describe alternatives you've considered**
Currently didnt able to think of any.

**Who will this benefit**
the author who writes to modmail

**Additional context**

**Comment by fourjr** [comment]
Hey, the name of mod is shown in the footer
![image](https://user-images.githubusercontent.com/28086837/97404093-7fe87f00-1930-11eb-8de9-07f2f140c44a.png)

**Comment by fourjr** [comment]
We will add the footer icon though
