### ISSUE TITLE
[FEATURE REQUEST] ModMail YT Channel

### ISSUE THREAD

**Issue by AuroroNightengale** [kyb3r/modmail#2830]
**Is your feature request related to a problem? Please describe.**
No, this feature request is related to making support a little bit easier.

**Describe the solution you'd like**
I would like the ModMail team to create a YouTube rand Account that will allow support and staff to make tutorials on both the core features as well as plugins to allow the support of users to be much easier

**Who will this benefit**
Yes. This would benefit both support and staff members as well as the users as it gives them a visual aid.

**Comment by fourjr** [comment]
Our team is working on this.
