### ISSUE TITLE
Notify staff when bot is pinged

### ISSUE THREAD

**Issue by ghost** [kyb3r/modmail#2833]
### ping mods upon bot ping
**This is how my feature goes**
@Modmail I need to help here
then it will ping the staff members with the msg @User has pinged the modmail with the msg I need help here
and the modmail will then put a msg on that channel where the user asked this msg
![image](https://user-images.githubusercontent.com/66989464/88539313-a8f62c80-d02e-11ea-8c98-604066558dc5.png)
### -------------------------------------------------------------------------------------------------
Question) i dont see how this could be useful though, cant the user just DM modmail instead?

Anwers)but it would be easier this way, like if someone is doing something against the rules..ppl can just report him by saying `@Modmail help is needed here/ rules are been broken here/etc.`

**Comment by fourjr** [comment]
Added to v3.6.3-dev2 which is still in development. Will be ready for public release soon.
