### ISSUE TITLE
Feature request: Userlog's

### ISSUE THREAD

**Issue by 13LuckyBack** [kyb3r/modmail#2836]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
That the user who created a Thread that he will get a log aswel.

**Who will this benefit**
All the users that created a Thread.

**Comment by StephenDaDev** [comment]
Can't they just scroll up and see what happen?

**Comment by 13LuckyBack** [comment]
Yes thay can but it looks nicer if thay have a link aswel

**Comment by Forcellrus** [comment]
That way they could see internal conversations as well, I'm not sure how many people would be happy with that.

**Comment by DAzVise** [comment]
Yeah Forcellrus has got a point, it could be set as a config but really the user shouldn't see the staff's conversations, i think this issue should get closed
