### ISSUE TITLE
[Command request] Titles for threads

### ISSUE THREAD

**Issue by XtoMHA96** [kyb3r/modmail#2838]
**Is your feature request related to a problem? Please describe.**
It is not a problem in itself, but sometimes an inconvenience in the logs. Users to open a thread only reply with 'Hello' and we do not know the content of the thread.

**Describe the solution you'd like**
In the logs when a thread has been closed, show the title set for the ticket instead of the first message sent by the user, by default if there is no title, it would show it. So by looking at the log history, we can identify the threads.

**Describe alternatives you've considered**
Alternatively, the description of the thread channel could also be updated by adding the title and clarifying the reason for the thread.

**Who will this benefit**
It would benefit all servers when searching for a specific ticket with its description / title.

**Additional context**
![](https://i.imgur.com/wUdX6xP.png)

**Comment by fourjr** [comment]
Added to v3.7.0-dev8 which is still in development. Will be ready for public release soon.
