### ISSUE TITLE
Expand ?note functionality

### ISSUE THREAD

**Issue by Sasiko** [kyb3r/modmail#2842]
Let **?note** data appear  in all  future modmail tickets. This can be useful when staff want to write a note for a special reason and want to inform future staff to read that note whenever that user submit a new modmail thread. 

?note right now only appear when you execute the command in the current modmail ticket but get wiped after ticket is closed. This should be changed with an option to make the note persistent in all future modmail related to the recipient in modmail.

Config options? 
ability to wipe the ?note data related to a user id or to all users, if user hasnt been in the server for X days

**Comment by StephenDaDev** [comment]
Potential Functionality:

``?note [msg]`` - Acts just as it does today

``?note persistent [msg]`` - triggers a persistent note

**Comment by Anonymyous678** [comment]
I agree with this

**Comment by RealCyGuy** [comment]
I am working on this, PR in a few days.
