### ISSUE TITLE
heroku no longer works

### ISSUE THREAD

**Issue by cesarsaiyan1835** [kyb3r/modmail#2857]
And the bot is off

**Comment by StephenDaDev** [comment]
Hey there! Thanks for reaching out! This appears to be an issue with the bot itself, please join our support server as this is the best method to contact the support team. https://discord.gg/F34cRU8

**Comment by lag145** [comment]
it works for me only logs cant load

**Comment by lorenzo132** [comment]
Hey @cesarsaiyan1835 , i'v just tested to create a clean instance of modmail using heroku, and it still seems to work. Please come to our support server for further assistance https://discord.gg/UANjXCC
