### ISSUE TITLE
How do you load plugins manually?

### ISSUE THREAD

**Issue by damagicalcat** [kyb3r/modmail#2863]
Based on the way I am hosting the bot, I can't install plugins through ?plugins add <name>
How do I load the plugins by adding it to the code manually?

**Comment by damagicalcat** [comment]
One of you is going to say "Why don't you ask this in the support server"
I got banned from it, so I can't...

**Comment by damagicalcat** [comment]
After several hours of trying different methods, you for plugins you create a new file under plugins\<authorname>\modmail-plugins\<pluginname>
And then in Mongodb, manage your collections and create a new array called plugins, and add <authorname>\modmail-plugins\<pluginname>@master for each plugin
Hoped this helped someone who had the same problem as me.

**Comment by matrix2113** [comment]
How are you hosting your modmail bot?

And also, we would recommend you to install plugins through `?plugins add` as it may be easier and sufficient. Although, it's up to you how you want to install plugins, however we cannot provide support for it if you break something.
