### ISSUE TITLE
Add config vars for the cooldown warn texts

### ISSUE THREAD

**Issue by Forcellrus** [kyb3r/modmail#2865]
**Describe the solution you'd like**
When someone tries to message the bot while they're on a cooldown, they get a messages such as:
```
Message not sent!
You must wait for 14 minutes and 43 seconds before you can contact me again.
```
Would it be possible to add config vars so we can translate them, like we have for `thread_auto_close_response` etc?

**Who will this benefit**
Anyone who runs the bot on a server that is not primarily English. It really helps keep up with the consistency (whole bot can be pretty much translated for the end user except for this aspect)

**Comment by Anonymyous678** [comment]
Good idea

**Comment by fourjr** [comment]
Unfortunately, we cannot add full support for such a usecase as the "14 minutes and 43 seconds" is dynamic. The most we can do is allow you to modify the text surrounding the time, such as the config option `You must wait for {delta} before you can contact me again.`.

**Comment by Forcellrus** [comment]
Wouldn't it be possible to replace "and" with & and allow us to edit "minutes" and "seconds" separately? That'd be the most elegant way to do it I think.

**Comment by fourjr** [comment]
That would be too much unnecessary config.

**Comment by fourjr** [comment]
Added to v3.7.0-dev3 which is still in development. Will be ready for public release soon.

**Comment by Forcellrus** [comment]
I don't see an issue with it if it's optional. It'd just good to have it for people who want to customize
