### ISSUE TITLE
Bot won’t let me use reply command even tho dms are open

### ISSUE THREAD

**Issue by 6days9weeks** [kyb3r/modmail#2866]
```Haskell
2020-10-27 14:11:12 __main__[540] - WARNING: Not in guild, cannot verify guild_age, pooli.
2020-10-27 14:11:12 core.thread[145] - ERROR: Failed unexpectedly:
Traceback (most recent call last):
  File "/home/noob/modmail/core/thread.py", line 141, in send_genesis_message
    msg = await channel.send(mention, embed=info_embed)
  File "/home/noob/.local/share/virtualenvs/modmail-kKl6vl4u/lib/python3.7/site-packages/discord/abc.py", line 870, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/noob/.local/share/virtualenvs/modmail-kKl6vl4u/lib/python3.7/site-packages/discord/http.py", line 225, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: This field is required
2020-10-27 14:12:51 cogs.utility[537] - INFO: -------------------------
2020-10-27 14:12:51 cogs.utility[546] - INFO: Activity set to: Dm For Help.
2020-10-27 14:12:51 cogs.utility[551] - INFO: Status set to: idle.```
If you're going to ask why I didn't ask in support server, maybe ask your mods to not ban anyone without a reason. I didn't even break any rules but oh well. If anyone knows how to fix this problem. Let me know. It's the error log I got from debug and if I try [p]reply I get user isn't in the server.

**Comment by PaeP3nguin** [comment]
This is likely due to the discord gateway update: https://support-dev.discord.com/hc/en-us/articles/360056426994, will probably require some changes to the bot itself

**Comment by 6days9weeks** [comment]
> This is likely due to the discord gateway update: https://support-dev.discord.com/hc/en-us/articles/360056426994, will probably require some changes to the bot itself

Oh alright. I'll wait for an update then but I need a replacement now tho my guild has 15k members so it's a big problem. Anyways, thanks.

**Comment by PaeP3nguin** [comment]
(note that I'm not a contributor)

Yeah I forked and will try to get it working on my server again. If it functions properly, then I might make a pull request.

**Comment by everlasting393** [comment]
Did anyone of you enable the gateway intents on the discord developers site? The bot wasn’t working for me too but then I remembered discord.py had an update so I turned on intents and it worked for me.

**Comment by PaeP3nguin** [comment]
Ah you're totally right, just need to turn on members intent in developer portal and it works again!

**Comment by 6days9weeks** [comment]
Yep, it worked for me too. Thank you so much. The bot took some time to boot but it's working.

**Comment by everlasting393** [comment]
Glad to help! And it’s so weird that I’m banned from the support server too.

**Comment by fourjr** [comment]
Hey, if you wish to appeal your bans, please let me know your discord user IDs in DM (4JR#4895) along with any relevant explanation. For now, I'll close this issue.
