### ISSUE TITLE
[BUG] Mention command forces it to be a role/member mention, normal txt gets ignored

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#2867]
**Describe the bug**
the mention command forces the mention to be either a role mention or a memebr mention. First you could add a normal text a thread creation mention..

**Bot Info**
Bot version (check with `@modmail about`): v3.6.2
Host method (Heroku, self-host, etc): VPS hosted

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? Anyone with perms to change the mention
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? In any channel the bot can read/write
3. Done what to cause the error? Change the mention to a normal text as it was allowed first
4. Any recently made changes to your bot? Updated to the latest version
5. Errored

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here. https://cdn.discordapp.com/attachments/682709693738778671/771119532512247808/39yIRfix.png ( no other logs are given, neither in the vps terminal )
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png) No logs given, it will say: `2020-10-28 21:03:29 core.config[206] - INFO: Setting mention.`

**Screenshots**
https://cdn.discordapp.com/attachments/682709693738778671/771118831820603412/CJWMydyc.png
**Additional context**

First you could add a plain text as mention, now it forces for some reason to be the mention either a role mention or a member mention.. Is this ment to be or a bug?

**Comment by fourjr** [comment]
This feature is intended. Use `?config set mention MESSAGE` for old behaviour.

Refer to #2796
