### ISSUE TITLE
Unable to connect to guild

### ISSUE THREAD

**Issue by ShowxBells** [kyb3r/modmail#2869]
**Describe the bug**
Unable to connect to guild which allows members to DM the bot, owners and people who have access are unable to reply/use any bot commands to get info on the member who needs help. Says the bot is unable to connect to guild.

**Bot Info** 
Uptime
0h 28m 59s
Latency
30.38 ms
Version
3.5.0
Authors
godspray

<img width="698" alt="Screen Shot 2020-10-28 at 8 28 53 PM" src="https://user-images.githubusercontent.com/73626775/97522110-39107e80-195c-11eb-944b-b23e17edb44f.png">

**Comment by fourjr** [comment]
Hey, please join our [discord server](https://discord.gg/etJNHCQ) and we will assist you from there.

From the info here, this seems like an intents issue. Try this fix:
Enable **all** privelleged intents in developer portal > Open app  > Bot and restart your bot.

![](https://i.imgur.com/OcZ8a43.png)
