### ISSUE TITLE
Ability to turn off embeds

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#287]
An ability to turn off all embed in the bot

#### Suggestion by Discord User Coderholic#4750

**Comment by fourjr** [comment]
Why would this be worth implementing? or why would it be helpful?

**Comment by kyb3r** [comment]
Do you want this:

/polls yes no

**Comment by codeinteger6** [comment]
I think it would be useful to have such an option in case some people have link embeds turned off in their Discord settings

**Comment by codeinteger6** [comment]
Some people may have link embeds turned off in their Discord settings, so maybe when someone DMs the bot to start a new thread, above the Thread Created embed is a text saying:

`If you cannot see the below embed, please turn on link previews in your Discord settings`

IMO that will be a better solution

**Comment by kyb3r** [comment]
IMO its not worth it to add some text above the embed for everyone just puts off the user experience with unnecessary text. Most people do have embeds turned on though.
