### ISSUE TITLE
Plain reply

### ISSUE THREAD

**Issue by Toberak1** [kyb3r/modmail#2872]
Hi
Can you please add ?preply (plain reply) command
It will reply to user without Embed (just plain text)
It will be useful when user is in mobile and cant copy content from embed

**Comment by DAzVise** [comment]
similar to #389, i think this is a highly suggested feature and should be added, but i'm not sure which way to implement this would be better (as a config or as a command)

**Comment by 6days9weeks** [comment]
I think it’d be good as a command instead of a config variable cause on the bot there’s `areply,reply,freply` so preply or whatever the devs add would be fine. I’m saying this as a user who uses modmail everyday and think a command would be better instead of config.

**Comment by Toberak1** [comment]
I think it would be more configuration, I am used to this. Look 
![Screenshot_20201103-154951](https://user-images.githubusercontent.com/61362061/98028080-5629cf00-1dec-11eb-9e8a-a9efbb1175cb.png)

**Comment by StephenDaDev** [comment]
Both.

**Comment by fourjr** [comment]
Added to v3.6.3-dev1 which is still in development. Will be ready for public release soon.

**Comment by RealCyGuy** [comment]
Plain replies can't be deleted.
`11/06/20 07:32:12 cogs.modmail[1318] - WARNING: Failed to delete message: DM message not found..`

Checks for embeds:
https://github.com/kyb3r/modmail/blob/aba9b71a5568daeac3ea4448141704e4a589b178/core/thread.py#L525-537

**Comment by fourjr** [comment]
Plain messages are not able to be deleted due to how we internally find linked messages. This will be a limitation until post-database update (probably v4.0)

**Comment by lorenzo132** [comment]
Maybe also add the config to recieve plain replies from the users dming the bot

**Comment by Toberak1** [comment]
The idea of ​​my proposal is that the answers are possible to copy on mobile. Since the embed are not selectable as text to be able to copy and paste
