### ISSUE TITLE
[BUG] Emoji Reaction threads

### ISSUE THREAD

**Issue by finalyzed** [kyb3r/modmail#2881]
**Describe the bug**
Using the new feature to Open a thread by clicking a reaction, the users can not close their thread by themselves like a normal thread would allow if they messaged the bot. Also, the thread creation does not ping any users from the ModMail team, it opens silently.

**Bot Info**
Bot version: 3.7.1
Heroku Host

**To Reproduce**
1. Who can reproduce: Anyone
2. Where can it be reproduced: Using the emoji reaction to open a thread

**Screenshots**
What the user sees if they click the reaction:
![image](https://user-images.githubusercontent.com/46934724/99094804-4eafb600-25a2-11eb-82c7-200772cd01a5.png)
What the modmail team sees if a new ticket comes in from the reaction:
![image](https://user-images.githubusercontent.com/46934724/99094890-6850fd80-25a2-11eb-86b7-36a4f31704b7.png)

vs.

What the user sees if the message the bot:
![image](https://user-images.githubusercontent.com/46934724/99094933-799a0a00-25a2-11eb-83df-71d4a21e0658.png)
and What the staff sees:
![image](https://user-images.githubusercontent.com/46934724/99094984-8ae31680-25a2-11eb-9e4d-fc76ba4d8a63.png)

**Comment by fourjr** [comment]
Fixed in v3.7.5
