### ISSUE TITLE
[BUG] Bot not mentioning when creating a new ticket

### ISSUE THREAD

**Issue by EGGamer** [kyb3r/modmail#2883]
Since the new update the bot is not mentioning when creating a new ticket. I've been reading the changelog and I can't find anything related to that specifically. I checked the config to see if the mention config var was still there and indeed it is. Is there something I need to do because it was changed?

Version: 3.7.5
Hosting method: Self-hosting in VPS and PM2.

![Config var](https://user-images.githubusercontent.com/40073654/99107315-ed113b00-25e5-11eb-80c5-53debd08f564.png)
![GJJLhg6pec](https://user-images.githubusercontent.com/40073654/99107339-f6020c80-25e5-11eb-9740-052cb711a18c.png)

**Comment by StephenDaDev** [comment]
How was this thread created?

**Comment by EGGamer** [comment]
It was created just like a normal one. Sending a DM to the bot.

**Comment by StephenDaDev** [comment]
Ok, I know the react to contact didn't earlier.

**Comment by jb3** [comment]
Can reproduce this, `mention` is set to `@here` but no ping ever comes through on thread creation.

**Comment by fourjr** [comment]
Fixed in v3.7.6
