### ISSUE TITLE
[BUG] Privileged intents...

### ISSUE THREAD

**Issue by Arnau97** [kyb3r/modmail#2886]
When i put pipenv run bot, i have this error

![image](https://user-images.githubusercontent.com/68655033/99128164-6ae73d80-260a-11eb-88fc-d1e42375d972.png)
What to do?

**Comment by lorenzo132** [comment]
Enable all privelleged intents in developer portal > Open app  > Bot and restart your bot.

https://i.imgur.com/OcZ8a43.png

**Comment by fourjr** [comment]
Ensure that you `pipenv install` again as well.
