### ISSUE TITLE
can't change thread_close_response

### ISSUE THREAD

**Issue by sir1k** [kyb3r/modmail#289]
![image](https://user-images.githubusercontent.com/51683010/59315367-2bece400-8cc2-11e9-88e0-801ea3dc3676.png)

![image](https://user-images.githubusercontent.com/51683010/59315373-30b19800-8cc2-11e9-920b-4a6c9da35912.png)

**Comment by StephenDaDev** [comment]
Have you had someone else close it? There is a chance the self-close response it overriding it.

**Comment by sir1k** [comment]
> Have you had someone else close it? There is a chance the self-close response it overriding it.

I closed it myself by clicking on lock icon

**Comment by StephenDaDev** [comment]
Ok, in that case, it is using the self-close response. You can change it with ``[p]config set thread_self_close_response``

**Comment by StephenDaDev** [comment]
# Not bug
## Simple Misunderstanding of Config Options

No Worries.
