### ISSUE TITLE
Some form of alert when the bot is updated.

### ISSUE THREAD

**Issue by dirtyformal** [kyb3r/modmail#2894]
My implementation of the Modmail bot is through the basic Heroku and MongoDB hosting. This is then set to automatically deploy upon a new pull request from my forked repo. One issue with this is that I typically only become aware of a Modmail update when an email comes along alerting me to the changes. This can sometimes be problematic for other users of the system when I'm away from my computer, which can happen frequently.

I would love the opportunity to have Modmail post into a user-configurable channel (either a non-Modmail controlled permanent channel or a Modmail thread) alerting us to an update and potentially posting a snippet of the changelog.

I have considered just forwarding this email to other Moderators or creating a script to forward it to another Discord bot, but I think it would be more beneficial to incorporate it into the Modmail bot itself. 

At the end of the day, this feature will only affect the 'behind-the-scenes' users of Modmail, and most likely only the admins of the bot, but it would be tremendously appreciated to have the alerts automated.

**Comment by StephenDaDev** [comment]
``?changelog`` will show the changelog.

And as of version 3.7.0, it can automatically update. Would you still be interested in this?

**Comment by fourjr** [comment]
This already happens in autoupdate in the log channel

**Comment by dirtyformal** [comment]
G'day, thanks to both of you for your replies.

> `?changelog` will show the changelog.
> 
> And as of version 3.7.0, it can automatically update. Would you still be interested in this?

I've already set up the auto-update feature, and I am aware of the `?changelog` command to show the latest changes. My request is that the bot automatically posts this to a channel upon updating. 

> This already happens in autoupdate in the log channel

In my server I have #modmail-logging, logging the thread closes. I can't seem to find the bot giving a changelog automatically in that channel, and I have trawled through the settings trying to find an option to enable this, to no avail.

**Comment by dirtyformal** [comment]
I have now seen that a command was implemented in v3.7.10 which was released overnight. [This commit](https://github.com/kyb3r/modmail/commit/34befb593824aaeee2979fc7d30f837509ccfc9a) references the addition of the `update_channel_id`. This change was made at the same time that @fourjr replied above.

As far as I can tell, the issue has resolved. Feel free to close. Thank you!
