### ISSUE TITLE
[BUG] Configuring the update command won't work.

### ISSUE THREAD

**Issue by OfficialBlueFoxy** [kyb3r/modmail#2897]
**What the bug is.**
So i wanted to configure the ?update command and followed all the steps, but when i finished and executed the command, it wouldn't quite work, and would show me an error message about not having configured my personal access token (PAT) but I actually did. I don't know if this is only on my case, if it works on other bots, then maybe i did something wrong or something has gone faulty in the code of my specific bot.

**Bot Info**
Bot version (check with `@modmail about`): v3.7.12
Host method (Heroku, self-host, etc): Heroku

**To Reproduce**
1. If not done yet, follow all the steps to configuring the update command.
2. Do [p]update.
(It's not a detailed explanation, i know, but there's really nothing more to it.)

**Error Logs**
https://hasteb.in/jipolebu

**Screenshots**
![Screenshot_20201121-233547_Chrome](https://user-images.githubusercontent.com/51539715/99890316-22f59580-2c5e-11eb-969d-307e8430789a.jpg)
![Screenshot_20201122-005950_Discord](https://user-images.githubusercontent.com/51539715/99890317-29840d00-2c5e-11eb-8a0b-118a369ce49d.jpg)

**Additional context**
Not really.

**Comment by Hamdanmohd** [comment]
umm

**Comment by fourjr** [comment]
Did you add `GITHUB_TOKEN` into your config variables?

**Comment by OfficialBlueFoxy** [comment]
> Did you add `GITHUB_TOKEN` into your config variables?

Yeah, i did.

**Comment by Hamdanmohd** [comment]
uhm if u have done it, then it woudn't show, idk more bout it, but i can guess there is something wrong in the config vars..

**Comment by wolfier74** [comment]
Does also autoupdate work on selfhost or another host than heroku?
