### ISSUE TITLE
Variables in Modmail status

### ISSUE THREAD

**Issue by Hamdanmohd** [kyb3r/modmail#2898]
i would like to suggest a good idea to the status of the bot,
while using the ?activity command, if we could set users in the status 
ex. by using ?activity Playing with {users} Users! or ?activity Watching {users} Users!
etc.. in the place of {users} it should show the users count in the status, this will be a great feature, thanks!

**Comment by wolfier74** [comment]
This is good idea. Maybe also add option to show opened thread count. So users can know how many active threads exist.

**Comment by Hamdanmohd** [comment]
uhm, i am talking about modmail status, not users in threads or something
smh

**Comment by RealCyGuy** [comment]
wolfier was talking about open threads as a status variable

**Comment by fourjr** [comment]
This is out of scope of Modmail. A plugin should be used for this.
