### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by wolfier74** [kyb3r/modmail#2899]
Hi, can you please **add option that only members in MODMAIL_GUILD_ID will be able to run modmail bot commands which uses database.**
Because i am getting error that my modmail is on more servers and it can cause database problems.

It should be config option like ?config set database_commands_whitelist (guild id where modmail commands can be used)
This would be helpful for those who want to have 1 modmail for more servers and dont want to have database problems.

**Or can you add command ?perms mass_override (command category/all) (perm level)**
This should override permissions to all commands in provided category or to all commands. 

I want to have 1 modmail for more servers, is there option to create support reaction panel on each server? 
Another suggestion: **Add option to create multiple support reaction panels.**

**Comment by fourjr** [comment]
I have no idea what you are talking about. Modmail is not supported on multiple servers.

**Comment by Hamdanmohd** [comment]
hmm
