### ISSUE TITLE
Anonymous snippets

### ISSUE THREAD

**Issue by kyle95wm** [kyb3r/modmail#2905]
**Is your feature request related to a problem? Please describe.**
Snippets are a great feature for sending pre-written messages that you would otherwise have to type out every single time. The problem is, if you want to run an anonymous modmail system, you would have to use a workaround that uses an alias to fire the `areply` command along with your snippet's message.

**Describe the solution you'd like**
A possible solution would be a config variable. Something like `anonymous_snippets`. If it's set to yes, then any snippet used will follow the anonymous reply flow instead of the regular reply.

**Describe alternatives you've considered**
Not sure what to put here if I'm being honest.

**Who will this benefit**
This feature would benefit those who wish to run an anonymous modmail system, meaning that staff aren't revealed unless they actually come out and say who is talking to the other user.

**Additional context**
n/a

**Comment by ririko5834** [comment]
Good feature

**Comment by owlcoolrule** [comment]
Hey there, you can easily use aliases to do tis right now before this features is added. Check out the code snippet I left below for your alias:
`{prefix}alias add {snippet_name} anonreply {text}`

Tell me how that works.

**Comment by kyle95wm** [comment]
Indeed, that's what I've been using in the meantime. While it does work, I feel that snippets should have a way to make them anonymous.
