### ISSUE TITLE
Ticket claiming

### ISSUE THREAD

**Issue by JOX3944** [kyb3r/modmail#2906]
**Is your feature request related to a problem? Please describe.**
when you have multiple helpers it can be hard to know who is answering a ticket so this this would help

**Describe the solution you'd like**
Allow a support member to claim tickets and move them to teams as needed

**Describe alternatives you've considered**
I have considered using different categories and other bots but they didn't work out

**Who will this benefit**
It would benefit users and teams with large amounts of people so support teams wnt get confused.

**Comment by StephenDaDev** [comment]
Duplicate of #2754

**Comment by ririko5834** [comment]
This is good feature

**Comment by JOX3944** [comment]
Please add this!
