### ISSUE TITLE
Disallow or redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by BreezeQS** [kyb3r/modmail#2908]
While reading the logs of a few threads, i noticed that it's possible to access the logviewer over HTTP simply by removing the S. And the logviewer allows one to view a log over plain, unencrypted HTTP. Now, this is not a big issue. It's unlikely that someone will remove that s since the links posted to log channel are all https. And even if they do, it's unlikely for a modmail thread to contain much sensitive info like a password which should not exist on a message sent over Discord anyway. But it was still wondering if something to redirect people trying to access over plain HTTP to HTTPS can be done.

**Comment by lidistat67** [comment]
Hey. When changing https:// to http:// most browser will warn the users that the site is not secure and as you said it's unlikely for someone to change it from https:/
