### ISSUE TITLE
Interactive Permissions Setup

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#291]
When you install the bot, after you run ?setup. You will be presented with a prompt (either in the channel you use ?setup in or DMs, to setup permissions. (Also could do it included in Takki's World Famous Interactive Setup)

**Comment by codeinteger6** [comment]
There could also be a quick setup option, which looks at the perms the Discord roles have, and set up the permissions based on that.

**Comment by kyb3r** [comment]
[![](https://api.gh-polls.com/poll/01DD5YZXW78Y7M6BAATDPCXTM9/yes)](https://api.gh-polls.com/poll/01DD5YZXW78Y7M6BAATDPCXTM9/yes/vote)
[![](https://api.gh-polls.com/poll/01DD5YZXW78Y7M6BAATDPCXTM9/no)](https://api.gh-polls.com/poll/01DD5YZXW78Y7M6BAATDPCXTM9/no/vote)

**Comment by Taaku18** [comment]
Thank you all for voting! In order to have the potential to be implemented, we need to determine the visual of prompt and the workflow of the interactive setup. Suggestions?

**Comment by StephenDaDev** [comment]
Working on concept

**Comment by CupCakefanuwu** [comment]
Yes

**Comment by StephenDaDev** [comment]
![634b3da38782048ac77b8201f593faf5](https://user-images.githubusercontent.com/48072084/72385310-360a1180-36ed-11ea-96f6-4f40450bf1e0.png)
Is the overall if you can't read something on it I have a zoomed-in version step=by-step version here https://docs.google.com/presentation/d/1s9Az5Ln-cO8iOuvH2BBOQh2PMGwEB-OmNGRnX-8XKOY/edit?usp=sharing

**Comment by officialpiyush** [comment]
Looks sick
