### ISSUE TITLE
Add Jump to page to reaction menus

### ISSUE THREAD

**Issue by wolfier74** [kyb3r/modmail#2913]
Can you please add button Jump to page to reaction menus (help, plugins list, ...)?

**Comment by fourjr** [comment]
When will this be useful? A jump to page button would require you to know the "page number", I don't think many people will be able to remember that.

In addition, `?help` and `?plugins list` both allow you to specify a cog/plugin name to jump to a certain page.

**Comment by wolfier74** [comment]
Useful when bot ping is higher and it take longer to change page. And you dont have to remember page numbers

**Comment by wolfier74** [comment]
They will use arrows

**Comment by StephenDaDev** [comment]
We don't already have arrows?

**Comment by wolfier74** [comment]
Yes we have, but please add also Jump to page.
Is it hard to code?

**Comment by fourjr** [comment]
As the labels show, this feature request is currently set to low priority as it will benefit a very small number of users. If you want and you know python, you can add it yourself and create a pull request.

**Comment by lorenzo132** [comment]
> Can you please add button Jump to page to reaction menus (help, plugins list, ...)?
![Ass1420](https://user-images.githubusercontent.com/50767078/142765741-a321a907-d2f5-4f49-9c1b-9277ab00200d.png)

![Mastiff1421](https://user-images.githubusercontent.com/50767078/142765770-ab0549d4-7c85-4c10-8973-cd74ae9f70d6.png)
https://github.com/kyb3r/modmail/tree/development

**Comment by lorenzo132** [comment]
> > Can you please add button Jump to page to reaction menus (help, plugins list, ...)?
> > ![Ass1420](https://user-images.githubusercontent.com/50767078/142765741-a321a907-d2f5-4f49-9c1b-9277ab00200d.png)
> 
> ![Mastiff1421](https://user-images.githubusercontent.com/50767078/142765770-ab0549d4-7c85-4c10-8973-cd74ae9f70d6.png) https://github.com/kyb3r/modmail/tree/development

adding to this, buttons on log embeds.
- https://github.com/TheDiscordHistorian/historian-cogs/blob/main/logbutton/logbutton.py

**Comment by fourjr** [comment]
Certain paginators now support select menus as of v4.0.0-dev6. Proper jump to page support for all other paginators will be added upon https://github.com/discord/discord-api-docs/discussions/3689
![image](https://user-images.githubusercontent.com/28086837/142852406-910384dd-dc51-40ff-bf19-1bda7dcf87b2.png)
![image](https://user-images.githubusercontent.com/28086837/142852461-1efc3faa-1b84-42d8-9ea3-4d77597267d6.png)
