### ISSUE TITLE
Add COMPETING status 

### ISSUE THREAD

**Issue by wolfier74** [kyb3r/modmail#2914]
Can you please add option to setup COMPETING activity? Its type 5

Also I would like to have option to use variables in modmail activity. For example add:
- {members} - Main guild member count
- {opened_threads} - Count of opened modmail threads
- {supporters} - Count of users who have role with perm level SUPPORTER
- etc.

**Comment by StephenDaDev** [comment]
Staged in [#2902](https://github.com/kyb3r/modmail/pull/2902)

**Comment by fourjr** [comment]
Modmail already supports COMPETING activity in all versions, just specify `competing` in `?activity.

Variables are out of scope and a duplicate of #2898
