### ISSUE TITLE
Nickname requests

### ISSUE THREAD

**Issue by vNziie** [kyb3r/modmail#2915]
Nickname requests: I will explain the nick name requests a little further. So, you can set up nick name requests by setting a nickname request channel. A user can use “<prefix>nick (what they want there nickname request to be)”. Then, then the bot puts out “Your nickname request has been submitted!”. You are able to set the channel of where the nickname request go to. Then, the nickname request will go to that channel,  in an embed. The embed will say what the users nickname request is. The bot will automatically add the reactions of “👍” and “👎”. The “👍” emoji will accept it and send a DM to that user saying what there nickname has been changed to and what they requested it to be.  The bot will also change the nickname of the user that requested it to what they requested it to be. The “👎” will deny the request and the moderator is able to provide a reason of why it was enabled. The bot will also send the user that requested it the reason (if the moderator provided a reason) and what they requested there nickname to be. If the moderator does not provide a reason why there nickname request was denied, the reason will be “No reason provided”. Also, we are able to customize the pre-set deny and accept reasons and. Also, the bot will remove the reactions when a moderator accepted/denied the request. The bot will also edit the request embed to (Accepted/denied by (user/moderator) and provide the reason if the mod/user provided one of it was accepted or denied.

**Comment by fourjr** [comment]
This is out of scope of modmail. You can create a plugin for this feature.

**Comment by vNziie** [comment]
How do I create my own plug-in? And is it easy? Also, would I be able to get help to create my own plug-in?

**Comment by RealCyGuy** [comment]
You can see info here: https://github.com/kyb3r/modmail/wiki/Plugins If you want help, you can ask in `#coding` or `#plugin-creation` in the [Modmail Discord Server](https://discord.gg/etJNHCQ). You can also request your plugin to be made in `#plugin-requests`
