### ISSUE TITLE
[BUG] Reacting to the emoji of `confirm_thread_creation_deny` opens a thread.

### ISSUE THREAD

**Issue by XtoMHA96** [kyb3r/modmail#2916]
**Describe the bug**
If a user reacts to the emoji of `confirm_thread_creation_deny` a thread is opened.

**Bot Info**
Bot version (check with `@modmail about`): 3.7.13
Host method (Heroku, self-host, etc): Self-hosting in a VPS

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? `@everyone`
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? In the MD
3. Done what to cause the error? Write a message in the MD, get the confirmation message and react to the emoji of `confirm_thread_creation_deny`
4. Any recently made changes to your bot? No
5. Errored

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.
https://hasteb.in/forofusa

**Comment by mickykuna** [comment]
Adding on to this issue. On my side, `confirm_thread_creation_deny` works with the default ❌, but opens a thread anyway with a custom emoji.
