### ISSUE TITLE
Annotation enhancement suggestions.

### ISSUE THREAD

**Issue by Xithrius** [kyb3r/modmail#2922]
Greetings, I have a couple questions about type annotations throughout the bot.

Why doesn't [this function here](https://github.com/kyb3r/modmail/blob/master/core/config.py#L229-L231) not have any return annotation such as `None`, when a [function](https://github.com/kyb3r/modmail/blob/master/core/config.py#L244-L245) a few lines away does?

Do y'all think it would be useful to put the argument and return annotation for [these functions](https://github.com/kyb3r/modmail/blob/master/core/config.py#L405-L424) into a constant somewhere at the top of the file?

What I'm suggesting here is something similar to this:
```py
DICT = typing.Dict[str, typing.Any]  # Probably not the best name, feel free to suggest others.
```
Then at the bottom of the file, located [here](https://github.com/kyb3r/modmail/blob/master/core/config.py#L405-L424):
```py 
    @classmethod
    def filter_valid(cls, data: DICT) -> DICT:
        return {
            k.lower(): v
            for k, v in data.items()
            if k.lower() in cls.public_keys or k.lower() in cls.private_keys
        }

    @classmethod
    def filter_default(cls, data: DICT) -> DICT:
        # TODO: use .get to prevent errors
        filtered = {}
        for k, v in data.items():
            default = cls.defaults.get(k.lower(), Default)
            if default is Default:
                logger.error("Unexpected configuration detected: %s.", k)
                continue
            if v != default:
                filtered[k.lower()] = v
        return filtered
```

I can understand why there's no return annotation in [this dunder method](https://github.com/kyb3r/modmail/blob/master/core/config.py#L188-L192), since it's fairly obvious what it returns.

I am completely willing to create/modify these annotations and more throughout the project if need be.

Thank you for any and all feedback.

**Comment by fourjr** [comment]
I think the latest few versions have slowly added a bunch of type annotations
