### ISSUE TITLE
Videos fail to send

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#2926]
**Describe the bug**
Videos are unable to send in either dm and in a thread.

**Bot Info**
Bot version (check with `@modmail about`): 3.7.13 / 3.8.0dev7
Host method (Heroku, self-host, etc): vps

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? Anyone
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? in dms and in the thread channel
3. Done what to cause the error? Send a video
4. Any recently made changes to your bot? No recent changes
5. Errored

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here. https://hastebin.cc/ruvewaqasa
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
in dm: https://cdn.discordapp.com/attachments/770408630788816917/795364717542637568/b40476b15eba9944.png

In thread channel: https://cdn.discordapp.com/attachments/770408630788816917/795364938583375912/unknown.png

**Additional context**

**Comment by fourjr** [comment]
This issue applies to all non-image files as well and is fixed in v3.8
