### ISSUE TITLE
Add confirmation before opening a new thread in react to contact

### ISSUE THREAD

**Issue by ririko5834** [kyb3r/modmail#2930]
Can you please add confirmation before opening a new thread also when someone react to react to open new thread panel?
Sometimes users reacted to reaction panel by mistake and dont need to open thread.

**Comment by fourjr** [comment]
Use the `confirm_thread_creation` config

**Comment by wolfier74** [comment]
@fourjr Hello, ik how to add confirmation.
But when i have confirmation seted and someone open thread from react to contact panel, the confirmation is bypassed.
Can you add that when user react to the panel, dm message with confirmation will be also sent?

Often users just react to panel by mistake and open useless thread.
