### ISSUE TITLE
[BUG] ?logs with no arguments not working in modmail thread in separate server

### ISSUE THREAD

**Issue by PaeP3nguin** [kyb3r/modmail#2935]
**Describe the bug**
`?logs` used to list the user's logs when run without arguments in a modmail thread. It no longer works after upgrading from 3.6.2 to 3.8.1. We're using a separate server setup, no idea if this reproduces for single-server setup, sorry.

From the release notes, this may have been introduced in 3.7.8, where `?logs` <id> was fixed for separate server setups.

**Bot Info**
Bot version (check with `@modmail about`): **3.8.1**
Host method (Heroku, self-host, etc): **self-host**

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? **Anyone who can run ?logs**
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? **In a modmail thread channel**
3. Done what to cause the error? **Run ?logs**
4. Any recently made changes to your bot? **Upgraded from 3.6.2 to 3.8.1**

**Error Logs**
[https://hastebin.cc/zajaherara.apache](https://hastebin.cc/zajaherara.apache)

**Screenshots**
N/A

**Additional context**
On 3.6.2 with separate server setup, `?logs` with no arguments worked in modmail threads but `?logs <id>` didn't work in the modmail server. Now, it's the opposite.

**Comment by Jerrie-Aries** [comment]
I couldn't reproduce it either using single or multiple server setup. Is there any chance the recipient no longer shares any servers with the bot (e.g already left after opening the thread), and you restarted the bot after that?

**Comment by PaeP3nguin** [comment]
I think you're right! Though I didn't see a leave message. Seems to work well in other threads.

**Comment by Jerrie-Aries** [comment]
That seemed to be the case. Maybe we can fix it tho.

**Comment by Jerrie-Aries** [comment]
On similar situation (the recipient is not cached I guess), I got this error when the recipient reacts to reactions in DM channel.

The error as shown below:
```py
2021-01-11 03:15:48 __main__[1402] - ERROR: Ignoring exception in on_raw_reaction_remove.
2021-01-11 03:15:48 __main__[1403] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 1223, in on_raw_reaction_remove
    await self.handle_reaction_events(payload)
  File "bot.py", line 1156, in handle_reaction_events
    if user.bot:
AttributeError: 'NoneType' object has no attribute 'bot'
```
