### ISSUE TITLE
[BUG] Reaction thread creation issue

### ISSUE THREAD

**Issue by MinerMends** [kyb3r/modmail#2938]
**Describe the bug**
When you have the reaction feature enabled where they have to confirm the reaction, they get the options of yes/no (check mark/exmark), if they hit the exmark it still creates the ticket, even though it should cancel it. Alternatively users need to use timeout as a way to stop it.

**Bot Info**
Bot version: Latest
Host method: Heroku

**To Reproduce**
1. Enabled react to create thread (in dm) not react to contact.
2. DM the bot, click the cancel emoji (for me I have it set to a exmark), then the bot will still create the ticket.

**Error Logs**
No errors, it's as if the bot just thinks it's normal lol.

**Comment by Jerrie-Aries** [comment]
Similar with issue #2916.

Plus, devs already fixed this in v3.8.0

Are you sure your bot is latest version?

**Comment by fourjr** [comment]
>  Bot version: Latest
Could you be more specific and show us which version it is in `?about`?

**Comment by fourjr** [comment]
Closed due to inactivity.
