### ISSUE TITLE
[BUG] Not Connecting With Mongo

### ISSUE THREAD

**Issue by LokeshSen002** [kyb3r/modmail#2939]
**PYMONGO is Not Connecting With MONGODB**
In Self-Host
**Bot Info**
Bot version (3.8.2)
Host method (self-host)

**Error Logs**
01/16/21 19:05:56 core.clients[380] - CRITICAL: Your MongoDB CONNECTION_URI might be copied wrong, try re-copying from the source again. Otherwise noted in the following message:

**Screenshots**
https://cdn.discordapp.com/attachments/725294475391533068/799996123385036810/unknown.png
Check This Image

**Comment by lorenzo132** [comment]
This is not a bug, this is a issue from your side.

Remove `<password>` and replace it with the actual password for the database user. Also remove everything past `<dbname>`, but keeping the `/`

It should look like this afterwards:
`mongodb+srv://Papiersnipper:mypassword123@modmail-rdm99.mongodb.net/`

https://i.imgur.com/lxtzDOz.png

**Comment by lorenzo132** [comment]
Possible MongoDB Auth Fails: 

1. IP not whitelisted (`0.0.0.0/0`)
2. Didn't edit the `<PASSWORD>`
3. Wrong username/passsword
4. Whitespace in username/password
5. Other weird characters in username/password
6. Accidentally entered a space in the heroku config variable
7. Simply not a valid URI schema
8. Didn't remove `<` or `>`

Please check If you have done something of the above ^ @LokeshSen002

**Comment by LokeshSen002** [comment]
See Its My MongoDB URI
mongodb+srv://noob:noob@ratioofficialmodmail.yp1dy.mongodb.net/
But You Write In Upper That After clustername remove "." add "-" After That
My MongoDB URI 
mongodb+srv://noob:noob@ratioofficialmodmail-yp1dy.mongodb.net/

So Please Check It With MongoDB Compass Its Connect Successfully

**Comment by fourjr** [comment]
Do not post your mongo uri publicly.
