### ISSUE TITLE
Random embed color

### ISSUE THREAD

**Issue by MrGameMemo** [kyb3r/modmail#295]
### Hi
I would like to ask you if you could add random option for the RichEmbed color.

I know it works with D.js but never did this with py.

*Thanks in advance*

__Mr Game__

**Comment by StephenDaDev** [comment]
This is not currently possible as of ``v2.24.1``. Leave this open as a feature request for the Developers. (Maybe this will be a plugin)

**Comment by fourjr** [comment]
I assume this is to change the main color of the bot. If so, you cannot make this a plugin.

**Comment by StephenDaDev** [comment]
Ok, great to know.

**Comment by MrGameMemo** [comment]
How come it works with Discord.js and you just can't do it in Python ?

**Comment by fourjr** [comment]
We can do it in python.

**Comment by StephenDaDev** [comment]
He said it CAN NOT be a plugin but it CAN be added in

**Comment by MrGameMemo** [comment]
So, do you plan adding it to ModMail ?

**Comment by fourjr** [comment]
Can you be patient? We have 35 currently open issues, and 35 currently unsolved feature requests. We have our own lives too and would appreciate for you not to be so demanding.

**Comment by MrGameMemo** [comment]
Of course. :-)
 

Envoyé: dimanche 23 juin 2019 à 06:44
De: "Jia Rong Yee" <notifications@github.com>
À: kyb3r/modmail <modmail@noreply.github.com>
Cc: "Mr Game Pro" <mrgamepro@gmx.fr>, Author <author@noreply.github.com>
Objet: Re: [kyb3r/modmail] Random embed color (#295)


Can you be patient? We have 35 currently open issues, and 35 currently unsolved feature requests. We have our own lives too and would appreciate for you not to be so demanding.

**Comment by Taaku18** [comment]
This is an extremely niche feature request. I will be closing this now as it's not worth the collective efforts to implement this into Modmail. 

However, if in the future a great number of people want this as a core feature of Modmail, we can reopen this issue. For now, you may make a suggestion to our [Plugins Server](https://discord.gg/fvSEamh) as it is possible to "monkey-patch" this feature from a plugin.
