### ISSUE TITLE
[BUG] Small formatting error on ?config help confirm_thread_creation command

### ISSUE THREAD

**Issue by martinbndr** [kyb3r/modmail#2950]
**Describe the bug**

**Bot Info**
Bot version (check with `@modmail about`): 3.8.2
Host method: self-host

**To Reproduce**
Running the ?config help confirm_thread_creation  command to get moe help on this config setting

**Error Logs**
No error, its just a small formatting error - see attached image below in screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/55140357/106298022-aaa9e280-6253-11eb-9482-b6223027daff.png)

**Additional context**

**Comment by F-C0DE** [comment]
### In `core/config_help.json`

**Typo in Line 709:**

> "See also: `confirm_thread_creation_title`, `confirm_thread_response`, `confirm_thread_creation_accept`, `confirm_thread_creation_deny``"

At the end of the line there are two " ` ". Just delete one. :)

Edited:

> "See also: `confirm_thread_creation_title`, `confirm_thread_response`, `confirm_thread_creation_accept`, `confirm_thread_creation_deny`"

**Comment by fourjr** [comment]
Resolved
