### ISSUE TITLE
every time someone updates the bot it sends "Bot has been updated and is logging out." 

### ISSUE THREAD

**Issue by wowyourbad** [kyb3r/modmail#2952]
and when I try to start it again it just sends the same thing and then logs out again (this is on repl.it)

**Comment by 21Z** [comment]
repl.it is not supported for updating the bot. so you will have to disable auto updates by adding:
`DISABLE_AUTOUPDATES=1` in the `.env` file

**Comment by wowyourbad** [comment]
oh that means if I ever want to update it ill have to clone it again?

**Comment by wowyourbad** [comment]
> DISABLE_AUTOUPDATES=1

does it matter what line?

**Comment by 21Z** [comment]
> > DISABLE_AUTOUPDATES=1
> 
> does it matter what line?

no

**Comment by 21Z** [comment]
> oh that means if I ever want to update it ill have to clone it again?

yes

**Comment by wowyourbad** [comment]
yea it works thanks
