### ISSUE TITLE
[BUG] thread_close_response doesn't seem to work correctly

### ISSUE THREAD

**Issue by DylsterDev** [kyb3r/modmail#2956]
**Describe the bug**
When one runs `?config set thread_close_response <message>` and then closes a thread the response set does not appear in the closed embed.

**Bot Info**
Bot version: 3.8.4
Host Method: Local

**To Reproduce**
1. Set the message using the config set command
2. Create a thread
3. Close the thread
4. Go to DMs
5. Observe

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

https://hastebin.cc/igorexogor

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Jerrie-Aries** [comment]
It's working actually.
By any chance, did you close your own modmail thread?

If so, the bot would use another config variable which is `thread_self_close_response`. This if the closer is the same user as the recipient.

You can refer to the code here:
https://github.com/kyb3r/modmail/blob/7b2e63d1dac132162dc4a9e4c9c62dcc604b839a/core/thread.py#L477-L481
