### ISSUE TITLE
Be able to make all messages sent and received through plain messages (non embeds)

### ISSUE THREAD

**Issue by vNziie** [kyb3r/modmail#2958]
I thought this could be a useful thing if people dont like using the embeds. Becuase right now, you cant copy and paste text in embeds on IOS. This gets really annoying. If you could make this, this could be a config option and removes the embed footer message when in plain messages (like using `?preply`, it sends the footer message which makes the message long). 

Please and thank you.

**Comment by fourjr** [comment]
Why not use an alias? `?alias add r preply`

**Comment by fourjr** [comment]
Closed due to inactivity
