### ISSUE TITLE
[BUG] setting mention will show differently when set with markdown

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#2962]
**Describe the bug**
When setting a multiword mention by doing > ?config set mention word1 `darkword` < the  "darkword" will show as normal word when doing `?config get` 

**Bot Info**
Bot version (check with `@modmail about`): 3.8.4
Host method (Heroku, self-host, etc):Selfhost on vps

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? anyone with perms to change the mention config
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? Anywhere where the bots config can be changed
3. Done what to cause the error?      > ?config set mention word1 `word2`  <
4. Any recently made changes to your bot? No recent changes were made
5. Errored

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.  https://hastebin.cc/onujubicaf ( no errors in the logs )
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots** ( Video )
Tutorial how to produce the bug: https://i.discord.gold/m9ZAED.mp4
The `?config get` command: https://i.discord.gold/ZHOzPQ

**Comment by fourjr** [comment]
Won't fix. This is the nature of discord markdown and there is no workaround for it. Since there is no functionality that is affected, this is a wont fix issue.
