### ISSUE TITLE
mongodb not connecting

### ISSUE THREAD

**Issue by TizoCraft** [kyb3r/modmail#2967]
if i run `python3 bot.py` this error comes up:
 `pi@raspberrypi:~/Desktop/modmail-master $ python3 bot.py
03/08/21 17:16:23 __main__[145] - INFO: -------------------------
03/08/21 17:16:23 __main__[153] - INFO: Logging level: INFO
03/08/21 17:16:23 __main__[155] - INFO: Log file: /home/pi/Desktop/modmail-master/temp/NzQyODI1MDI4MDA1MTM0NDY3.log
03/08/21 17:16:23 __main__[114] - INFO: -------------------------
03/08/21 17:16:23 __main__[116] - INFO: ┌┬┐┌─┐┌┬┐┌┬┐┌─┐┬┬
03/08/21 17:16:23 __main__[117] - INFO: ││││ │ │││││├─┤││
03/08/21 17:16:23 __main__[118] - INFO: ┴ ┴└─┘─┴┘┴ ┴┴ ┴┴┴─┘
03/08/21 17:16:23 __main__[121] - INFO: v3.8.5
03/08/21 17:16:23 __main__[122] - INFO: Authors: kyb3r, fourjr, Taaku18
03/08/21 17:16:23 __main__[123] - INFO: -------------------------
03/08/21 17:16:23 __main__[124] - INFO: discord.py: v1.6.0
03/08/21 17:16:23 __main__[125] - INFO: -------------------------
03/08/21 17:16:24 core.clients[380] - CRITICAL: Your MongoDB CONNECTION_URI might be copied wrong, try re-copying from the source again. Otherwise noted in the following message:
03/08/21 17:16:24 __main__[220] - ERROR:  - Shutting down bot - 
`

this is my .env file (i changed the password/token to random shit):
`TOKEN=HJIGugudhNDY3.XzLdJukzutfdh-sg.dhmdNIdEfAnZ2nUhdfhfdhfdhfd
LOG_URL=https://log-viewer-modmail-123.herokuapp.com/
GUILD_ID=659822436912726046
MODMAIL_GUILD_ID=659822436912726046
OWNERS=310844659821707264
CONNECTION_URI=mongodb+srv://userbot:UfgthTfzKIgzgU@modmail.uarih.mongodb.net/`

im trying to install the bot on a raspberry pi 4 modell b with Python 3.9.2
hope someone can help me

**Comment by fourjr** [comment]
Please ask for setup-related help on our [discord server](https://discord.gg/etJNHCQ).
