### ISSUE TITLE
[THREAD CREATED CONFIRMATION DOES NOT WORK] Hello good! When I do the commands to activate the confirmation of the created thread, I send a message to the BOT and said bot does not put the emojis to confirm the creation of the thread

### ISSUE THREAD

**Issue by Momazodayxdd** [kyb3r/modmail#2968]
**Describe the bug**

**Bot Info**
Bot version (check with `@modmail about`): 
Host method (Heroku, self-host, etc):

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)?
2. Where can it be reproduced (ex. in thread channels, recipient DM's)?
3. Done what to cause the error?
4. Any recently made changes to your bot?
5. Errored

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by fourjr** [comment]
What is the exact command you gave to the bot?

**Comment by fourjr** [comment]
Closed due to inactivity
