### ISSUE TITLE
[BUG] disable command doesnt disable react to contact

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#2969]
**Describe the bug**
Using the disable command does not affect react to contact threads

**Bot Info**
Bot version (check with `@modmail about`): v3.8.5
Host method (Heroku, self-host, etc): selfhost (doesnt matter)

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)?
2. Where can it be reproduced (ex. in thread channels, recipient DM's)?
3. Done what to cause the error?
4. Any recently made changes to your bot?
5. Errored

- run `?disable new`
- try creating thread by dming bot (works correctly)
- try using react to contact (works but shld be disabled)

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

Possible solution could be additional granularity to the disable command to prevent breaking current functionality

**Comment by fourjr** [comment]
The initial bug part of this has been resolved. However, the PR will remain open as a feature request for additional granularity to the `?disable` command.

**Comment by coleslaw12** [comment]
Im unsure if this falls in the same category, but the `?block` command doesnt disable react_to_contact either.

**Comment by martinbndr** [comment]
Yes for me too. Users still can open tickets through the reaction even they are blocked. @fourjr Maybe you need to look at this and fix it.

**Comment by Jerrie-Aries** [comment]
> Im unsure if this falls in the same category, but the `?block` command doesnt disable react_to_contact either.

> Yes for me too. Users still can open tickets through the reaction even they are blocked. **fourjr** Maybe you need to look at this and fix it.

I'm going to try and look into these.

**Comment by fourjr** [comment]
Issue resolved
