### ISSUE TITLE
Mobile Raw Snippet Feature

### ISSUE THREAD

**Issue by cutofmeat** [kyb3r/modmail#2975]
**Is your feature request related to a problem? Please describe.**
Yes, mainly for those using this program on mobile.

**Describe the solution you'd like**
I would like to propose a new command that enables the ability for mobile users to copy raw snippets. Instead of sending the raw snippet in an embed, it would be sent as text for mobile users to be able to copy. 

Would be best if the command were something like `!mobraw` or `!mraw`

**Describe alternatives you've considered**
I would usually solve this by asking someone on a computer to send the snippet text over.

**Who will this benefit**
Mobile users would be favored with this feature.

**Additional context**
—

**Comment by StephenDaDev** [comment]
**Note:** This feature already exists as a plugin made by @matrix2113 and is located in [matrix2113/modmail-plugins](https://www.github.com/matrix2113/modmail-plugins/) under the title "Raw".
