### ISSUE TITLE
Running on Replit.com [COMPATIBILITY]

### ISSUE THREAD

**Issue by inyourface34456** [kyb3r/modmail#2979]
Is it possible to run this on replit.com?  I know that it is not compatible at the moment, but it would be nice if you were to add all of the necessary modules and imports.

**Comment by lorenzo132** [comment]
Hey, we do not support hosting using repl.it and we also are not planning on doing this in the future. as of that we will not provide support for repl.it hosting

**Comment by TheLimifiedLime** [comment]
Hey, I managed to get the bot running on repl.it and it seems to be working fine. It involved adding a flask server and a little bash script to install pipenv and dependencies (for some reason dependencies seemed to get wiped after a reboot). I managed to do this with minimal python knowledge so I may have left something out by accident. I can link the repl if you'd like to look at it.

**Comment by inyourface34456** [comment]
@TheLimifiedLimecan  you give me the repl link?

**Comment by TheLimifiedLime** [comment]
Link:
https://replit.com/@TheLimifiedLime/modmail

**Comment by inyourface34456** [comment]
@TheLimifiedLime thanks
