### ISSUE TITLE
Thread cooldown

### ISSUE THREAD

**Issue by Forcellrus** [kyb3r/modmail#298]
Add a functionality that allows us to set a cooldown timer, before users are able to open another thread for a certain period of time after closure. For example, users open a thread, we deal with them, close the thread and they message us again, opening a new thread and pinging staff just to write "ty". It's becoming really annoying and we think that adding an option to set a 15 min (configurable time) cooldown between closing and creating a new thread would be of great help. It would also really help with spammers.

**Comment by StephenDaDev** [comment]
Good Feature

**Comment by StephenDaDev** [comment]
This is important, it helps with anti-raid and anti-accidental-creation.

**Comment by TheKinG2149** [comment]
GitHub Actions uwu

**Comment by StephenDaDev** [comment]
I know, I hate it.

**Comment by groovybluedog** [comment]
This really couldn't come sooner!

**Comment by officialpiyush** [comment]
Don't we have thread cooldown's now?

**Comment by StephenDaDev** [comment]
Implemented!

**Comment by RealCyGuy** [comment]
should be closed then

**Comment by StephenDaDev** [comment]
@Taaku18 Apparently I never tagged you on this one

**Comment by RealCyGuy** [comment]
*gasp*
