### ISSUE TITLE
Warning: removes relevant characters from usernames in the channel list

### ISSUE THREAD

**Issue by F8ER** [kyb3r/modmail#2982]
Dear Developers,

Thank you for the project.

**A warning just to highlight the issue.**

Due to Discord channel name formation procedure limitations, it appears only few characters are allowed in the channel name(username based), hence the function `format_channel_name`.

The line: https://github.com/antigravities/modmail/blob/3f2b9a5b0a4180ec574325d364770bbbbad4ddf4/core/utils.py#L349
```python
# ...
name = new_name = (
    "".join(l for l in name if l not in string.punctuation and l.isprintable()) or "null"
) + f"-{author.discriminator}"
# ...
```

For example, my username starts with `/\ngel#????` which appears `ngel-????` in the channel list:

<img src="https://i.imgur.com/4Qiigls.png" width="200" />

As the result, this may cause different users like `ngel#????` or `^ngel#????` and actual me(`/\ngel#????`) appear in the channel like `ngel-????` and `ngel-????_1` and confuse a moderator. **This may lead to an accidental private data leak.**

Best and kind regards ✨

**Comment by fourjr** [comment]
How do you suggest we tackle this issue?

**Comment by F8ER** [comment]
> How do you suggest we tackle this issue?

For example, a time(i.e. UTC zoned) of the issue reported and some non-general Unicode characters:

```python
from datetime import datetime

# ...

def format_channel_name(author, guild, exclude_channel=None, force_null=False):
    channel_name = ""

    if force_null:
        channel_name = "null"

    channel_name = channel_name_new = (
        datetime.utcnow().strftime('%Hː%Mː%S｜%m-%d-%Y')
    ) + f"-{author.discriminator}"
    
    counter = 1
    existed = set(c.name for c in guild.text_channels if c != exclude_channel)

    while channel_name_new in existed:
        channel_name_new = f"{channel_name}｜{counter}"  # multiple channels with same name
        counter += 1

    return channel_name_new
```

A possible view:

<img src="https://user-images.githubusercontent.com/25136754/112512986-91796a00-8d9c-11eb-8777-1b11050d0886.png" />

As you might notice, the last channel on above preview is the widest possible(assumed 9 reports at the same second) and more than 9 reports at the same second should result in a text overflow, hence trimmed channel name, but what's the probability of such phenomenon? Also, different separators could be used, of course, or even minimal like `181136_03252021` and `＃`(`U+FF03`) character for a counter etc.

Imagine, what if Discord have used a monospace font for channel names and allowed resizing the panel ^^

**Comment by F8ER** [comment]
Updated the datetime format

**Comment by fourjr** [comment]
Suggestion: More ways to customise channel names

For now, you can try out a config option recently added `use_user_id_channel_name`.

**Comment by fourjr** [comment]
`use_timestamp_channel_name` is added in v3.10.0-dev6. Channels are formatted according to YYYY-MM-DD-HHMM

**Comment by fourjr** [comment]
`Bot.format_channel_name(bot, author, exclude_channel=None, force_null=False):` can now be extended by plugins in v3.10.0-dev7
