### ISSUE TITLE
[BUG] bug report title here

### ISSUE THREAD

**Issue by Kathou99** [kyb3r/modmail#2999]
**Describe the bug**
Bot don't start the command prop open and close
**Bot Info**
Bot version (check with `@modmail about`): last bersion up to date
Host method (Heroku, self-host, etc):self-host window 10 server

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? anyone
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? no
3. Done what to cause the error? nothing
4. Any recently made changes to your bot? no
5. Errored 

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.[ODE4MDg5NDAwMjE0NjE4MTMy.log](https://github.com/kyb3r/modmail/files/6292924/ODE4MDg5NDAwMjE0NjE4MTMy.log)
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com  https://quebeclogs.herokuapp.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png) The command prop open an close pretty fast
3. Reproduce the error to populate the error logs 
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
Add screenshots to help explain your problem. no screen shot the only thing I had is the logs

**Additional context**

I had close my bot to restart my dedicated vps but the modmail bot don't have restart so I had go look up the logs and it's seem is the problem.

**Comment by Kathou99** [comment]
![Screenshot_20210411-190111_Video Player](https://user-images.githubusercontent.com/71993497/114324519-82165280-9af8-11eb-8105-df6c5fbff644.jpg)
Here the screen shot before it's close

**Comment by StephenDaDev** [comment]
Update the bot. Join the support server for further assistance.

**Comment by jaed0n** [comment]
I'm getting the same issue, have to reinstall discord.py 1.6.0 using pipenv everytime to run the bot so can't use pm2 to autostart.

**Comment by chasejkal2004** [comment]
Join the discord (https://discord.gg/MtF3Gk5kpr). Create a Modmail and the staff will help you further support.
