### ISSUE TITLE
[suggestion]Change how embeds looks

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#300]
currently modmail bot creates a embed in first message containing recipient info. 

some owners may dislike how the embed looks so let us freely adjust how each embed can look like. 

Example remove/reposition recipient roles, avatar, join age info, user id, timestamp. 

Present an easy way to adjust the layout of an embed with arguements say
[USERID] [USERROLE] and maybe add some plugin event listener so third party dev can expand further of the layout complexit with more arguements

**Comment by fourjr** [comment]
I'd suggest using https://leovoel.github.io/embed-visualizer/ and extracting embed data from it with `Embed.from_dict` and `{brace-style-variables}` similar to [welcomer](https://github.com/fourjr/modmail-plugins/tree/master/welcomer).

**Comment by StephenDaDev** [comment]
@Taaku18 What the fuck did you do
