### ISSUE TITLE
[BUG] Fallback Channel Method Bugs

### ISSUE THREAD

**Issue by Coolguy3289** [kyb3r/modmail#3002]
**Describe the bug**
Categories usually have a max channel limit of 50, this is checked in thread.py however there is a bug in the Discord API where a category having 49 channels is returning "Category has reached the maximum number of channels" causing the thread creation to fail since the check to trigger the fallback category functionality is contingent on the category having 50 channels.

**Bot Info**
Bot version (check with `@modmail about`): 3.9.3
Host method (Heroku, self-host, etc): Self-Host 

**Error Logs**
http://haste.thegamingcorner.net/imelisejom.sql
After some extra Debug Logging
http://haste.thegamingcorner.net/igelukovez.sql

**Comment by Coolguy3289** [comment]
After making the change, I'm now seeing this issue:
![image](https://user-images.githubusercontent.com/12205727/115413747-6f201400-a1c3-11eb-92c5-022b1a169865.png)

**Comment by Jerrie-Aries** [comment]
That's kinda weird. It's like the bot didn't save the new 'fallback_category_id' or something.

**Comment by Coolguy3289** [comment]
Well it did, and it used that category, but once it was filled up, it didn't migrate/update the config for the new one. Rather, it did, created the new thread and seems to have just dumped it for the old value. I've tried removing the config value and it's doing the same thing.
