### ISSUE TITLE
Allow more modmails on one server

### ISSUE THREAD

**Issue by NoodlesDev987** [kyb3r/modmail#3025]
Hi, can you add something to allow more modmail instances on one server? 
Maybe there should be added thread prefix config option (channels should be named prefix-username-tag).

**Comment by onerandomusername** [comment]
Hi, I've added this to an [unofficial instance](https://github.com/onerandomusername/modmail/tree/add-multiple-bot-per-guild-support) at the moment. If you're up to the task I can help you set it up.

Just set it up like normal and put `MULTI_BOT ="True"` in your `.env` file.

**Comment by fourjr** [comment]
@onerandomusername, this is not the place to advertise your other modmail bot.

**Comment by fourjr** [comment]
What is the usecase for this feature? Who will it benefit? Would a plugin like `menu` solve the same problem?

**Comment by NoodlesDev987** [comment]
The menu plugin is not working together with react_to_contact panel, maybe there should be plugin react_menu that the reactions to choose department will be on the react to contact panel. Or after opening thread using the panel just dm the user the reactions like on normal thread opened by dming the bot

**Comment by fourjr** [comment]
This is out of scope and unsupported by modmail. Create a plugin instead
