### ISSUE TITLE
[Suggestion] Add an alert on Category filled

### ISSUE THREAD

**Issue by Coolguy3289** [kyb3r/modmail#303]
The discord limitation of 50 channels per category is well known. I am proposing a chat alert in the logging channel to state that the limit has been hit so the moderators of a server can take proper action to keep tickets flowing, otherwise checking the logs manually is the only way to know what has happened.

**Comment by maidos** [comment]
we need a contingency plan for this because most of us rarely check logs. So we have no way of knowing when we reach 50 channels. Sometimes the recipient arent even aware that the bot couldnt create a thread and assume it was created.

Im suggesting that the bot creates a temporary category once the original category reach 50 channels. And when the original category have fewer than 50 channels, the channels in the temporary category get auto moved to the original category and 2nd category gets deleted

**Comment by Coolguy3289** [comment]
Honestly that feature would be *very* helpful, better than manually dragging channels to an overflow category. I may see about making the changes myself depending on the proposed timeline for release

**Comment by StephenDaDev** [comment]
> most of us rarely check logs

In most larger servers I'm in almost all of the staff mute the log channel. If you absolutely had to keep this concept and couldn't change maybe make it do a mention such as `overflow-mention` also if you would do that maybe make a config var `overflow-warning-channel` so you could send it to Staff Announcements or somewhere staff do actually look

**Comment by Coolguy3289** [comment]
Like I said, the suggested addition of auto creating overflow categories and using that for new tickets to prevent the tickets from being created would be helpful and imo future proofing

**Comment by Taaku18** [comment]
@DAzVise Is working on this.

**Comment by StephenDaDev** [comment]
#636

**Comment by groovybluedog** [comment]
Great to see this is coming, I also support the idea of the bot creating a secondary category and putting threads back in to the main one and then deleting itself when space becomes available.

**Comment by StephenDaDev** [comment]
Overflow category was implemented! View the config help below:
---
Default:
``Fallback Modmail`` (created when the main category is full)

Information:
This is the category that will hold the threads when the main category is full.

To change the Fallback category, you will need to find the category’s ID.

Example(s):
- ``?config set fallback_category_id 9234932582312`` (9234932582312 is the category ID)
Note(s):
- If the Fallback category ended up being non-existent/invalid, Modmail will create a new one. To fix this, set ``fallback_category_id`` to a valid category.
- See also: ``main_category_id``.
---
@Taaku18 *implemented*
