### ISSUE TITLE
thread_auto_close timer starts after user replied or after note is added

### ISSUE THREAD

**Issue by Flybel** [kyb3r/modmail#3030]
In the [config wiki](https://github.com/kyb3r/modmail/wiki/Config), thread_auto_close is described as:

> Time that has to pass after no reply **from a user** before the thread auto closes. If not set, thread will not auto close.

However, this seems misleading as the timer begins whenever a message is sent in a thread by anyone or when a note is added. This also produces undesirable behaviour. Examples:

- A user contacts ModMail to request assistance. The ticket will be closed even if no reply is given at all.
- A staff member replies and issues a `?close cancel` to put the issue on hold. While staff member is unavailable, the user replies with additional info, which resets the timer and the ticket is closed before staff member gets back.
- A staff member issues a `?close cancel` and then a `?note`. The timer is restarted and the ticket is closed.

Possible changes for this can be to completely disable the timer for anything other than a `?reply` being issued by a staff member, or to add a second timer configuration for `?reply` versus messages sent by the user in DMs. The `?note` command should not be considered for this in both cases.

**Comment by fourjr** [comment]
This issue will be resolved in v3.10.0-dev5

Changes:
- Notes no longer restart the timer.
- The timer only restarts when the reply is sent "from mod".
