### ISSUE TITLE
Delete command after successful execution.

### ISSUE THREAD

**Issue by kimotoaoi** [kyb3r/modmail#3033]
Can you add a function that deletes the command after it executes successfully?

**Comment by StephenDaDev** [comment]
What command?

**Comment by onerandomusername** [comment]
Which commands are you talking about? Most of them already delete their selves after being invoked

**Comment by kimotoaoi** [comment]
> Which commands are you talking about? Most of them already delete their selves after being invoked

My personal bot doesn't automatically delete?

**Comment by lorenzo132** [comment]
Got any logs for us + a screenshot of the commands your running?
( `?debug hastebin` )

**Comment by kimotoaoi** [comment]
> Got any logs for us + a screenshot of the commands your running?
> ( `?debug hastebin` )

https://hastebin.cc/ojudisokum
![IMG_20210519_231240](https://user-images.githubusercontent.com/55420858/118847604-1940a800-b8f8-11eb-88ee-0cc148dea1ff.jpg)

**Comment by lorenzo132** [comment]
commands like about/help etc wont be deleted, this would only be with commands like reply.
