### ISSUE TITLE
[BUG] Internal discord reconnecting can cause memory to spike while reloading every thread

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3037]
**Describe the bug**

**Bot Info**
Bot version (check with `@modmail about`): 3.9.4
Host method (Heroku, self-host, etc): VPS

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? hoster
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? Hosting device
3. Done what to cause the error? start the bot and watch
4. Any recently made changes to your bot? no changes were made
5. Errored

**Screenshots**
https://usagi.移动/OM4pCN

**Comment by fourjr** [comment]
Resolved in v3.10.0-dev5
