### ISSUE TITLE
[BUG] `send_recipient_genesis_message` only sends message if the creator is also the recipient

### ISSUE THREAD

**Issue by conniey** [kyb3r/modmail#3038]
**Describe the bug**

I could be understanding the feature incorrectly, but the documentation for `send_recipient_genesis_message` says: "Once thread is ready, tell the recipient." (https://github.com/kyb3r/modmail/blob/master/core/thread.py#L184)

* However, the bot only sends you a message if you are the one invoking the command. Is this expected behaviour?
    * Here's the line of code: https://github.com/kyb3r/modmail/blob/master/core/thread.py#L203-204

** Aside**
* Is there a way to disable `send_recipient_genesis_message`? It doesn't appear to be supported.

**Bot Info**
Bot version: Pulled from `master`.
Host method (Heroku, self-host, etc): selfhost

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute: `{prefix}contact <your-user-id>`

**Expected**
Based on the documentation, I would expect it to DM the recipient if they are _not_ the invoker of that command.

**Comment by fourjr** [comment]
Intended behaviour. Commands such as `?contact` that cause the other behaviour to happen have their own genesis message sending.

Documentation updated to reflect this.
