### ISSUE TITLE
Perms Override for Plugins

### ISSUE THREAD

**Issue by KowshikSB** [kyb3r/modmail#3039]
**Describe the Feature you'd like**
A feature that lets us to set perms to use the commands from external plugins i.e A Feature to restrict commands from external plugins to be usable only for a specified role.

**Who will this benefit**
This will benefit in alot of ways. Servers can make some exclusive commands as booster perks or level perks which will enhance the activity of the server! Thats it pretty much. I hope you get what i mean.

**Comment by fourjr** [comment]
Do you mean custom plugins that you make or pre existing plugins?

**Comment by KowshikSB** [comment]
> Do you mean custom plugins that you make or pre existing plugins?

Perms override for pre exisiting plugin like Music. And also it would be good if we can set perms for custom plugins that the "bot owner" make.

**Comment by fourjr** [comment]
This is dependent on how the plugin owner wishes to configure permissions but you can still use Modmail default `?perms override` command
