### ISSUE TITLE
Timer for tickets/threads

### ISSUE THREAD

**Issue by Immusama** [kyb3r/modmail#3046]
**Idea:**
Adding a timer into the description for opened tickets/threads
(Scheduled close and auto close)
-
It would mainly be for auto close so we can easily see when the ticket/thread will be closed.
But also useful if you set a timer for closing yourself.

**Comment by ProHyphonzDaCoder** [comment]
This is already a feature its simple just do [prefix]close 3 minutes

**Comment by Immusama** [comment]
> This is already a feature its simple just do [prefix]close 3 minutes

I meant for the description.

**Comment by ProHyphonzDaCoder** [comment]
What do you exactly mean?

**Comment by ProHyphonzDaCoder** [comment]
Oh you mean like a little timer footer?

**Comment by Immusama** [comment]
> Oh you mean like a little timer footer?

Exactly, so it would show how much time left until it's closing for both ?close time or the autoclose feature

**Comment by ProHyphonzDaCoder** [comment]
> > Oh you mean like a little timer footer?
> 
> Exactly, so it would show how much time left until it's closing for both ?close time or the autoclose feature

Can i join your discord server :))

**Comment by Immusama** [comment]
> > > Oh you mean like a little timer footer?
> > 
> > 
> > Exactly, so it would show how much time left until it's closing for both ?close time or the autoclose feature
> 
> Can i join your discord server :))

It's the Phasmophobia Discord, but why ask here 🤣 ?

**Comment by ProHyphonzDaCoder** [comment]
> > > > Oh you mean like a little timer footer?
> > > 
> > > 
> > > Exactly, so it would show how much time left until it's closing for both ?close time or the autoclose feature
> > 
> > 
> > Can i join your discord server :))
> 
> It's the Phasmophobia Discord, but why ask here 🤣 ?

Invite Link :))))

**Comment by lorenzo132** [comment]
@ProHyphonzDaCoder this is not the place to ask for invites
