### ISSUE TITLE
Addition of a command that only returns the user's snowflake

### ISSUE THREAD

**Issue by dtslubbersen** [kyb3r/modmail#3047]
**Is your feature request related to a problem? Please describe.**
I've always found it tedious to grab a user's snowflake from a mod mail thread. On desktop it's less of an issue than on mobile. On mobile (I use iOS, can't speak for Android) you cannot copy text from the top embed nor from the channel description without opening the channel settings.

**Describe the solution you'd like**
The addition of an `id` command that simply returns the user's snowflake with nothing else so you can copy text and paste the snowflake for your follow up command with your moderation bot.

**Describe alternatives you've considered**
Having a plain text message with just the snowflake but that's an ugly solution.

**Who will this benefit**
All mod mail users but primarily mobile users.

**Comment by donzee529** [comment]
This would be an amazing feature. I 100% agree. I have to scroll to the top of the thread, then I can't copy an embed text from mobile, so I have to copy it down on a paper (starting to type it on the keyboard will scroll back down to the bottom) and then type it on my keyboard. On desktop this is a feature for lazy people, but for mobile this is needed.

**Comment by fourjr** [comment]
Might be out of scope for Modmail, but will leave this open for a bit more as it isn't really that hard to implement into Modmail

**Comment by fourjr** [comment]
`?plugin install matrix2113/modmail-plugins/id`
