### ISSUE TITLE
Use per-server avatars

### ISSUE THREAD

**Issue by DuckMasterAl** [kyb3r/modmail#3048]
**Is your feature request related to a problem? Please describe.**
The bot does not display per-server avatars to users

**Describe the solution you'd like**
The bot displays the per-server avatar for a user if applicable.

**Describe alternatives you've considered**
No alternatives have been considered.

**Who will this benefit**
This feature will apply to a larger group of users once per-server avatars are public, but for now, it doesn't apply to most users.

**Additional context**
<img width="374" alt="Screen Shot 2021-06-19 at 9 58 53 PM" src="https://user-images.githubusercontent.com/43557963/122659830-c1d96600-d149-11eb-9d6e-86335a102ddb.png"> <img width="228" alt="Screen Shot 2021-06-19 at 9 59 15 PM" src="https://user-images.githubusercontent.com/43557963/122659832-c30a9300-d149-11eb-94a9-30a226277fc9.png">
(Username information has been censored)

**Comment by fourjr** [comment]
https://github.com/Rapptz/discord.py/issues/7054

Tagged to #2990
