### ISSUE TITLE
Minor QoL improvement suggestions

### ISSUE THREAD

**Issue by LividJava** [kyb3r/modmail#3051]
**Is your feature request related to a problem? Please describe.**
**A**. When a user has an animated PFP it makes it hard to focus on the actual ticket (Accessibility reasons).
**B**. We use a warning system and reference it internally while using modmail

**Describe the solution you'd like**
For **A**: Like in discord have gifs remain static unless hovered over.
For **B**: In addition to logging moderator conversation, also log Bot messages (unless due to API reasons this is not applicable)

**Describe alternatives you've considered**
**A**. Disabling or out right removing PFPs via an Adblocker, while this does work it is likely to break things (at least in my experience) and is not ideal.
**B**. Can't really think of a good alternative other than switching over to a warning system plugin within Modmail.

**Who will this benefit**
**A**. Benefits moderators who may have conditions where large amounts of movement on their screen either causes sickness or makes it harder to focus.
**B**. Makes it so context remains within the thread, this is very situational and will vary from server to server, but we always check the warnings of a user in a thread.

**Comment by fourjr** [comment]
please create one issue per suggestion
