### ISSUE TITLE
add roles by command to thread channel

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3053]
### Is your feature request related to a problem? Please elaborate.

This request is not related to any issue. 

### Describe the solution you'd like

For example doing `?addrole @Role` will add `@Role` to the thread channel so they can read the channel.

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

manually updating the channel, however this is not always possible as its not a common thing that everyone has manage channels perms

### Who will this benefit?

moderators

**Comment by NoodlesDev987** [comment]
It should be also possible to add single user by mention/id to the channel `?adduser @user/user id`

**Comment by fourjr** [comment]
Staged in v3.10.0-dev4
