### ISSUE TITLE
add the functionality to anon add users to group threads

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3054]
### Is your feature request related to a problem? Please elaborate.

There is no possible way to add users to a thread without remaining private. Think about anonreply etc
( Dev Branch )

### Describe the solution you'd like

Add a config option / command to add users to threads privately.

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

There arent any of now

### Who will this benefit?

Moderators.

**Comment by fourjr** [comment]
one issue per suggestion please

**Comment by fourjr** [comment]
Staged in v3.10.0-dev4

**Comment by fourjr** [comment]
`?adduser <user> [silently]`    
`?removeuser <user> [silently]`

**Comment by fourjr** [comment]
Just realised what this issue actually meant, `anonadduser` and `anonremoveuser` will also be added to dev4 with similar args.
