### ISSUE TITLE
[BUG]: Discord Not Reports Category Full when not at 50 channels

### ISSUE THREAD

**Issue by Coolguy3289** [kyb3r/modmail#3058]
### Bot Version

3.9.4

### How are you hosting Modmail?

PM2

### Error Logs

https://hastebin.com/eparakoruh.yaml

### Additional Information

This is a continuation of a crop up issue already solved by changing the code in the thread.py code on line 1208 to check if the category has 50 channels to 49, however Discord is now reporting the same issue at 48 channels instead now. This issue is to report that bug, and to recommend a dynamic check based on the response from discord rather than a hard check on the number of channels in a category since this is now proved to no longer be reliable by discord.
#3002

**Comment by fourjr** [comment]
Resolved in v3.10.0-dev5
