### ISSUE TITLE
Remove cooldown on title command

### ISSUE THREAD

**Issue by Atharv-Agarwal** [kyb3r/modmail#3059]
### Is your feature request related to a problem? Please elaborate.

The title command has a cooldown of 600 seconds which in my opinion is immensely useless.

### Describe the solution you'd like

Reduce the cooldown to 10 seconds

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

I have tried making another title command and importing it as a plugin but it seems to break the bot.

### Who will this benefit?

Me? I mean you just need to edit 1 line and 1 number really 

### Additional Information

cogs/modmail.py line 676 if I am not wrong, 600 has to be changed to 10

**Comment by lorenzo132** [comment]
This wont be possible due to ratelimits
