### ISSUE TITLE
Plugin Documentation / Proper Guide: Feature Request

### ISSUE THREAD

**Issue by CoalByte** [kyb3r/modmail#3061]
### Is your feature request related to a problem? Please elaborate.

As of now there is a substantial learning curve as far as plugin creation goes, as there is no documentation or guide explaining the functioning and use of database interactions, permissions, etc using the built-in functions the bot provides at it's core.

### Describe the solution you'd like

A clear guide / docs about plugin creation and the use of core / built-in functions.

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

The use of examples and previously created plugins can only go so far to help newcomers understand how to make simple or more complex plugins of their own.

Currently the only available documentation is a tag in the support server (.tag plugin) which is massively incomplete and only provides instructions on creating basic discord.py cogs, uploading them to GitHub and setting them up.

### Who will this benefit?

Mainly plugin developers, but as more complete and complex plugins may be created, It could indirectly benefit bot owners as well.

**Comment by fourjr** [comment]
We have [this Plugins wiki page](https://github.com/kyb3r/modmail/wiki/Plugins). Is it sufficient?

**Comment by fourjr** [comment]
Closed due to inactivity
