### ISSUE TITLE
Claim Feature

### ISSUE THREAD

**Issue by ProHyphonzDaCoder** [kyb3r/modmail#3062]
### Is your feature request related to a problem? Please elaborate.

Whenever a new thread opens up and you start helping the person but then out the blue! ANOTHER Moderator steals your thread and starts helping the person instead of you!. 

### Describe the solution you'd like

If the user did [prefix]claim the bot should change the name of the channel and update all perms for that channel making only you be able to see it excluding admin's and server owners

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

I used ticket tool ig

### Who will this benefit?

Moderators who hate other mod's stealing their conversation

**Comment by CoalByte** [comment]
There are a couple pre-existing plugins for this feature, [here's my personal implementation of it]( https://github.com/CoalByte/modmail-plugins/tree/master/claim) If you'd like to take a look. 

Though, It could be neat If this was provided as a native feature as you suggest 👍

**Comment by fourjr** [comment]
This is out of scope of modmail. You can create a plugin for this feature.
