### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by HyperfireRS** [kyb3r/modmail#3063]
### Is your feature request related to a problem? Please elaborate.

No

### Describe the solution you'd like

Please add the ability for modmail categories. This would allow staff to handle modmail easier.
Idea: When making a thread you have preset options which will then place the new thread in a seperate category on the server such as appeals or reports or general support.

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

This as a plugin. Idk what else to say XD

### Who will this benefit?

Everyone who uses this modmail.

**Comment by fourjr** [comment]
This plugin exists as `menu`. `?plugin add menu`.
