### ISSUE TITLE
add the ability to remove users from groupthreads

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3065]
### Is your feature request related to a problem? Please elaborate.

As of now there is no way to remove users from group threads ( Dev branch ) 

### Describe the solution you'd like

a command where we can remove users from the group threads

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

havent thought of any alternatives.

### Who will this benefit?

both moderators and user

**Comment by fourjr** [comment]
Staged in v3.10.0-dev4
