### ISSUE TITLE
A option to add multiple users at once to a groupthread ( dev branch )

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3066]
### Is your feature request related to a problem? Please elaborate.

This would be usefull incase you want/need multiple users added to a thread. ( To sort of bypass the channel desc ratelimit ) 

### Describe the solution you'd like

add a command like 
`?adduser 12121212121212, 12121212121212, 12121212121212`
`?adduser @user, @user, @user`
this would add all 3 the users

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

couldnt find any working workaround for this.

### Who will this benefit?

both moderators & user

**Comment by CoalByte** [comment]
If a moderator was managing a "group" thread, how would replying work? Would It be like a group DM, sort of messaging every user once a reply is triggered?

**Comment by lorenzo132** [comment]
> If a moderator was managing a "group" thread, how would replying work? Would It be like a group DM, sort of messaging every user once a reply is triggered?

This would be like a groupdm. if the moderator replies all users added will recieve this reply. The same counts if the user replies every would recieve the reply.

**Comment by fourjr** [comment]
Staged in v3.10.0-dev4. `?adduser [users...]`
