### ISSUE TITLE
[SUGGESTION] New variables to configure Modmail. 

### ISSUE THREAD

**Issue by XtoMHA96** [kyb3r/modmail#3072]
### Is your feature request related to a problem? Please elaborate.

No.

### Describe the solution you'd like

Hello, I would like to know if these options are implemented in the BOT, how it would be configured and if not, suggest them.

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

:one: Modify the message when the opening of a ticket by the user is canceled.
:two: Modify the messages that are created for both the moderators and the user when using the `contact` command.
:three: Remove foosters from embeds (message ID, timestamp, anon_tag, mod_tag, ...)
:four: Remove the list of roles in the thread creation message.
:five: Remove the age of the user's account in the creation message of the thread.
:six: Customize the titles of the non-anonymous embeds, which would be the `anon_tag`. For example, **:hammer: Staff | {user}**

![Example](https://i.imgur.com/SKOC42Z.png)

### Who will this benefit?

I am a moderator on non-English speaking servers, and some of these options would help to have the BOT in other languages.

**Comment by StephenDaDev** [comment]
None of that is possible natively.

4&5 - No current way of editing the thread creation message on the staff side

**Comment by fourjr** [comment]
Could you indicate the current versions of each default message?

**Comment by fourjr** [comment]
- [x] Modify the message when the opening of a ticket by the user is canceled. (`thread_cancelled`)
- [x] Modify the messages that are created for both the moderators and the user when using the contact command. (`thread_creation_contact_title`, `thread_creation_self_contact_response`, `thread_creation_contact_response`, mods see below)
- [x] Remove footers from embeds (message ID, timestamp, anon_tag, mod_tag, ...) (`show_timestamp` is already implemented, rest won't be implemented.)
- [x] Remove the list of roles in the thread creation message. (`thread_show_roles`)
- [x] Remove the age of the user's account in the creation message of the thread. (`thread_show_join_age`, `thread_show_account_age`)
- [ ] Customize the titles of the non-anonymous embeds, which would be the anon_tag. For example, 🔨 Staff | {user} (wontfix)

We don't typically add config options for messages solely seen by mods. See the brackets for the new config options and comments.

Implemented in v3.10.0-dev5
