### ISSUE TITLE
Add the reason why Modmail closes the thread if a user leaves the server.

### ISSUE THREAD

**Issue by XtoMHA96** [kyb3r/modmail#3075]
### Is your feature request related to a problem? Please elaborate.

![Close thread](https://i.imgur.com/zAafnzp.png)

When a user exits the server, the thread is closed but the reason is not shown.

### Describe the solution you'd like

Know the reason why Modmail has closed the thread.

### Does your solution involve any of the following?

- [X] Logviewer
- [ ] New config option

### Describe alternatives you've considered

Since there is the option of the configuration `close_on_leave_reason`, that this is shown in the logs, as the reason for closing in the Modmail message.

### Who will this benefit?

Clarify the reasons why the thread has been closed and it is registered.

**Comment by coleslaw12** [comment]
This is possible with the `close_on_leave_reason` config. WHich can be set with ?config set close_on_leave_reason <message>.

**Comment by fourjr** [comment]
Staged in v3.10.0-dev4
