### ISSUE TITLE
[BUG]: Contact command not working properly on “silent”

### ISSUE THREAD

**Issue by Philleco1** [kyb3r/modmail#3076]
### Bot Version

v3.9.4

### How are you hosting Modmail?

Other

### Error Logs

https://google.com/

### Additional Information

Debug hastebin is not valid, due to that the bot not erroring, and the fact that it’s unable to generate a link. 

The contact itself works as it needs to, but if you’re trying to contact someone, make the ticket appear in a specific category and want to do it silently, it doesn’t work properly. By that, I mean that the ticket is created, but it’s not moved to the correct category, nor is it silent. 
It’s only “breaking” whenever you put “silent” onto the command, else it works perfectly fine. 
This is the command I tried to execute, which “breaks”:
-contact \<discordUserId> \<categoryName> silent

I also tried with “silently”, it’s the same. 
Though the bot isn’t erroring, it’s just not doing what it’s supposed to do.

**Comment by lorenzo132** [comment]
can confirm

**Comment by fourjr** [comment]
Staged in v3.10.0-dev4
