### ISSUE TITLE
Allow multiple users in ?contact

### ISSUE THREAD

**Issue by Sasiko** [kyb3r/modmail#3082]
### Is your feature request related to a problem? Please elaborate.

Allow modmail to create private threads based on staff commands 

### Describe the solution you'd like

ie: !create pthread @user1 @user2 

The private thread will then invite user1 and user2 to the thread

!close pthread
to delete the thread

### Does your solution involve any of the following?

- [X] Logviewer
- [ ] New config option

### Describe alternatives you've considered

N/A

### Who will this benefit?

This could be useful in handling disputes where he says and she says can be mediated more easily as they will be directly talking to each other while moderators are there to moderate the conflict.

This can be useful since rather than relying traditional DM to create thread and relay messages of user1 and user2 messages which would take more time.

**Comment by fourjr** [comment]
This feature request will be changed to allowing multiple users in `?contact` to start a group conversation.

Tracking in #143

**Comment by Sasiko** [comment]
@fourjr would you add support for modmail that is located in 2 guilds. IE if bot is configured with inbox setup in modmail server with only staff members.

**Comment by fourjr** [comment]
@Sasiko what does that mean? doesn't modmail separate server setup do that?

**Comment by Sasiko** [comment]
I assume thats independent function from creating the thread itself
