### ISSUE TITLE
Plain snippets

### ISSUE THREAD

**Issue by SnakeGames** [kyb3r/modmail#3083]
### Is your feature request related to a problem? Please elaborate.

Nope.

### Describe the solution you'd like

I just think it'd be cool if you guys make it so where you have plain reply snippets. so 

STAFF MEMBER: SNIPPET 

:)

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

None

### Who will this benefit?

Some people, just a suggestion

### Additional Information

No other info.

**Comment by fourjr** [comment]
For now, you can use aliases `?alias add plainhello preply Hello!`
