### ISSUE TITLE
ModMail Bot Status & Activity Setting Commands

### ISSUE THREAD

**Issue by AustinHolderr** [kyb3r/modmail#3085]
### Is your feature request related to a problem? Please elaborate.

This feature request is *not* related to a problem.

I’d like for there to be commands that can be run to set different activities & statuses for the ModMail Bot.
_**Such as:**_
**For Activities:**
Playing, Competing in, Watching, Listening to, Streaming, etc.
**For Statuses:**
Online (Default), Idle, Do Not Disturb, and Invisible.

### Describe the solution you'd like

_**Commands to set to another command.**_
**What I mean by this is…**
For example you use these activity & status commands a lot…
Obviously the **Status** ones would just be `?online`, `?idle`, `?dnd`, and `?invisible`.
For the **Activity** ones, you can set a command to have all the arguments preset so when you use it the first time you can set the preset command by doing something like the following:
`?setstreaming <Title Argument>, <URL Argument>` **or** `?setwatching <Title Argument>, <Description Argument>` **or** `?setlistening <Title Argument>, <Description Argument>` **or** `?setplaying <Title Argument>, <Description Argument>` **or** `?setcompeting <Title Argument>, <Description Argument>`; which would then allow you to just use `?streaming` **or** `?watching` **or** `?listening` **or** `?playing` **or** `?competing` to automatically set that preset activity to the bot with one, simple command.

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

I’ve considered using a third party to do this but it did not work properly/as intended. I also tried updating the code on my own fork of this, which also did not work.

### Who will this benefit?

I feel like this would benefit people with little to no coding experience/knowledge and anyone else really that uses this ModMail Bot because they will be able to customize it to the fullest extent then.

**Comment by lorenzo132** [comment]
See `?help activity` and `?help status`.
This issue/feature request can be closed

**Comment by AustinHolderr** [comment]
> See `?help activity` and `?help status`.
> 
> This issue/feature request can be closed

Thanks; sorry, I didn't know this existed.
