### ISSUE TITLE
[BUG]: Error during deploying

### ISSUE THREAD

**Issue by Daniellop1** [kyb3r/modmail#3087]
### Bot Version

-

### How are you hosting Modmail?

Heroku

### Error Logs

https://pastebin.com/A5Gm1Vsd

**Comment by Jerrie-Aries** [comment]
You need to enable the privileged intents for your bot in the [Discord developer portal](https://discord.com/developers/applications).

Also if you run into any problems when deploying, join [Modmail Discord server](https://discord.gg/j5e9p8w) to get further supports and helps.

**Comment by fourjr** [comment]
Please ask for setup-related help on our [discord server](https://discord.gg/etJNHCQ).
