### ISSUE TITLE
responding in a groupthread results in new thread instead of groupthread channel

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3090]
### Bot Version

3.10.3

### How are you hosting Modmail?

Systemd

### Error Logs

https://hastebin.cc/viqogunimo.rb

### Additional Information

Open a thread > add 3 users to groupthread > have a user respond back in dm to a group message > new thread gets made for the person responding to group

**Comment by patrickklaeren** [comment]
Same here

**Comment by MIGI10** [comment]
Same here, I can only have a thread with two users, when the third is added that happens and the channel description doesn't include the third user's ID

**Comment by fourjr** [comment]
A fix is currently being tested on v3.11.0-dev3, fix is not confirmed yet.
