### ISSUE TITLE
[BUG]: ?contact xx#xxxx silently opens a thread outside of the Modmail category.

### ISSUE THREAD

**Issue by dirtyformal** [kyb3r/modmail#3091]
### Bot Version

v3.10.2

### How are you hosting Modmail?

Heroku

### Error Logs

https://hastebin.cc/jotaguxaxi

### Additional Information

**Overview**: 

When `@contact xx#xxxx silently` is run, it opens a modmail thread outside of the Modmail category. I have reset the `main_category_id` and `fallback_category_id` to the Modmail category id, with no change.

**Background**:

Previously we used to be able to run the `?contact xx#xxxx silently` command and it would open a new channel without notifying the user. When this was run after the v3.10.2 release, it would open a channel without notifying the user, however in a public 'meta' category.

Running the `?contact xx#xxxx silent` command would open the thread in the correct location, however it would notify the user.

Request a fix, or a short-term workaround to prevent notification of the user until a `?reply` command is send in the respective channel.

**Comment by Jerrie-Aries** [comment]
I can confirm this. The bot creates the channel in the first top category in the server.
