### ISSUE TITLE
Suggestion: Modmail make a note when adding people to group chat

### ISSUE THREAD

**Issue by YyAoMmIi** [kyb3r/modmail#3096]
### Is your feature request related to a problem? Please elaborate.

When adding people to group chat using the new `adduser` function, sometimes you forget how many users are in that thread. Branched off this issue: https://github.com/kyb3r/modmail/issues/143

### Describe the solution you'd like

Add an automated function similar to Note to the adduser / removeuser. 
When a user get added or removed, The Note will be updated to say x is in current thread.

[my prefix is =]
1) x start modmail.
2) staff adduser y to thread
--- when command is used, an automated note is made
Note: Thread is now a group chat. Current user: 2/10. Thread starter: x
Additional members: Y
2) Staff adduser z to thread
=adduser z
---- Note is updated to say
---- Thread is a group chat, current users 3/10. thread starter x
additional members: Y Z
3) staff removeuser y from thread
=removeuser y
---- Note is updated to say
---- Thread is a group chat, current users 2/10. thread starter x
additional members: Z
4) staff adduser a & b tothread
=adduser a b 
---- Note is updated to say
---- Thread is a group chat, current users 4/10. thread starter x
additional members: Z a b

this would be for internal use, so a note function. 

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

Above solution can be done manually, it just helps being automated. 

### Who will this benefit?

This would benefit people use the group chat function. An automated system helps with keeping track on members in a thread.

**Comment by fourjr** [comment]
New recipients and initial thread starters are already indicated in the initial "genesis message" which is pinned to the channel. An example is attached. If you want your note functionality, you can create a plugin instead.

![image](https://user-images.githubusercontent.com/28086837/142596904-fa8de2be-63d2-4a77-a768-2621765c47de.png)
