### ISSUE TITLE
Config Var [STATUS] Doesnt work

### ISSUE THREAD

**Issue by Reverion** [kyb3r/modmail#31]
The config variable `STATUS` does not work for me, after updating and all.
I am able to set it through the command, but I was told that would not be permanent

**Comment by turpedogamer** [comment]
^^

**Comment by granthood** [comment]
it has been prem for me

**Comment by Reverion** [comment]
> it has been perm for me
How did you do that? Could you contact me on discord `Reverion#2116`, would be much appreciated

**Comment by fourjr** [comment]
should work now

**Comment by lovish2001** [comment]
its not working 
http://prntscr.com/jggl4m

**Comment by NovaIAndii** [comment]
Are there any differences on ios? I tried it on my mac and as soon as i type in commands in the terminal its totally different. Plus, the command „start“ is not found. Pls help

**Comment by kyb3r** [comment]
Works now
