### ISSUE TITLE
Ability to reference snippets in aliases. 

### ISSUE THREAD

**Issue by Qwerty-133** [kyb3r/modmail#3108]
### Is your feature request related to a problem? Please elaborate.

There is currently no way to add aliases to snippets. One cannot have a snippet with a descriptive name and have a shorter, concise way to invoke it.

### Describe the solution you'd like

`?alias add alias-name snippet-name` should be possible. 

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

Adding a new snippet with the name of the "alias" you wish, with the same contents. This works, but is problematic when you want to pull up the list of snippets and see duplicated snippets. It also requires you to edit each snippet when you wish to change the contents. 

### Who will this benefit?

Mainly servers which use a lot of snippets and need aliases to them.

**Comment by Qwerty-133** [comment]
A better alternative could be having aliases directly be a part of the snippet interface, so that `snippet raw alias` wouldn't fail. Which would imply adding commands to add/remove aliases to snippets and `help snippet` possibly displaying its aliases as well.

**Comment by Qwerty-133** [comment]
@fourjr How should we be handling snippet edits/deletions? Updating the alias to match the new snippet name in the former case and removing the snippet from the alias in the latter seems to make the most sense to me (along with informing the user).

**Comment by fourjr** [comment]
@Qwerty-133 I think skipping the snippet step would work, yup.
