### ISSUE TITLE
Menu plugin

### ISSUE THREAD

**Issue by Mystik01** [kyb3r/modmail#3117]
### Is your feature request related to a problem? Please elaborate.

I would like to have category's for each ticket, this will help support team know a basic idea already on what type of issue they have. 

### Describe the solution you'd like

When a user opens a thread they are greeted asking about what type of issue they have, these can be edited in config settings. If no configs are set then just don't ask the question.

The issue type will show in the staff side ticket and maybe on the logsviewer and moving the thread into a different Discord category.  And ping different staff roles.

### Does your solution involve any of the following?

- [X] Logviewer
- [X] New config option

### Describe alternatives you've considered

Just moving the the ticket into a different Discord category.

### Who will this benefit?

Mainly just the staff, this can be useful so that the right staff are notified because you can set different permissions for each category. E.g in a Developer server, One category for issues within the Discord and only Discord mods will be able to help and a bug report category if the user wants to report a bug and the developers will be notified.

**Comment by lorenzo132** [comment]
This is a plugin @Mystik01 , try doing `?plugins add menu`
PR/Issue can be closed.

**Comment by Mystik01** [comment]
> This is a plugin @Mystik01 , try doing `?plugins add menu` PR/Issue can be closed.

aw thats cool thank you

**Comment by Mystik01** [comment]
> This is a plugin @Mystik01 , try doing `?plugins add menu` PR/Issue can be closed.

It only works if you DM the bot, it doesn't work if you react to open

**Comment by fourjr** [comment]
This issue should be created on the plugin's repo ([fourjr/modmail-plugins](https://github.com/fourjr/modmail-plugins)), not here.
