### ISSUE TITLE
Ability to delete logs on mongodb using commands and log id

### ISSUE THREAD

**Issue by Blizzard2875** [kyb3r/modmail#3118]
### Is your feature request related to a problem? Please elaborate.

Helps to clear spam mod mail threads from db

### Describe the solution you'd like

A command / slash command to remove a log by id

### Does your solution involve any of the following?

- [X] Logviewer
- [ ] New config option

### Describe alternatives you've considered

-

### Who will this benefit?

Everyone I suppose

**Comment by lorenzo132** [comment]
Already possible for a long time, `?logs delete https://your-cool-log.link`
PR can be closed.

**Comment by Blizzard2875** [comment]
Is it possible to close specific logs using the log id?

**Comment by lorenzo132** [comment]
> Is it possible to close specific logs using the log id?

yes,
