### ISSUE TITLE
LOTTIE discord default sticker fails to retrieve

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3119]
### Bot Version

v3.11.0-dev1

### How are you hosting Modmail?

Systemd

### Error Logs

![](https://fle.soulmusic.pro/file/shxshx/Grunion1401.png)

### Screenshots

![](https://fle.soulmusic.pro/file/shxshx/Grunion1401.png)

### Additional Information

https://discord.com/channels/359577438101176320/911664310487486576/911668656033919038

**Comment by fourjr** [comment]
https://pypi.org/project/lottie/

**Comment by fourjr** [comment]
Hey, after exploring how we can handle this... here are a couple options:
1. Generate a GIF within Modmail (takes ~10 seconds)
2. Pre-generate all GIFs and store it in Modmail/another external repo
3. Only generate the first frame (takes ~0.08 seconds)

I'm personally in favour of the 3rd option, 10 seconds for sending a message would definitely take too long and pre-generating gifs require constant updating on our side. Thoughts?

Does anyone know how often discord updates these stickers?

**Comment by TheDiscordHistorian** [comment]
> Hey, after exploring how we can handle this... here are a couple options:
> 
> 1. Generate a GIF within Modmail (takes ~10 seconds)
> 2. Pre-generate all GIFs and store it in Modmail/another external repo
> 3. Only generate the first frame (takes ~0.08 seconds)
> 
> I'm personally in favour of the 3rd option, 10 seconds for sending a message would definitely take too long and pre-generating gifs require constant updating on our side. Thoughts?
> 
> Does anyone know how often discord updates these stickers?

Users can also send custom stickers if they have nitro so maintaining would be difficult (Lottie is locked to partnered / verified servers), I agree with the 3rd option but just generate a png instead of a gif if it’s possible or 3rd as is works imo.

**Comment by fourjr** [comment]
If partnered servers can do LOTTIE as well, best to just generate a thumbnail.

**Comment by lorenzo132** [comment]
> Hey, after exploring how we can handle this... here are a couple options:
> 
> 1. Generate a GIF within Modmail (takes ~10 seconds)
> 2. Pre-generate all GIFs and store it in Modmail/another external repo
> 3. Only generate the first frame (takes ~0.08 seconds)
> 
> I'm personally in favour of the 3rd option, 10 seconds for sending a message would definitely take too long and pre-generating gifs require constant updating on our side. Thoughts?
> 
> Does anyone know how often discord updates these stickers?

would be nice to make it a config option, to either have it as opt 1 or 3
