### ISSUE TITLE
Cannot access Logs

### ISSUE THREAD

**Issue by Weirdo914** [kyb3r/modmail#312]
Whenever I open the Logs through the link. The heroku log website opens and shows an error-
```
Internal Server Error
The server encountered an internal error and cannot complete your request.
```

**Comment by StephenDaDev** [comment]
Are you in our Support Server? (If yes, please DM Modmail)

**Comment by officialpiyush** [comment]
Could be due to Discord throwing 502 cuz of Clouflare outage.
