### ISSUE TITLE
Logviewer/logviewer patron Breaks for every thread

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3121]
### Bot Version

v3.11.0-dev2

### How are you hosting Modmail?

Systemd

### Error Logs

https://hastebin.cc/ajubocufuw.sql

### Additional Information

https://publicmodmail.logs.vodka/logs/04f519d55a76

**Comment by lorenzo132** [comment]
Those are logviewer its logs, as modmail gave 0 logs

**Comment by TheDiscordHistorian** [comment]
This needs to be fixed in the log viewer, the error is occurring due to dpy being timeaware and log viewer using `datetime.datetime.utcnow()`, which is a dirty function and isn’t aware, it can be fixed by changing it to `datetime.datetime.now(datetime.timezone.utc)`.

**Comment by fourjr** [comment]
- https://github.com/kyb3r/logviewer/pull/44
- https://github.com/kyb3rr/logviewer-premium/pull/23
