### ISSUE TITLE
[BUG]: the block command stopped working

### ISSUE THREAD

**Issue by lorenzo132** [kyb3r/modmail#3131]
### Bot Version

4.0.0.dev6

### How are you hosting Modmail?

Systemd

### Error Logs

https://hastebin.cc/omopiqobip

### Additional Information

When having to much blocker users the blocked cmd to show the blocked users will stop responding and error out.

**Comment by fourjr** [comment]
Fix attempted in v4-dev8

**Comment by lorenzo132** [comment]
Reopening this, the list still fails to show when there's 1k+ users blocked.
Quering through the db takes more then 30minutes which makes it impossible to use the command.
This is with both Selfhosted DB's and mongo hosted DB's
cc @StephenDaDev

**Comment by lorenzo132** [comment]
> Reopening this, the list still fails to show when there's 1k+ users blocked. Quering through the db takes more then 30minutes which makes it impossible to use the command. This is with both Selfhosted DB's and mongo hosted DB's cc @StephenDaDev

Coolguy suggested making a cache using redis ( https://discord.com/channels/515071617815019520/528927720063631360/1065390687270473958 ) which would be nice, however i'm afraid the regular discord user does not know how to work with redis

**Comment by khakers** [comment]
From a quick look at the code, it doesn't seem like the database is involved at all aside from when the bot pulls the config at launch

**Comment by khakers** [comment]
Should also add, this issue (#3131)  seemed to have been timezone related (and not size) so you might want to make a new one.
