### ISSUE TITLE
Block not working

### ISSUE THREAD

**Issue by Zachary2311** [kyb3r/modmail#3132]
### Bot Version

3.10.2

### How are you hosting Modmail?

Heroku

### Error Logs

https://hastebin.cc/zuruzeciyi

**Comment by Akshit1025** [comment]
> ### Bot Version
> 3.10.2
> 
> ### How are you hosting Modmail?
> Heroku
> 
> ### Error Logs
> https://hastebin.cc/zuruzeciyi
> 
> ### Screenshots
> _No response_
> 
> ### Additional Information
> _No response_

Try removing the music plugin and try again
because in the logs the error is coming for the music plugin, not for the block command
