### ISSUE TITLE
[BUG]: ?contact xx#xxxx silently opens a thread outside of the Modmail category

### ISSUE THREAD

**Issue by dirtyformal** [kyb3r/modmail#3133]
### Bot Version

3.10.2

### How are you hosting Modmail?

Heroku

### Error Logs

https://hastebin.cc/ifatadefam.apache

### Additional Information

This is a duplication of Issue #3091, after having been fixed by PR #3092. This bug exists under the exact same fault conditions.

**Overview**:

When @contact xx#xxxx silently is run, it opens a modmail thread outside of the Modmail category. I have reset the main_category_id and fallback_category_id to the Modmail category id, with no change.

**Background**:

Previously we used to be able to run the ?contact xx#xxxx silently command and it would open a new channel without notifying the user. When this was run recently, it would open a channel without notifying the user, however in a public 'meta' category. This is the same if you truncate `silently` to `silent`.

Request a fix, as this is a critical feature for our server.

**Comment by dirtyformal** [comment]
Pinging original bug fixer - @Jerrie-Aries

**Comment by Atharv-Agarwal** [comment]
While PR #3092 has fixed the issue, it is in the dev branch and not the master. You will have to wait for an update in which the dev branch is merged or you could use the dev branch (This can be unstable at times)
