### ISSUE TITLE
[BUG]: Self Contact 400 Invalid Form Body

### ISSUE THREAD

**Issue by OoLunar** [kyb3r/modmail#3136]
### Bot Version

3.10.2

### How are you hosting Modmail?

Other

### Error Logs

https://hastebin.cc/irewowelen

### Additional Information

Minimal Reproduction: https://github.com/OoLunar/ModMail_Repro. Be sure to fill out the [ModMail Environment File](https://github.com/OoLunar/ModMail_Repro/blob/master/modmail.env)

**Comment by OoLunar** [comment]
This happens before and after running `?setup`

**Comment by JaedonLau** [comment]
Upgrade it to newer version 3.10.3.

**Comment by fourjr** [comment]
Unable to reproduce
