### ISSUE TITLE
Update from discord.py to another python framework 

### ISSUE THREAD

**Issue by FIRE-WATER799** [kyb3r/modmail#3138]
### Is your feature request related to a problem? Please elaborate.

Discord.py has been depreciated and one new framework I use is nextcord

### Describe the solution you'd like

Update discord.py to nextcord

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

None

### Who will this benefit?

This will benefit the whole bot as discord py is expected to break sometime in April or something if no one updates it.

**Comment by lorenzo132** [comment]
Hey @FIRE-WATER799 This is currently being worked on by @Taaku18 and @fourjr

**Comment by fourjr** [comment]
We will stick to using discord.py as development has resumed - #2990.
