### ISSUE TITLE
[BUG]: Plugins not loading in dev7

### ISSUE THREAD

**Issue by Cordila** [kyb3r/modmail#3141]
### Bot Version

4.0.0.dev7

### How are you hosting Modmail?

Heroku

### Error Logs

No debug logs.

### Screenshots

https://cdn.discordapp.com/attachments/950235045698863188/955452352473759754/unknown.png

### Additional Information

After the dev7 update, the bot is unable to load plugins. Have tried rebooting. Doesnt help.

**Comment by Cordila** [comment]
@fourjr Seems to be due to the last commit you made. Pinging you.

**Comment by fourjr** [comment]
All plugins are broken in v4.

**Comment by fourjr** [comment]
Could you send your plugin repo link?

**Comment by fourjr** [comment]
Will look into it, thanks.

**Comment by Cordila** [comment]
Any update?
