### ISSUE TITLE
Please update the docker repository

### ISSUE THREAD

**Issue by HydraTownRP** [kyb3r/modmail#3144]
### Is your feature request related to a problem? Please elaborate.

Please update the docker repository to the latest one on https://hub.docker.com/r/kyb3rr/modmail

### Describe the solution you'd like

None

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

None

### Who will this benefit?

All

**Comment by viharm** [comment]
This issue seems closed but the latest image on _Docker_ hub is still more than a year old. it appears to be based on _Modmail_ v3.9.5 (_discord.py_ v1.7.3).

**Comment by Cordila** [comment]
Unfortunetly it looks like neither fourjr or taku have access to the docker, it might need to be remade.

**Comment by Satellite-Galaxy** [comment]
#3228

**Comment by Taaku18** [comment]
The Docker image from the GitHub Container Registry should be up to date now, thanks to #3228. You can pull the image using `docker pull ghcr.io/kyb3r/modmail:master`.
