### ISSUE TITLE
The title command breaks the bot temporarily in that channel by setting "User ID" to -1

### ISSUE THREAD

**Issue by Cordila** [kyb3r/modmail#3151]
### Bot Version

4.0 dev9

### How are you hosting Modmail?

Other

### Error Logs

NA

### Additional Information

By default, the bot shows the first message of the modmail in the logs channel, but by using the title command, it used to set that instead. No error logs.

**Comment by Cordila** [comment]
![image](https://user-images.githubusercontent.com/49218334/165973687-e794a831-8452-4c46-bf0d-d7aded741e0e.png)

If it helps, look at the user id it set it to after using the title command.

**Comment by Cordila** [comment]
Tested in another thread, the bot seems to change back the channel name! Attached audit logs and me changing the name. I suspect this is the reason for #3150 The bot cant close the channel without the user ID being proper in the topic

![image](https://user-images.githubusercontent.com/49218334/165974585-23dfc391-1c7b-4eea-827b-657e08aca887.png)
![image](https://user-images.githubusercontent.com/49218334/165974591-2c37e756-31af-445a-86ba-760a40dce12a.png)
![image](https://user-images.githubusercontent.com/49218334/165974621-8b09690a-7e35-472c-82da-7930041fc601.png)

**Comment by Cordila** [comment]
https://github.com/kyb3r/modmail/blob/4ef803337b5c6359d6711cbd71f3c5188ec54918/core/utils.py#L245
https://github.com/kyb3r/modmail/blob/4ef803337b5c6359d6711cbd71f3c5188ec54918/core/utils.py#L257

Looks like, for some reason, sometimes it doesn't manage to find the user ID? 
https://github.com/kyb3r/modmail/blob/4ef803337b5c6359d6711cbd71f3c5188ec54918/core/utils.py#L223 
Link for where the regex is happening, if I understood regex at all, I would be able to for once help

**Comment by Cordila** [comment]
Pretty sure it broke somewhere in this commit 4eca2732ba31a99b576627ca951f09338147daef

**Comment by Cordila** [comment]
@Jerrie-Aries Since you did this ^ you probably have a better idea around this. I have tried combing through but only if I understood regex better

**Comment by fourjr** [comment]
@Cordila does this always happen for this particular user? (958407376451567717)

**Comment by Cordila** [comment]
I am unable to find a constant reproduction either, but I can confirm this happens with me. Funny part being this doesnt happen when I run in the Test server. Maybe some config I have is interfering? Let me try clean updating to dev14 and get back to you.

![image](https://user-images.githubusercontent.com/49218334/166617790-8c8ee6cb-d70b-41d3-9cbc-ce8f81c0a905.png)
ID: 705769248034914314

**Comment by Cordila** [comment]
Still having the same issue even after updating.

**Comment by JeDaYoshi** [comment]
Having the same issue in the latest commit too.

**Comment by Cordila** [comment]
Here is a user ID it worked for properly
756407638744629249

**Comment by JeDaYoshi** [comment]
I don't think it's something specific to certain user IDs not working.
For example, it did not work at first for my account, but did on further attempts.
