### ISSUE TITLE
[BUG]: Plugin downloads are broken because of changed URL

### ISSUE THREAD

**Issue by sebkuip** [kyb3r/modmail#3155]
### Bot Version

v4.0 (all versions)

### How are you hosting Modmail?

Other

### Error Logs

https://media.discordapp.net/attachments/529240018934431744/971518398540427335/unknown.png?width=1304&height=701

### Additional Information

In the plugins.py file, plugins are assigned the download URL as `f"https://github.com/{user}/{repo}/archive/{self.branch}.zip"` [right here](https://github.com/kyb3r/modmail/blob/77489be6a21cf4befeab1dc7fa2c2d2098104cbc/cogs/plugins.py#L49)

Github has changed the link format for downloading a zip archive of a repository to the following format: `https://github.com/{user}/{repo}/archive/refs/heads/{self.branch}.zip`.
This means that plugins cannot be downloaded from github from within the bot.

**Comment by Cordila** [comment]
I am still able to install and use plugins

**Comment by Cordila** [comment]
After debugging with the user who had the issue, a few corrections. 
Version is 3.10.3
Hosting Method is Heroku

I suspect the issue could be because github is blocking herokus access to access github repositories in view of the latest security breach. https://status.heroku.com
