### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Lee-F20** [kyb3r/modmail#3156]
### Is your feature request related to a problem? Please elaborate.

No its not 

### Describe the solution you'd like

For My suggestion I was thinking for the status like for example when people go ?status they can change the bot to either Online, idle ,dnd, and or Streaming I was thinking their could be one where it could make it look like the bot is on mobile so like the command could be ?status Mobile and The bot will act like its on phone. 

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

For My suggestion I was thinking for the status like for example when people go ?status they can change the bot to either Online, idle ,dnd, and or Streaming I was thinking their could be one where it could make it look like the bot is on mobile so like the command could be ?status Mobile and The bot will act like its on phone. 

### Who will this benefit?

It will benefit everyone

**Comment by StephenDaDev** [comment]
The ``?status`` and ``?activity`` commands already accomplish both of these actions. You can run ``?help status`` and ``?help activity`` for further details and usage instructions.

------ HELP (ACTIVITY) -----
> Set an activity status for the bot.

> Possible activity types:
>     - `playing`
>     - `streaming`
>     - `listening`
>     - `watching`
>     - `competing`

> When activity type is set to `listening`, it must be followed by a "to": "listening to..."

> When activity type is set to `competing`, it must be followed by a "in": "competing in..."

> When activity type is set to `streaming`, you can set the linked twitch page:
> - `?config set twitch_url https://www.twitch.tv/somechannel/`

> To remove the current activity status:
> - `?activity clear`

========================
