### ISSUE TITLE
Anonymous replies

### ISSUE THREAD

**Issue by SergeantShadoww** [kyb3r/modmail#316]
Hi, I was wondering if you could implement a command which is similar to "[p]config set reply_without_command true" but it is always anonymous replies.

Also, will the ability to close threads anonymously be a thing?

**Comment by StephenDaDev** [comment]
1. I would recommend renaming this to something along the lines of ``anonreply without command`` so it is not confused as a ``[p]anonreply`` suggestion.
2. Closing threads anonymously is already a feature, you just need to add a close message for example ``[p]close I have decided to close this thread`` and it will not show the user who closed it.
