### ISSUE TITLE
[BUG]: little typo

### ISSUE THREAD

**Issue by FynnT076** [kyb3r/modmail#3160]
### Bot Version

v3.10.3

### How are you hosting Modmail?

Heroku

### Error Logs

There is no error, but still: https://hastebin.cc/xurabejoda 

### Screenshots

![Screenshot 2022-05-28 17 48 33](https://user-images.githubusercontent.com/64733407/170866262-48389e39-179e-4e68-aa5a-c7b4d13ac189.png)

### Additional Information

Little typo here! You forgot one `!

**Comment by Jerrie-Aries** [comment]
This has already been fixed in `dev` version.
