### ISSUE TITLE
Ability to pause auto close timer

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#317]
With the new ``thread_auto_close`` in [v3.0.0](https://github.com/kyb3r/modmail/blob/master/CHANGELOG.md#v300) some times you may not want a thread to close, such as an interview, test thread, thread your keeping open as a reminder, etc. So you can run a command such as ``!stopclose`` and the timer until close is stopped

**Comment by kyb3r** [comment]
`?close cancel` exists

**Comment by StephenDaDev** [comment]
Does that stop the auto close (not ordered by a human?)

**Comment by kyb3r** [comment]
Yes

**Comment by StephenDaDev** [comment]
I just did it and it said there was no scheduled close

**Comment by StephenDaDev** [comment]
**works fine**

# Already Exists
