### ISSUE TITLE
[BUG]: Having a user called "silent"/"silently" in the server confuses silent contact

### ISSUE THREAD

**Issue by Erisa** [kyb3r/modmail#3179]
### Bot Version

3.10.3

### How are you hosting Modmail?

Heroku

### Error Logs

https://haste.erisa.uk/agiquq.apache

### Screenshots

![image](https://user-images.githubusercontent.com/14004943/186561058-82917187-7226-4c04-9852-e5d308ee6f9d.png)
![image](https://user-images.githubusercontent.com/14004943/186561938-1ce508d5-2ebb-48ca-91b4-b87658b558bf.png)

### Additional Information

If a user in the server is called `silent` or `silently` then the flow `?contact @user silent` or `?contact @user silently` respectively will become confused and a open a non-silent thread with both `@user` and the user called `silent` or `silently`.

If unnoticed this results in the contact not being silent (Shows the recipient who opened the thread) and the silent/silently user receiving all of the modmail communication in that thread.

Reproduction is somewhat simple, just have a user named `silent` or `silently` in the server and use `?contact @user silent` against a different user.

From my understanding this appears to happen because the `users` argument will do a "greedy" match against any users it can find before getting to the `silent`/`silently` argument after it, causing the `silent`/`silently` to be dropped and the matching user to be added to the list in its place.

https://github.com/kyb3r/modmail/blob/be14cca89742cd691f6b91f0d0931a074ad81e3b/cogs/modmail.py#L1333-L1340

**Comment by Cordila** [comment]
Can reproduce
