### ISSUE TITLE
[BUG]: Python Version

### ISSUE THREAD

**Issue by ConnorHV** [kyb3r/modmail#3193]
### Bot Version

Trying to get to V4

### How are you hosting Modmail?

Heroku

### Error Logs

Dont have any logs

### Screenshots

![image](https://user-images.githubusercontent.com/96971163/191383476-29841829-cb68-4a56-bfd0-89d77b28dd7b.png)

<img width="403" alt="image" src="https://user-images.githubusercontent.com/96971163/191383578-156c2afd-5dd7-4c3d-bcfb-1a1d43fecebc.png">

### Additional Information

I dont know if im the only one but when I try and create a new app on heroku be able to host my bot, its saying that it doesnt support py 3.10.3 and so Im not able to get my bot going because it cant connect/ create my app

**Comment by 0vql** [comment]
No same here

**Comment by ConnorHV** [comment]
Thanks. Hopefully it will work when I get home👍

**Comment by ConnorHV** [comment]
Heroku is now working with 3.10.7 - My bot is now up and running, thanks for the help
