### ISSUE TITLE
Ability to disable the thread close message

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#320]
For my use case, I don’t really want to include a thread close message, I just want to have the thread close silently by default. A setting to enable close silently by default would be helpful for me and some others who would prefer no thread close message.

**Comment by kyb3r** [comment]
Use an alias for closing silently `?alias add c close silently`

**Comment by codeinteger6** [comment]
What about for `thread_auto_close_response`? Can this be done silently?
