### ISSUE TITLE
[BUG]: The 'logs' does not work correctly

### ISSUE THREAD

**Issue by XtoMHA96** [kyb3r/modmail#3200]
### Bot Version

4.0.1

### How are you hosting Modmail?

PM2

### Error Logs

https://hastebin.com/rowogoheca.rb

### Screenshots

![image](https://user-images.githubusercontent.com/25475587/191689848-4f6087b0-c5f3-4d67-8e29-6b1cf2496848.png)

### Additional Information

When the 'logs' command is used, the bot does not send user data. The only thing that appears is that "The bot is typing"

**Comment by Jerrie-Aries** [comment]
Yes, I can confirm this.

Maybe due to old logs don't have the `title` key saved into the database.
Will try to take a look.

**Comment by StephenDaDev** [comment]
Can-repo 4.0.1
