### ISSUE TITLE
Suggestion: Dedicated Notes

### ISSUE THREAD

**Issue by matrix2113** [kyb3r/modmail#321]
Suggestion: allow a dedicated notes channel for a copy of user notes to also be posted in, so that they can be referenced even after the thread is closed

Idea: Void#8888

**Comment by StephenDaDev** [comment]
Use cases? I feel going back in the logs would be better as then you get the context for the note

**Comment by StephenDaDev** [comment]
[![](https://api.gh-polls.com/poll/01DRWTB0GYJ0270DX1YWT3RGRM/Yes%2C%20Add%20it)](https://api.gh-polls.com/poll/01DRWTB0GYJ0270DX1YWT3RGRM/Yes%2C%20Add%20it/vote)
[![](https://api.gh-polls.com/poll/01DRWTB0GYJ0270DX1YWT3RGRM/No%2C%20Don't%20add%20it)](https://api.gh-polls.com/poll/01DRWTB0GYJ0270DX1YWT3RGRM/No%2C%20Don't%20add%20it/vote)

**Comment by Taaku18** [comment]
Please vote on this issue, if number of votes do not surpass a threshold, the issue will be marked as stale.
