### ISSUE TITLE
[BUG]: snippets command does not work in modmail guild id

### ISSUE THREAD

**Issue by Sasiko** [kyb3r/modmail#3227]
### Bot Version

4.0.1

### How are you hosting Modmail?

PM2

### Error Logs

https://hastebin.cc/uwababupux.sql

### Additional Information

Bot is in 2 guilds configured as Guild ID and Modmail ID
!snippet commands works only in guild id while snippets result in the error from provided error logs  when commands is executed in modmail guild

**Comment by Jerrie-Aries** [comment]
Related to #3205.

This is a known bug and being worked on, I believe.
The error was originated from a failure of getting the url of server icon.
For temp solution, make sure both guild and modmail guild have their icon set.
