### ISSUE TITLE
Hide inaccessible commands in help

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#325]
This was removed in the permissions update, it should be brought back. If the permissions for certain commands are changed, then the level next to each command in help are of no use. So hiding inaccessible commands would be better.

A `?help all` command could also be added, in case the person also wants to see inaccessible commands.

**Comment by StephenDaDev** [comment]
If you remember way back this used to be a feature! But was changed in [v2.18.0](https://github.com/kyb3r/modmail/blob/master/CHANGELOG.md#v2180) due to Check Failures

**Comment by codeinteger6** [comment]
> If you remember way back this used to be a feature! But was changed in [v2.18.0](https://github.com/kyb3r/modmail/blob/master/CHANGELOG.md#v2180) due to Check Failures

Yeah I remember

**Comment by StephenDaDev** [comment]
That's why it doesn't exist not sure if it will ever be added back

**Comment by fourjr** [comment]
we can implement similar to how rainbot does it
