### ISSUE TITLE
[Suggestion] Threads open = dnd // No threads = online

### ISSUE THREAD

**Issue by matrix2113** [kyb3r/modmail#326]
i have a fun idea, if there is open threads the bot status changes to Dnd
when its done, bot status changes back to online

Credit to Ironman#7040

**Comment by allipsee** [comment]
Good Idea!

**Comment by StephenDaDev** [comment]
Why would you want this other than to look cool?

**Comment by matrix2113** [comment]
@StephenDaDev ask the guy credited

**Comment by ClearlyElevated** [comment]
Good idea. I think that [IDLE] would be better for the bot not being used. & Maybe [ONLINE] when there is a ticket lending respond. [DND] when a ticket is in session. It would be a pain and prob not needed. But none the less a good idea I wouldnt have thought of

**Comment by StephenDaDev** [comment]
> @StephenDaDev ask the guy credited

Its not my job to track people down. I'll just use "There is no reason"

**Comment by AhmedXL** [comment]
> > @StephenDaDev ask the guy credited
> 
> Its not my job to track people down. I'll just use "There is no reason"

can you calm down, i am the guy who suggested the idea, at first i said it was a fun idea , not that highly needed one, its just fun idea .. if the developer want make it that would be a cool feature, don't want to that won't harm anyone

**Comment by StephenDaDev** [comment]
This is prob a plugin feature not a core

**Comment by Taaku18** [comment]
Although it’s a cool idea, it’s really not necessary and wouldn’t be beneficial to the general population using Modmail.
