### ISSUE TITLE
Certain category if a key word is met. 

### ISSUE THREAD

**Issue by TheFatalKiller** [kyb3r/modmail#331]
I suggest that there should be a command where you can specify a key word and specify what category the thread will move to if the key word is met. For example if someone started a thread saying “I would like to partner”, or “partner?” It would go to the partner category automatically. 
*edit*: I also think it would be a good idea if the key word is met and once it’s moved to the category a certain role would be mentioned (which the user has set up)

**Comment by StephenDaDev** [comment]
Good Idea

**Comment by StephenDaDev** [comment]
This issue isn't stale. And is highly requested due to the benefit it would add for auto-filtering threads to  the corresponding team that needs to deal with it.

**Comment by TheFatalKiller** [comment]
What stepthen said

**Comment by officialpiyush** [comment]
Nice idea

**Comment by officialpiyush** [comment]
Back in #649
