### ISSUE TITLE
Bot doesn't DM

### ISSUE THREAD

**Issue by nasirma1** [kyb3r/modmail#34]
I've done (my prefix) setup 
The bot has the permissions to create channel but it doesn't DM me when someone DMS thr bot

**Comment by fourjr** [comment]
it just creates a channel, isn't supposed to dm?

**Comment by nasirma1** [comment]
When someone dms the bot i don't receive a message anywhere , how do i solve this ?

**Comment by fourjr** [comment]
anything in heroku logs?

**Comment by nasirma1** [comment]
Nope

**Comment by fourjr** [comment]
send the logs here

**Comment by nasirma1** [comment]
oesports
 More 
      
 If you use GitHub, you can link your deploys to the code diff on GitHub. Hide   Connect to GitHub
Activity Feed

  novaimaaz@gmail.com
novaimaaz@gmail.com: Deployed
Today at 7:35 AM · v4
  novaimaaz@gmail.com
novaimaaz@gmail.com: Enable Logplex
Today at 7:34 AM · v3 · Roll back to here
  novaimaaz@gmail.com
novaimaaz@gmail.com: Set TOKEN, GUILD_ID, PREFIX config vars
Today at 7:34 AM · v2 · Roll back to here
  novaimaaz@gmail.com
novaimaaz@gmail.com: Build succeeded
Today at 7:34 AM · View build log
  novaimaaz@gmail.com
novaimaaz@gmail.com: Initial release
Today at 7:34 AM · v1 · Roll back to here

**Comment by fourjr** [comment]
did u turn worker on?

**Comment by fourjr** [comment]
send a screenshot of logs

**Comment by nasirma1** [comment]
Can we talk on discord ? maaz#2031

**Comment by nasirma1** [comment]
On discord i can send you the screens

**Comment by nasirma1** [comment]
Btw yes i Turner on worker

**Comment by fourjr** [comment]
join our support server

**Comment by nasirma1** [comment]
What's the link ?

**Comment by fourjr** [comment]
https://discord.gg/jvP42F go to #modmail

**Comment by nasirma1** [comment]
I joined , i asked help in #modmail
