### ISSUE TITLE
Contact Command "Improvements"

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#343]
When running the contact command auto delete the command and response

### Suggestion by Discord User Ari#1119

Additional Comment: Maybe have a command to configure which commands will be auto-deleted.

**Comment by conceptual-perception** [comment]
The intended behavior is to allow the discord username autocomplete to work when creating a new $contact thread.

Currently I'm creating $contact threads in a mod only garbage channel. This change would require two modifications:

* Deleting the command entered into a channel.
* Supressing or redirecting the output from Modmail to either a DM or a log channel.

**Comment by StephenDaDev** [comment]
Ok, Maybe I try to make this one. Can't be too hard....

**Comment by StephenDaDev** [comment]
[![](https://api.gh-polls.com/poll/01DJZQF9955K2Z39CW0WC7CVEB/Yes%2C%20Add%20this)](https://api.gh-polls.com/poll/01DJZQF9955K2Z39CW0WC7CVEB/Yes%2C%20Add%20this/vote)
[![](https://api.gh-polls.com/poll/01DJZQF9955K2Z39CW0WC7CVEB/Nope%2C%20Don't%20waste%20your%20time)](https://api.gh-polls.com/poll/01DJZQF9955K2Z39CW0WC7CVEB/Nope%2C%20Don't%20waste%20your%20time/vote)

**Comment by Taaku18** [comment]
implemented in v3.3.0
