### ISSUE TITLE
Suggestion: Config var to ignore threads starting with server link

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#346]
If a person starts a thread by DMing the bot with a Discord server invite, the bot will ignore it and won’t start a thread. This can be enabled via a config var and it would be helpful as some people tend to DM advertise and some server staff may not want invite links being sent to Modmail.

**Comment by Taaku18** [comment]
Sorry for the late reply. You can always just `block` the user, I don’t believe this should be a core feature native to Modmail.
