### ISSUE TITLE
Bug: Text from aliases not looking good

### ISSUE THREAD

**Issue by EGGamer** [kyb3r/modmail#348]
After the update 3.1.1, in our server we have aliases that are like the following:

!exampleAlias: "reply This is a test alias!!" && "close in 1 hour"

But the text doesn't look good in the embeds for the recipient and for us. Example image:

![alt text](https://i.imgur.com/UMJ9CGG.png)

As you can see there are some undesired spaces, even tho we wrote the text without the extra spaces. I also checked the config on the database and the text doesn't have the extra spaces.

So it looks like it's an error with some punctuation marks and some special characters like á, é, í, ó, ú

**Comment by EGGamer** [comment]
Okay I know how to reproduce this.

You need to have a multistep alias with a reply with special characters like **á, é, í, ó, ú, ¿, ¡**, and a close in X time as a second step.

**Comment by StephenDaDev** [comment]
Did we ever find out why it does this/does anyone know?

**Comment by Taaku18** [comment]
It has to do with how multistep alias loves to split and rejoin stuff. I’ll see if I can fix it for the next few updates.

**Comment by StephenDaDev** [comment]
👍

**Comment by StephenDaDev** [comment]
Issues with "Priority: High" or "bug" are not supposed to be stale.

**Comment by StephenDaDev** [comment]
Undo
