### ISSUE TITLE
Other roles cannot see messages

### ISSUE THREAD

**Issue by konsyr11** [kyb3r/modmail#354]
In my Discord server I have multiple roles, such as Administrator and Moderator. While I have given those roles the ModMail roles I wanted, every time a new ModMail thread comes in, they cannot see it. The permissions of the created channel are:
@everyone: Read Messages ✖️
I set permissions by myself, but when a new thread comes, they get reset of course. What should I do? Am I missing something from the configs?
Thanks in advance.

**Comment by papiersnipper** [comment]
The threads are spawned in the same category. You are able to set overrides for the whole category. That way, they can see every channel in that category, without the need to manually override each new thread.

**Comment by konsyr11** [comment]
I didn't know how to set category either, but I sent a message to ModMail in the ModMail Discord and got my answers. Thank you for your time though!
