### ISSUE TITLE
Having trouble setting up the bot

### ISSUE THREAD

**Issue by DtyKeys** [kyb3r/modmail#36]
I'm running the bot from a vps, and when I typed "python3.6 bot.py" it asked for the bot token. After I inputted the token I got 

Traceback (most recent call last):
  File "bot.py", line 511, in <module>
    Modmail.init()
  File "bot.py", line 107, in init
    raise e
  File "bot.py", line 105, in init
    bot.run(to_use, activity=discord.Game(os.getenv('STATUS')), reconnect=True)
TypeError: __init__() takes 1 positional argument but 2 were given
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efc850bcd30>

**Comment by park-inn** [comment]
##### I got the same issue.
I suggest hosting it on Heroku.
**Be sure to check [this](https://github.com/4rqm/modmail/issues/37) while creating the project.**
