### ISSUE TITLE
Sending Messages to another server

### ISSUE THREAD

**Issue by Computer-Man497** [kyb3r/modmail#369]
I'm not sure if this has been done yet, if it has can you let me know how i can do set it up.

**Problem**
-I want members in my main server to DM the modmail bot, we know that it creates a channel IN the SAME server. I want the messages to be sent to a separate server where the channel will be created there.

**What I have tried**
-I tried to set the category it sends to as a category in the server that I want them to be sent(From the ?config help command)
BUT That doesn't work.

**Help Please!**

**Comment by codeinteger6** [comment]
Check here: https://github.com/kyb3r/modmail/wiki/Seperate-Server-Setup

**Comment by Computer-Man497** [comment]
Many Thanks, This works well.
