### ISSUE TITLE
Mention at each message (auto)

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#380]
Similar to thread creation mention, it is suggested to have the ability to have mention occur on every new message. All threads turned on automatically.

### Suggestion by Discord User yeez#0076

**Comment by codeinteger6** [comment]
How about a smarter version of this, judging by whoever staff is active in the modmail conversation the people the bot will mention will change accordingly. It can be customised if needed.

**Comment by StephenDaDev** [comment]
Good Expansion,

**Comment by officialpiyush** [comment]
@StephenDaDev
