### ISSUE TITLE
No matching distribution found for pkg_resources

### ISSUE THREAD

**Issue by Computer-Man497** [kyb3r/modmail#386]
Ran it, installed all other packages fine, but brings up this error.
"Could not find a version that satisfies the requirement pkg_resources (from versions: )"
![grareh](https://user-images.githubusercontent.com/47247405/66036129-6a720d00-e504-11e9-9259-5557f08e3476.PNG)

**Comment by Computer-Man497** [comment]
Help would be much appreciated!

**Comment by Taaku18** [comment]
Pkg resources comes with the setuptools package which is usually pre installed with later versions of python, if you do not have it, you can do `pip install —upgrade setuptools`.
