### ISSUE TITLE
Add a plugin update all command

### ISSUE THREAD

**Issue by codeinteger6** [kyb3r/modmail#387]
What the title says. `[p]plugin update all` to update all installed plugins.

**Comment by papiersnipper** [comment]
I think that restarting the bot will result in a faster reload (and thus update) of the plugins. You can execute an eval like shown in the image below. However, if you're using Heroku, the plugins will auto update around every 24 hours. When you're using something like pm2 on a VPS, you can (and should) set the bot to restart every day as well.

**Comment by Taaku18** [comment]
Will be implemented in v3.3.0, `?plugins update`.
