### ISSUE TITLE
[Suggetions]Write custom text outside modmail embed post

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#389]
For some users, they may have forgotten that they have disabled 

**Link preview: Show website preview info from links pasted into the chat**

which result into this
https://cdn.discordapp.com/attachments/369801688443256837/629729288782086144/image0.png

This causes confusion and assumes its a bot issue.

**Implementation:**
1. Allow bot to optionally send messages to the recipient without the embed
2. Let us write a custom message to the bot auto response message **thread_creation_response** without embed to remind them to enable link preview to see our messages.

**Comment by StephenDaDev** [comment]
I'm un-staling this because many requests have been issued for this, and it is a useful feature for all users to be able to use the bot.
