### ISSUE TITLE
Setup Command Doesn't Enable Bot

### ISSUE THREAD

**Issue by CaliLifeStyle** [kyb3r/modmail#39]
Hello,

I had an issue with the bot not setting up.  I was able to resolve that.  It said setup successful, but when messaging the bot, it only creates a reaction in a DM.

**Comment by ExDe707** [comment]
Show your logs. If you have it on Heroku, here's how:
https://i.gyazo.com/16cc28c28c9c976f2b4fe76c90f346f4.png

**Comment by kyb3r** [comment]
fixed
