### ISSUE TITLE
[Suggestion] Temporarily refuse accepting new modmail ticket

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#390]
Include a config that let us disable modmail from creating new modmail threads and have a auto response msg, customized for that too.

Use case scenario:
*Bot server - When server is down and dev made proper announcement regarding downtime, people still bombard modmail, sometimes overwhelm the modmail especially on large bot servers.it would also serve as another good notification to tell users in modmail auto response msg that the server is down for X reason and should read Y channel for more info.

*Community - If server is currently undergoing a lock down as in channels being made read only mod, people might bombard in modmail asking why they cant send messag

**Comment by codeinteger6** [comment]
For now you can make the bot invisible or turn off the server

**Comment by StephenDaDev** [comment]
@Taaku18 This was added in [v3.3.0](https://github.com/kyb3r/modmail/blob/master/CHANGELOG.md#v330)
> - Ability to fully disable Modmail DM.
>   - ?disable all

(Close Requested - Thank You)

**Comment by StephenDaDev** [comment]
Oops! Wrong Citation
> - Ability to disable new threads from getting created.
>   - ?disable
