### ISSUE TITLE
Accidental Threads

### ISSUE THREAD

**Issue by matrix2113** [kyb3r/modmail#398]
Make it so the bot will ignore threads like “ok”, “thanks”.

**Comment by StephenDaDev** [comment]
#298 Alleviates this issue by adding a cooldown.

**Comment by StephenDaDev** [comment]
@matrix2113 Does the thread cooldown that was recently added eliminate this issue?

**Comment by fourjr** [comment]
Opened as I thought it was stale, now closing as #298 seems like issue is solved
