### ISSUE TITLE
Send Snippets even when not in a thread

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#403]
For those of us who have way too many snippets allow us to run the command and it will send it in the channel so we can see without having to type snippet first. It also adds the functionality of being able to use them in support channels (#modmail-support cough cough).

Submitted from my Nokia circa 1999

**Comment by DAzVise** [comment]
shouldn't `?snippet <snippet-name>` do the job?

**Comment by StephenDaDev** [comment]
> so we can see without having to type snippet first.

**Comment by DAzVise** [comment]
just make it an alias `?alias add s snippet` then running `?s <snippet-name>` would work, don't think they should be working outside of threads tbh.
