### ISSUE TITLE
Support Assignment

### ISSUE THREAD

**Issue by StephenDaDev** [kyb3r/modmail#407]
The ability to assign a thread to a certain supporter helps so everyone knows who is dealing with the thread. Could be achieved with ``?assign`` ``?unassign`` or clicking an emoji to "self-assign" on the creation embed. Would show who is assigned somewhere maybe on a separate embed or creation embed under ``Assigned:``.

**Comment by DAzVise** [comment]
Maybe you can just `?note` that?

**Comment by StephenDaDev** [comment]
``?notpe`` (that worked out better in my head)
