### ISSUE TITLE
OperationError: bad auth Authentication failed.

### ISSUE THREAD

**Issue by AzmainIsraq** [kyb3r/modmail#408]
please help me with it

![Screenshot (372)](https://user-images.githubusercontent.com/56102572/68269493-3bf7cc80-0084-11ea-9c4d-0785668651de.png)

**Comment by RealCyGuy** [comment]
Make sure your password doesn't have any special characters/symbols and the < and >.

**Comment by officialpiyush** [comment]
I see it taki

**Comment by AzmainIsraq** [comment]
![Screenshot (374)](https://user-images.githubusercontent.com/56102572/68293218-b857d300-00b7-11ea-94ee-53e859b26716.png)
now ? what to do ? its again crashing!!!

**Comment by DAzVise** [comment]
how about joining the support server in discord; would be much easier to communicate there.

**Comment by StephenDaDev** [comment]
Have you been able to solve this issue? If so please close this issue, otherwise please join our support server [5cttdfY](https://www.discord.gg/5cttdfY) and DM the modmail bot and the support team will be able to help you out.
