### ISSUE TITLE
Suggestion: Add support for Absolute timestamp in logs

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#409]
![](https://i.imgur.com/vAychqe.png)

now that discord finally support absolute timestamp regardless of the recency of the message, it would be great to see that option included in logs aswell.
Currently we only have relative timestamp which is good but not great for older messages.

![](https://i.imgur.com/Xr222Z7.png)

**Comment by StephenDaDev** [comment]
[General Question not really for suggester] Do the logs store absolute timestamps? If so this shouldn't be that hard to put in otherwise your looking at changing the way databases work (sorta)

**Comment by papiersnipper** [comment]
This is certainly something that could be accomplished with the current system. I propose to move this issue to the logviewer repo, as it's that code that should be changed in order to work.

**Comment by maidos** [comment]
i would like to see this on modmail too though

**Comment by StephenDaDev** [comment]
How though? Its already implemented through discord

**Comment by maidos** [comment]
follow the same format
https://i.imgur.com/1IU83aO.png

**Comment by StephenDaDev** [comment]
Then that's for the logviewer
