### ISSUE TITLE
Suggestions: Thread Reply Embed Author & Message Cooldown

### ISSUE THREAD

**Issue by Double77x** [kyb3r/modmail#410]
**1.** Perhaps adding the ability to set a cooldown on the creation of threads. In order to prevent unwanted spamming.
**2.** The ability to modify the Thread Reply embed Author from the user's profile to something like user.mention or something that displays the current users nickname rather than their profile name - The current state is not ideal because many users go by nicknames on servers etc. I know this is currently not possible using embed titles. However, It could be done by setting them to fields instead.

**Comment by StephenDaDev** [comment]
Partial Duplicate of #298
