### ISSUE TITLE
How to check the messages users send to bot?

### ISSUE THREAD

**Issue by ItsDiqmond** [kyb3r/modmail#43]
I tried testing the bot by sending message, it responds with a check reaction. But, I don't know how to check the messages and I want to be able to know how to do it. Please respond as soon as possible.

**Comment by ItsDiqmond** [comment]
Anyone here?

**Comment by ItsDiqmond** [comment]
@4rqm Dude help please, how do I check the responses?

**Comment by ItsDiqmond** [comment]
OMG WHY WON'T HE ANSWER ME

**Comment by kyb3r** [comment]
fixed the issue
