### ISSUE TITLE
Game Status

### ISSUE THREAD

**Issue by ItsDiqmond** [kyb3r/modmail#54]
Each time I set the game status, it successfully sets it but after a while, it disappears. I know no one has the permissions to do !!customstatus(that's my prefix), but I did check just in case and no one did the command nor able to change it. So, what is making it disappear, I removed the bot and invited it back and tested it and waited about an hour to see if it will keep doing that and it did. What is going on here?

**Comment by ExDe707** [comment]
As far as I know it's somehow restarting itself every few hours on Heroku.

**Comment by park-inn** [comment]
Can it automatically somehow restore its state?

### How this might be possible:

- Saving the config somehow
- Making it a config var


**Hopefully this gets implemented soon, and that I'm helping you!**

**Comment by kyb3r** [comment]
set a `STATUS` env variable.
