### ISSUE TITLE
[ISSUE] Unblock Command

### ISSUE THREAD

**Issue by Shadddd** [kyb3r/modmail#67]
@kyb3r **Unblock Command**

The unblock command needs fixing as it doesn't work correctly, so I had to remove the ID from the channel list in the info of the bot so that it would fix, quite slow doing it manually.

If I were to feedback your coding I would rate it 10/10 so good job on your work and have a great day!

Thanks, Shad #

**Comment by kyb3r** [comment]
Can you describe the steps needed to recreate the problem?
