### ISSUE TITLE
disable ping command?

### ISSUE THREAD

**Issue by Smir** [kyb3r/modmail#68]
need to add an option to disable the ping command or make it so that certain people can do it?

**Comment by kyb3r** [comment]
I've made it an admin only command now.

**Comment by Smir** [comment]
Brilliant, How do I update the app? 🤔

**Comment by kyb3r** [comment]
Delete Heroku app and remake it. Not elegant but afaik the easiest method for the layman.

**Comment by Smir** [comment]
just to let you know, I copied all the info over from the previous bot, stopped the worker, then turned on the worker for the new one, and it worked flawlessly 👍 

thanks

p.s is !anonreply added to this?
