### ISSUE TITLE
Thread logs via modmail API

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#78]
- [x] Centralised MongoDB accessed through Modmail API
- [x] API token has to be added in config variables (generated from kyber website after github oauth) <jwt>
- [x] github callback checks if github user forked repo? 
- [x] Logs are hosted on logs.kyb3r.tk/github-user-id/randomstring

jwt stores:
- github access token
- github username

get log random string:
```python
import secrets
return secrets.token_hex(6)
```

**Comment by kyb3r** [comment]
This makes #74 obsolete.
