### ISSUE TITLE
Looking for designers (front-end developers)

### ISSUE THREAD

**Issue by fourjr** [kyb3r/modmail#83]
We have a dashboard planned and more features relating [the log-viewer's front-end](https://github.com/kyb3r/logviewer). If anyone would want to volunteer to help out, DM `Kyber#6969` on Discord.

Necessary skills:
- Competent in HTML/CSS/JS

Good to have:
- Competent in Python

**Comment by iamluca** [comment]
@fourjr I can defiantly do this. DM me on Discord `Luca#1234`

**Comment by fourjr** [comment]
Going to close because I don't like open issues (but we are always looking for contributors).
