### ISSUE TITLE
allow users to setup aliases for commands

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#86]
examples 
!archive !a
!close !c
!reply !r

People appreciate short commands especially when there are some community that respond 30+ tickets a day.

**Comment by kyb3r** [comment]
## Aliases 

- Added this in `v2.0.0`. 

If called without subcommands, returns a list of aliases that are currently set.

### Subcommands 
- `add [name] [command]...`
- `del [name]`

You can also pass in arguments for the command you want to link to the alias, enabling you to do things like:

- `alias add i move Important`
