### ISSUE TITLE
[V.2]Block feature does not work

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#92]
To eliminate possible oversight in role permission, i gave the role administrator rights before i executed !block and !blocked.

The bot did respond seeing it typing message but then it stopped typing and no result.

Hm it appears i broke the bot now. It no  longer able to create tickets.

**Comment by kyb3r** [comment]
The block command requires a user_id as an argument if its not executed within a thread channel.

**Comment by kyb3r** [comment]
In v2.0.1 the block command now accepts a wider range of argument types, including usernames, nicknames, mentions, and user ids.
