### ISSUE TITLE
[V.2]embed contains username link that is invalid

### ISSUE THREAD

**Issue by maidos** [kyb3r/modmail#95]
https://i.imgur.com/8gpHv6Y.png
https://i.imgur.com/oQGqviM.png

Not sure what kind of link its intended to be when you click on the username

**Comment by kyb3r** [comment]
This is not a bug. We store a common message ID in that link so that we can track linked thread messages. This enables you to delete/edit thread messages and the action would reflect on the other side of the thread.

**Comment by kyb3r** [comment]
That id used to be in the footer, but had an idea to store it as a link so the embed would look cleaner.
